const group_11_decks = [
  { id: "ecommerce_shopping", ten: "Mua sắm & TMĐT", items: [
    {id:"ecommerce_shopping-001", term:"add to cart", pos:"v", ipa:"/æd tuː kɑːrt/", meaning_vi:"thêm vào giỏ hàng", example:"Don't forget to add to cart."},
    {id:"ecommerce_shopping-002", term:"checkout", pos:"n/v", ipa:"/ˈtʃekaʊt/", meaning_vi:"thanh toán/quầy thanh toán", example:"Proceed to checkout now."},
    {id:"ecommerce_shopping-003", term:"courier", pos:"n", ipa:"/ˈkʊriər/", meaning_vi:"nhân viên giao hàng", example:"The courier is at the door."},
    {id:"ecommerce_shopping-004", term:"delivery", pos:"n", ipa:"/dɪˈlɪvəri/", meaning_vi:"sự giao hàng", example:"Free delivery on orders over $50."},
    {id:"ecommerce_shopping-005", term:"refund", pos:"n/v", ipa:"/ˈriːfʌnd/", meaning_vi:"hoàn tiền", example:"I want a full refund."},
    {id:"ecommerce_shopping-006", term:"promo code", pos:"n", ipa:"/ˈproʊmoʊ koʊd/", meaning_vi:"mã giảm giá", example:"Enter the promo code at checkout."},
    {id:"ecommerce_shopping-007", term:"review", pos:"n/v", ipa:"/rɪˈvjuː/", meaning_vi:"đánh giá", example:"Read the customer reviews."},
    {id:"ecommerce_shopping-008", term:"shipping fee", pos:"n", ipa:"/ˈʃɪpɪŋ fiː/", meaning_vi:"phí vận chuyển", example:"The shipping fee is too high."},
    {id:"ecommerce_shopping-009", term:"inventory", pos:"n", ipa:"/ˈɪnvəntɔːri/", meaning_vi:"hàng tồn kho", example:"The item is out of inventory."},
    {id:"ecommerce_shopping-010", term:"wholesale", pos:"n/adj", ipa:"/ˈhoʊlseɪl/", meaning_vi:"bán buôn", example:"They sell at wholesale prices."},
    {id:"ecommerce_shopping-011", term:"retail", pos:"n/adj", ipa:"/ˈriːteɪl/", meaning_vi:"bán lẻ", example:"Retail stores are struggling."},
    {id:"ecommerce_shopping-012", term:"transaction", pos:"n", ipa:"/trænˈzækʃn/", meaning_vi:"giao dịch", example:"The transaction was successful."},
    {id:"ecommerce_shopping-013", term:"guarantee", pos:"n/v", ipa:"/ˌɡærənˈtiː/", meaning_vi:"bảo hành/cam kết", example:"This product has a 2-year guarantee."},
    {id:"ecommerce_shopping-014", term:"purchase", pos:"v/n", ipa:"/ˈpɜːrtʃəs/", meaning_vi:"mua/vật mua được", example:"Thank you for your purchase."},
    {id:"ecommerce_shopping-015", term:"invoice", pos:"n", ipa:"/ˈɪnvɔɪs/", meaning_vi:"hóa đơn", example:"I'll send you the invoice."},
    {id:"ecommerce_shopping-016", term:"bargain", pos:"n/v", ipa:"/ˈbɑːrɡən/", meaning_vi:"món hời/mặc cả", example:"This dress is a real bargain."},
    {id:"ecommerce_shopping-017", term:"receipt", pos:"n", ipa:"/rɪˈsiːt/", meaning_vi:"biên lai", example:"Keep your receipt for returns."},
    {id:"ecommerce_shopping-018", term:"voucher", pos:"n", ipa:"/ˈvaʊtʃər/", meaning_vi:"phiếu giảm giá", example:"Use this voucher for a discount."},
    {id:"ecommerce_shopping-019", term:"wishlist", pos:"n", ipa:"/ˈwɪʃlɪst/", meaning_vi:"danh sách mong muốn", example:"Add this to my wishlist."},
    {id:"ecommerce_shopping-020", term:"track", pos:"v", ipa:"/træk/", meaning_vi:"theo dõi (đơn hàng)", example:"You can track your package online."},
    {id:"ecommerce_shopping-021", term:"bulk", pos:"n/adj", ipa:"/bʌlk/", meaning_vi:"số lượng lớn", example:"It's cheaper to buy in bulk."},
    {id:"ecommerce_shopping-022", term:"e-wallet", pos:"n", ipa:"/ˈiː ˌwɑːlɪt/", meaning_vi:"ví điện tử", example:"Pay using your e-wallet."},
    {id:"ecommerce_shopping-023", term:"m-commerce", pos:"n", ipa:"/ˈem ˌkɑːmɜːrs/", meaning_vi:"thương mại di động", example:"The rise of m-commerce."},
    {id:"ecommerce_shopping-024", term:"bestseller", pos:"n", ipa:"/ˌbestˈselər/", meaning_vi:"sản phẩm bán chạy", example:"This book is a bestseller."},
    {id:"ecommerce_shopping-025", term:"out of stock", pos:"adj", ipa:"/aʊt əv stɑːk/", meaning_vi:"hết hàng", example:"Sorry, it's out of stock."},
    {id:"ecommerce_shopping-026", term:"backorder", pos:"n/v", ipa:"/ˈbækˌɔːrdər/", meaning_vi:"đặt hàng chờ", example:"The laptop is on backorder."},
    {id:"ecommerce_shopping-027", term:"bid", pos:"v/n", ipa:"/bɪd/", meaning_vi:"đấu thầu/giá thầu", example:"She made a high bid."},
    {id:"ecommerce_shopping-028", term:"clearance", pos:"n", ipa:"/ˈklɪrəns/", meaning_vi:"bán thanh lý", example:"Huge clearance sale today."},
    {id:"ecommerce_shopping-029", term:"complaint", pos:"n", ipa:"/kəmˈpleɪnt/", meaning_vi:"khiếu nại", example:"Customer complaints are rare."},
    {id:"ecommerce_shopping-030", term:"consumer", pos:"n", ipa:"/kənˈsuːmər/", meaning_vi:"người tiêu dùng", example:"Protecting consumer rights."},
    {id:"ecommerce_shopping-031", term:"curbside pickup", pos:"n", ipa:"", meaning_vi:"nhận hàng tại sảnh", example:"Try our curbside pickup service."},
    {id:"ecommerce_shopping-032", term:"customer service", pos:"n", ipa:"", meaning_vi:"dịch vụ khách hàng", example:"Excellent customer service."},
    {id:"ecommerce_shopping-033", term:"faulty", pos:"adj", ipa:"/ˈfɔːlti/", meaning_vi:"bị lỗi", example:"Return faulty goods."},
    {id:"ecommerce_shopping-034", term:"installment", pos:"n", ipa:"/ɪnˈstɔːlmənt/", meaning_vi:"trả góp", example:"Pay in monthly installments."},
    {id:"ecommerce_shopping-035", term:"loyalty program", pos:"n", ipa:"", meaning_vi:"chương trình khách hàng thân thiết", example:"Join our loyalty program."},
    {id:"ecommerce_shopping-036", term:"pre-order", pos:"v/n", ipa:"/ˌpriːˈɔːrdər/", meaning_vi:"đặt trước", example:"Pre-order the new game."},
    {id:"ecommerce_shopping-037", term:"return policy", pos:"n", ipa:"", meaning_vi:"chính sách trả hàng", example:"Check the return policy."},
    {id:"ecommerce_shopping-038", term:"shopping spree", pos:"n", ipa:"", meaning_vi:"mua sắm thả ga", example:"Go on a shopping spree."},
    {id:"ecommerce_shopping-039", term:"store credit", pos:"n", ipa:"", meaning_vi:"tiền tích lũy cửa hàng", example:"They gave me store credit."},
    {id:"ecommerce_shopping-040", term:"warehouse", pos:"n", ipa:"/ˈwerhaʊs/", meaning_vi:"kho hàng", example:"The warehouse is huge."}
  ]},
  { id: "social_digital_media", ten: "Mạng xã hội & Truyền thông", items: [
    {id:"social_digital_media-001", term:"subscriber", pos:"n", ipa:"/səbˈskraɪbər/", meaning_vi:"người đăng ký", example:"She has 1 million subscribers."},
    {id:"social_digital_media-002", term:"trending", pos:"adj", ipa:"/ˈtrendɪŋ/", meaning_vi:"đang thịnh hành", example:"The video is trending on YouTube."},
    {id:"social_digital_media-003", term:"podcast", pos:"n", ipa:"/ˈpɑːdkæst/", meaning_vi:"podcast", example:"I listen to a daily podcast."},
    {id:"social_digital_media-004", term:"livestream", pos:"n/v", ipa:"/ˈlaɪvstriːm/", meaning_vi:"phát trực tiếp", example:"Join the livestream tonight."},
    {id:"social_digital_media-005", term:"content creator", pos:"n", ipa:"", meaning_vi:"người sáng tạo nội dung", example:"He is a famous content creator."},
    {id:"social_digital_media-006", term:"privacy settings", pos:"n", ipa:"", meaning_vi:"thiết lập quyền riêng tư", example:"Check your privacy settings."},
    {id:"social_digital_media-007", term:"algorithm", pos:"n", ipa:"/ˈælɡərɪðəm/", meaning_vi:"thuật toán", example:"The algorithm recommends videos."},
    {id:"social_digital_media-008", term:"clickbait", pos:"n", ipa:"/ˈklɪkbeɪt/", meaning_vi:"mồi nhấp chuột", example:"That headline is just clickbait."},
    {id:"social_digital_media-009", term:"engagement", pos:"n", ipa:"/ɪnˈɡeɪdʒmənt/", meaning_vi:"sự tương tác", example:"Increase post engagement."},
    {id:"social_digital_media-010", term:"follower", pos:"n", ipa:"/ˈfɑːloʊər/", meaning_vi:"người theo dõi", example:"Followers love her photos."},
    {id:"social_digital_media-011", term:"hashtag", pos:"n", ipa:"/ˈhæʃtæɡ/", meaning_vi:"thẻ gắn", example:"Use the hashtag #travel."},
    {id:"social_digital_media-012", term:"influencer", pos:"n", ipa:"/ˈɪnfluənsər/", meaning_vi:"người ảnh hưởng", example:"Social media influencers."},
    {id:"social_digital_media-013", term:"notification", pos:"n", ipa:"/ˌnoʊtɪfɪˈkeɪʃn/", meaning_vi:"thông báo", example:"You have a new notification."},
    {id:"social_digital_media-014", term:"platform", pos:"n", ipa:"/ˈplætfɔːrm/", meaning_vi:"nền tảng", example:"TikTok is a popular platform."},
    {id:"social_digital_media-015", term:"profile", pos:"n", ipa:"/ˈproʊfaɪl/", meaning_vi:"hồ sơ cá nhân", example:"Update your profile picture."},
    {id:"social_digital_media-016", term:"share", pos:"v/n", ipa:"/ʃer/", meaning_vi:"chia sẻ", example:"Please share this post."},
    {id:"social_digital_media-017", term:"subscribe", pos:"v", ipa:"/səbˈskraɪb/", meaning_vi:"đăng ký", example:"Subscribe to my channel."},
    {id:"social_digital_media-018", term:"tag", pos:"v/n", ipa:"/tæɡ/", meaning_vi:"gắn thẻ", example:"Tag your friends in the comments."},
    {id:"social_digital_media-019", term:"viral", pos:"adj", ipa:"/ˈvaɪrəl/", meaning_vi:"lan truyền mạnh", example:"The meme went viral."},
    {id:"social_digital_media-020", term:"vlog", pos:"n", ipa:"/vlɑːɡ/", meaning_vi:"blog video", example:"She started a travel vlog."},
    {id:"social_digital_media-021", term:"ad", pos:"n", ipa:"/æd/", meaning_vi:"quảng cáo", example:"Skip the ad."},
    {id:"social_digital_media-022", term:"analytics", pos:"n", ipa:"/ˌænəˈlɪtɪks/", meaning_vi:"phân tích dữ liệu", example:"Check the channel analytics."},
    {id:"social_digital_media-023", term:"avatar", pos:"n", ipa:"/ˈævətɑːr/", meaning_vi:"ảnh đại diện", example:"Cool avatar!"},
    {id:"social_digital_media-024", term:"block", pos:"v", ipa:"/blɑːk/", meaning_vi:"chặn", example:"Block annoying users."},
    {id:"social_digital_media-025", term:"channel", pos:"n", ipa:"/ˈtʃænl/", meaning_vi:"kênh", example:"Welcome to my channel."},
    {id:"social_digital_media-026", term:"comment", pos:"n/v", ipa:"/ˈkɑːment/", meaning_vi:"bình luận", example:"Write a comment below."},
    {id:"social_digital_media-027", term:"direct message", pos:"n", ipa:"", meaning_vi:"tin nhắn trực tiếp", example:"Send me a direct message."},
    {id:"social_digital_media-028", term:"feed", pos:"n", ipa:"/fiːd/", meaning_vi:"bảng tin", example:"Scroll through your feed."},
    {id:"social_digital_media-029", term:"filter", pos:"n/v", ipa:"/ˈfɪltər/", meaning_vi:"bộ lọc", example:"Use a beauty filter."},
    {id:"social_digital_media-030", term:"handle", pos:"n", ipa:"/ˈhændl/", meaning_vi:"tên người dùng (có @)", example:"What's your Twitter handle?"},
    {id:"social_digital_media-031", term:"interface", pos:"n", ipa:"/ˈɪntərfeɪs/", meaning_vi:"giao diện", example:"A user-friendly interface."},
    {id:"social_digital_media-032", term:"meme", pos:"n", ipa:"/miːm/", meaning_vi:"ảnh chế/meme", example:"This meme is hilarious."},
    {id:"social_digital_media-033", term:"newsfeed", pos:"n", ipa:"/ˈnuːzfiːd/", meaning_vi:"bảng tin tức", example:"Check your newsfeed."},
    {id:"social_digital_media-034", term:"post", pos:"v/n", ipa:"/poʊst/", meaning_vi:"đăng bài/bài đăng", example:"Post a status update."},
    {id:"social_digital_media-035", term:"privacy", pos:"n", ipa:"/ˈpraɪvəsi/", meaning_vi:"quyền riêng tư", example:"We value your privacy."},
    {id:"social_digital_media-036", term:"reaction", pos:"n", ipa:"/riˈækʃn/", meaning_vi:"biểu cảm/phản ứng", example:"Choose a reaction."},
    {id:"social_digital_media-037", term:"sponsored", pos:"adj", ipa:"/ˈspɑːnsərd/", meaning_vi:"được tài trợ", example:"A sponsored post."},
    {id:"social_digital_media-038", term:"story", pos:"n", ipa:"/ˈstɔːri/", meaning_vi:"tin ngắn (24h)", example:"Post it on your story."},
    {id:"social_digital_media-039", term:"unfollow", pos:"v", ipa:"/ˌʌnˈfɑːloʊ/", meaning_vi:"bỏ theo dõi", example:"Unfollow boring accounts."},
    {id:"social_digital_media-040", term:"update", pos:"v/n", ipa:"/ˌʌpˈdeɪt/", meaning_vi:"cập nhật", example:"Update the app."}
  ]},
  { id: "personal_finance", ten: "Tài chính & Ngân hàng", items: [
    {id:"personal_finance-001", term:"account balance", pos:"n", ipa:"", meaning_vi:"số dư tài khoản", example:"Check your account balance."},
    {id:"personal_finance-002", term:"interest rate", pos:"n", ipa:"", meaning_vi:"lãi suất", example:"High interest rates."},
    {id:"personal_finance-003", term:"transfer", pos:"v/n", ipa:"/trænsˈfɜːr/", meaning_vi:"chuyển tiền", example:"Transfer money to my mom."},
    {id:"personal_finance-004", term:"saving account", pos:"n", ipa:"", meaning_vi:"tài khoản tiết kiệm", example:"Open a saving account."},
    {id:"personal_finance-005", term:"debt", pos:"n", ipa:"/det/", meaning_vi:"khoản nợ", example:"Pay off your debt."},
    {id:"personal_finance-006", term:"installment", pos:"n", ipa:"/ɪnˈstɔːlmənt/", meaning_vi:"trả góp", example:"Buy it in installments."},
    {id:"personal_finance-007", term:"ATM", pos:"n", ipa:"/ˌeɪ tiː ˈem/", meaning_vi:"máy rút tiền", example:"Where is the nearest ATM?"},
    {id:"personal_finance-008", term:"bank statement", pos:"n", ipa:"", meaning_vi:"sao kê ngân hàng", example:"Review your bank statement."},
    {id:"personal_finance-009", term:"borrow", pos:"v", ipa:"/ˈbɑːroʊ/", meaning_vi:"vay/mượn", example:"Can I borrow some money?"},
    {id:"personal_finance-010", term:"budget", pos:"n/v", ipa:"/ˈbʌdʒɪt/", meaning_vi:"ngân sách", example:"Plan your monthly budget."},
    {id:"personal_finance-011", term:"cash", pos:"n", ipa:"/kæʃ/", meaning_vi:"tiền mặt", example:"I don't have any cash."},
    {id:"personal_finance-012", term:"check", pos:"n", ipa:"/tʃek/", meaning_vi:"séc", example:"Pay by check."},
    {id:"personal_finance-013", term:"credit card", pos:"n", ipa:"", meaning_vi:"thẻ tín dụng", example:"Don't overspend on credit cards."},
    {id:"personal_finance-014", term:"currency", pos:"n", ipa:"/ˈkɜːrənsi/", meaning_vi:"tiền tệ", example:"Exchange foreign currency."},
    {id:"personal_finance-015", term:"debit card", pos:"n", ipa:"", meaning_vi:"thẻ ghi nợ", example:"Use your debit card."},
    {id:"personal_finance-016", term:"deposit", pos:"n/v", ipa:"/dɪˈpɑːzɪt/", meaning_vi:"tiền gửi/nộp tiền", example:"Make a deposit at the bank."},
    {id:"personal_finance-017", term:"expense", pos:"n", ipa:"/ɪkˈspens/", meaning_vi:"chi phí", example:"Travel expenses."},
    {id:"personal_finance-018", term:"fee", pos:"n", ipa:"/fiː/", meaning_vi:"phí", example:"Monthly service fee."},
    {id:"personal_finance-019", term:"income", pos:"n", ipa:"/ˈɪnkʌm/", meaning_vi:"thu nhập", example:"Monthly income."},
    {id:"personal_finance-020", term:"insurance", pos:"n", ipa:"/ɪnˈʃʊrəns/", meaning_vi:"bảo hiểm", example:"Health insurance."},
    {id:"personal_finance-021", term:"invest", pos:"v", ipa:"/ɪnˈvest/", meaning_vi:"đầu tư", example:"Invest in stocks."},
    {id:"personal_finance-022", term:"loan", pos:"n", ipa:"/loʊn/", meaning_vi:"khoản vay", example:"Apply for a student loan."},
    {id:"personal_finance-023", term:"mortgage", pos:"n", ipa:"/ˈmɔːrɡɪdʒ/", meaning_vi:"thế chấp", example:"Pay the monthly mortgage."},
    {id:"personal_finance-024", term:"overdraft", pos:"n", ipa:"/ˈoʊvərdræft/", meaning_vi:"thấu chi", example:"Avoid bank overdrafts."},
    {id:"personal_finance-025", term:"payment", pos:"n", ipa:"/ˈpeɪmənt/", meaning_vi:"thanh toán", example:"Make a payment."},
    {id:"personal_finance-026", term:"pension", pos:"n", ipa:"/ˈpenʃn/", meaning_vi:"lương hưu", example:"Live on a pension."},
    {id:"personal_finance-027", term:"PIN", pos:"n", ipa:"/pɪn/", meaning_vi:"mã số cá nhân", example:"Enter your PIN."},
    {id:"personal_finance-028", term:"profit", pos:"n", ipa:"/ˈprɑːfɪt/", meaning_vi:"lợi nhuận", example:"Make a profit."},
    {id:"personal_finance-029", term:"salary", pos:"n", ipa:"/ˈsæləri/", meaning_vi:"tiền lương", example:"Receive your salary."},
    {id:"personal_finance-030", term:"save", pos:"v", ipa:"/seɪv/", meaning_vi:"tiết kiệm", example:"Save for the future."},
    {id:"personal_finance-031", term:"stock", pos:"n", ipa:"/stɑːk/", meaning_vi:"cổ phiếu", example:"Buy stocks online."},
    {id:"personal_finance-032", term:"tax", pos:"n", ipa:"/tæks/", meaning_vi:"thuế", example:"Pay income tax."},
    {id:"personal_finance-033", term:"withdraw", pos:"v", ipa:"/wɪðˈdrɔː/", meaning_vi:"rút tiền", example:"Withdraw cash from ATM."},
    {id:"personal_finance-034", term:"yield", pos:"n", ipa:"/jiːld/", meaning_vi:"lợi suất", example:"High-yield investment."},
    {id:"personal_finance-035", term:"banknote", pos:"n", ipa:"/ˈbæŋknoʊt/", meaning_vi:"tờ tiền", example:"A ten-dollar banknote."},
    {id:"personal_finance-036", term:"billing cycle", pos:"n", ipa:"", meaning_vi:"chu kỳ thanh toán", example:"End of the billing cycle."},
    {id:"personal_finance-037", term:"collateral", pos:"n", ipa:"/kəˈlætərəl/", meaning_vi:"tài sản thế chấp", example:"Use the house as collateral."},
    {id:"personal_finance-038", term:"direct debit", pos:"n", ipa:"", meaning_vi:"ghi nợ trực tiếp", example:"Pay bills by direct debit."},
    {id:"personal_finance-039", term:"inflation", pos:"n", ipa:"/ɪnˈfleɪʃn/", meaning_vi:"lạm phát", example:"High inflation rate."},
    {id:"personal_finance-040", term:"wealth", pos:"n", ipa:"/welθ/", meaning_vi:"sự giàu có", example:"Build long-term wealth."}
  ]},
  { id: "arts_entertainment", ten: "Giải trí & Nghệ thuật", items: [
    {id:"arts_entertainment-001", term:"masterpiece", pos:"n", ipa:"/ˈmæstərpiːs/", meaning_vi:"kiệt tác", example:"The Mona Lisa is a masterpiece."},
    {id:"arts_entertainment-002", term:"performance", pos:"n", ipa:"/pərˈfɔːrməns/", meaning_vi:"buổi biểu diễn", example:"A great live performance."},
    {id:"arts_entertainment-003", term:"genre", pos:"n", ipa:"/ˈʒɑːnrə/", meaning_vi:"thể loại", example:"What is your favorite movie genre?"},
    {id:"arts_entertainment-004", term:"sculpture", pos:"n", ipa:"/ˈskʌlptʃər/", meaning_vi:"điêu khắc", example:"A modern sculpture."},
    {id:"arts_entertainment-005", term:"soundtrack", pos:"n", ipa:"/ˈsaʊndtræk/", meaning_vi:"nhạc phim", example:"I love the movie's soundtrack."},
    {id:"arts_entertainment-006", term:"exhibition", pos:"n", ipa:"/ˌeksɪˈbɪʃn/", meaning_vi:"triển lãm", example:"An art exhibition."},
    {id:"arts_entertainment-007", term:"actor", pos:"n", ipa:"/ˈæktər/", meaning_vi:"diễn viên", example:"A famous Hollywood actor."},
    {id:"arts_entertainment-008", term:"audience", pos:"n", ipa:"/ˈɔːdiəns/", meaning_vi:"khán giả", example:"The audience cheered."},
    {id:"arts_entertainment-009", term:"ballet", pos:"n", ipa:"/ˈbæleɪ/", meaning_vi:"ba lê", example:"Watch a ballet show."},
    {id:"arts_entertainment-010", term:"canvas", pos:"n", ipa:"/ˈkænvəs/", meaning_vi:"vải bạt/khung tranh", example:"Paint on a canvas."},
    {id:"arts_entertainment-011", term:"cast", pos:"n", ipa:"/kæst/", meaning_vi:"dàn diễn viên", example:"The movie has a great cast."},
    {id:"arts_entertainment-012", term:"celebrity", pos:"n", ipa:"/səˈlebrəti/", meaning_vi:"người nổi tiếng", example:"A-list celebrities."},
    {id:"arts_entertainment-013", term:"cinema", pos:"n", ipa:"/ˈsɪnəmə/", meaning_vi:"rạp phim", example:"Go to the cinema."},
    {id:"arts_entertainment-014", term:"comedy", pos:"n", ipa:"/ˈkɑːmədi/", meaning_vi:"hài kịch", example:"Watch a romantic comedy."},
    {id:"arts_entertainment-015", term:"concert", pos:"n", ipa:"/ˈkɑːnsərt/", meaning_vi:"buổi hòa nhạc", example:"Go to a rock concert."},
    {id:"arts_entertainment-016", term:"critic", pos:"n", ipa:"/ˈkrɪtɪk/", meaning_vi:"nhà phê bình", example:"Movie critics loved it."},
    {id:"arts_entertainment-017", term:"director", pos:"n", ipa:"/dəˈrektər/", meaning_vi:"đạo diễn", example:"A famous film director."},
    {id:"arts_entertainment-018", term:"drama", pos:"n", ipa:"/ˈdrɑːmə/", meaning_vi:"kịch/phim tâm lý", example:"I like Korean dramas."},
    {id:"arts_entertainment-019", term:"entertainment", pos:"n", ipa:"/ˌentərˈteɪnmənt/", meaning_vi:"sự giải trí", example:"Modern entertainment."},
    {id:"arts_entertainment-020", term:"festival", pos:"n", ipa:"/ˈfestɪvl/", meaning_vi:"lễ hội", example:"A music festival."},
    {id:"arts_entertainment-021", term:"gallery", pos:"n", ipa:"/ˈɡæləri/", meaning_vi:"phòng trưng bày", example:"Visit an art gallery."},
    {id:"arts_entertainment-022", term:"instrument", pos:"n", ipa:"/ˈɪnstrəmənt/", meaning_vi:"nhạc cụ", example:"Play a musical instrument."},
    {id:"arts_entertainment-023", term:"lyrics", pos:"n", ipa:"/ˈlɪrɪks/", meaning_vi:"lời bài hát", example:"Emotional lyrics."},
    {id:"arts_entertainment-024", term:"museum", pos:"n", ipa:"/mjuˈziːəm/", meaning_vi:"bảo tàng", example:"Visit the history museum."},
    {id:"arts_entertainment-025", term:"novel", pos:"n", ipa:"/ˈnɑːvl/", meaning_vi:"tiểu thuyết", example:"Read a classic novel."},
    {id:"arts_entertainment-026", term:"opera", pos:"n", ipa:"/ˈɑːprə/", meaning_vi:"nhạc kịch opera", example:"Go to the opera house."},
    {id:"arts_entertainment-027", term:"painting", pos:"n", ipa:"/ˈpeɪntɪŋ/", meaning_vi:"bức họa", example:"A beautiful oil painting."},
    {id:"arts_entertainment-028", term:"photography", pos:"n", ipa:"/fəˈtɑːɡrəfi/", meaning_vi:"nhiếp ảnh", example:"He loves digital photography."},
    {id:"arts_entertainment-029", term:"play", pos:"n", ipa:"/pleɪ/", meaning_vi:"vở kịch", example:"A Shakespearean play."},
    {id:"arts_entertainment-030", term:"plot", pos:"n", ipa:"/plɑːt/", meaning_vi:"cốt truyện", example:"The plot is exciting."},
    {id:"arts_entertainment-031", term:"portrait", pos:"n", ipa:"/ˈpɔːrtrət/", meaning_vi:"chân dung", example:"A family portrait."},
    {id:"arts_entertainment-032", term:"premiere", pos:"n", ipa:"/priˈmɪr/", meaning_vi:"buổi công chiếu", example:"The movie premiere."},
    {id:"arts_entertainment-033", term:"producer", pos:"n", ipa:"/prəˈduːsər/", meaning_vi:"nhà sản xuất", example:"A record producer."},
    {id:"arts_entertainment-034", term:"review", pos:"n", ipa:"/rɪˈvjuː/", meaning_vi:"đánh giá", example:"A positive review."},
    {id:"arts_entertainment-035", term:"script", pos:"n", ipa:"/skrɪpt/", meaning_vi:"kịch bản", example:"Read the movie script."},
    {id:"arts_entertainment-036", term:"show", pos:"n", ipa:"/ʃoʊ/", meaning_vi:"chương trình/buổi diễn", example:"A variety show."},
    {id:"arts_entertainment-037", term:"sketch", pos:"n/v", ipa:"/sketʃ/", meaning_vi:"bản phác thảo", example:"Draw a quick sketch."},
    {id:"arts_entertainment-038", term:"theater", pos:"n", ipa:"/ˈθiːətər/", meaning_vi:"nhà hát", example:"Go to the theater."},
    {id:"arts_entertainment-039", term:"ticket", pos:"n", ipa:"/ˈtɪkɪt/", meaning_vi:"vé", example:"Buy a concert ticket."},
    {id:"arts_entertainment-040", term:"venue", pos:"n", ipa:"/ˈvenjuː/", meaning_vi:"địa điểm tổ chức", example:"A great music venue."}
  ]},
  { id: "science_tech", ten: "Khoa học & Kỹ thuật", items: [
    {id:"science_tech-001", term:"renewable energy", pos:"n", ipa:"", meaning_vi:"năng lượng tái tạo", example:"Solar is renewable energy."},
    {id:"science_tech-002", term:"artificial intelligence", pos:"n", ipa:"", meaning_vi:"trí tuệ nhân tạo", example:"AI is changing the world."},
    {id:"science_tech-003", term:"experiment", pos:"n/v", ipa:"/ɪkˈsperɪmənt/", meaning_vi:"thí nghiệm", example:"Perform a science experiment."},
    {id:"science_tech-004", term:"gene", pos:"n", ipa:"/dʒiːn/", meaning_vi:"gen", example:"Study human genes."},
    {id:"science_tech-005", term:"atmosphere", pos:"n", ipa:"/ˈætməsfɪr/", meaning_vi:"khí quyển", example:"Protect the Earth's atmosphere."},
    {id:"science_tech-006", term:"lab", pos:"n", ipa:"/læb/", meaning_vi:"phòng thí nghiệm", example:"Work in a chemistry lab."},
    {id:"science_tech-007", term:"anatomy", pos:"n", ipa:"/əˈnætəmi/", meaning_vi:"giải phẫu học", example:"Study human anatomy."},
    {id:"science_tech-008", term:"asteroid", pos:"n", ipa:"/ˈæstərɔɪd/", meaning_vi:"tiểu hành tinh", example:"An asteroid in space."},
    {id:"science_tech-009", term:"astronomy", pos:"n", ipa:"/əˈstrɑːnəmi/", meaning_vi:"thiên văn học", example:"He studies astronomy."},
    {id:"science_tech-010", term:"bacteria", pos:"n", ipa:"/bækˈtɪriə/", meaning_vi:"vi khuẩn", example:"Wash hands to kill bacteria."},
    {id:"science_tech-011", term:"biology", pos:"n", ipa:"/baɪˈɑːlədʒi/", meaning_vi:"sinh học", example:"The study of living things."},
    {id:"science_tech-012", term:"cell", pos:"n", ipa:"/sel/", meaning_vi:"tế bào", example:"The building blocks of life."},
    {id:"science_tech-013", term:"chemistry", pos:"n", ipa:"/ˈkemɪstri/", meaning_vi:"hóa học", example:"Chemical reactions."},
    {id:"science_tech-014", term:"discovery", pos:"n", ipa:"/dɪˈskʌvəri/", meaning_vi:"sự khám phá", example:"A scientific discovery."},
    {id:"science_tech-015", term:"dna", pos:"n", ipa:"", meaning_vi:"mã di truyền", example:"Analyze the DNA sample."},
    {id:"science_tech-016", term:"ecology", pos:"n", ipa:"/iˈkɑːlədʒi/", meaning_vi:"sinh thái học", example:"Protect the local ecology."},
    {id:"science_tech-017", term:"electricity", pos:"n", ipa:"/ɪˌlekˈtrɪsəti/", meaning_vi:"điện", example:"Generate electricity."},
    {id:"science_tech-018", term:"element", pos:"n", ipa:"/ˈelɪmənt/", meaning_vi:"nguyên tố", example:"Gold is a chemical element."},
    {id:"science_tech-019", term:"energy", pos:"n", ipa:"/ˈenərdʒi/", meaning_vi:"năng lượng", example:"Nuclear energy."},
    {id:"science_tech-020", term:"evolution", pos:"n", ipa:"/ˌevəˈluːʃn/", meaning_vi:"sự tiến hóa", example:"The theory of evolution."},
    {id:"science_tech-021", term:"fossil", pos:"n", ipa:"/ˈfɑːsl/", meaning_vi:"hóa thạch", example:"Find a dinosaur fossil."},
    {id:"science_tech-022", term:"gravity", pos:"n", ipa:"/ˈɡrævəti/", meaning_vi:"trọng lực", example:"Gravity keeps us on the ground."},
    {id:"science_tech-023", term:"hypothesis", pos:"n", ipa:"/haɪˈpɑːθəsɪs/", meaning_vi:"giả thuyết", example:"Test the hypothesis."},
    {id:"science_tech-024", term:"innovation", pos:"n", ipa:"/ˌɪnəˈveɪʃn/", meaning_vi:"sự đổi mới", example:"Technological innovation."},
    {id:"science_tech-025", term:"invention", pos:"n", ipa:"/ɪnˈvenʃn/", meaning_vi:"sự phát minh", example:"The invention of the light bulb."},
    {id:"science_tech-026", term:"laboratory", pos:"n", ipa:"/ˈlæbrətɔːri/", meaning_vi:"phòng thí nghiệm", example:"Work in the laboratory."},
    {id:"science_tech-027", term:"matter", pos:"n", ipa:"/ˈmætər/", meaning_vi:"vật chất", example:"Solid, liquid, and gas."},
    {id:"science_tech-028", term:"microscope", pos:"n", ipa:"/ˈmaɪkrəskoʊp/", meaning_vi:"kính hiển vi", example:"Look through a microscope."},
    {id:"science_tech-029", term:"molecule", pos:"n", ipa:"/ˈmɑːlɪkjuːl/", meaning_vi:"phân tử", example:"Water molecule."},
    {id:"science_tech-030", term:"nebula", pos:"n", ipa:"/ˈnebjələ/", meaning_vi:"tinh vân", example:"A nebula in deep space."},
    {id:"science_tech-031", term:"organism", pos:"n", ipa:"/ˈɔːrɡənɪzəm/", meaning_vi:"sinh vật", example:"A tiny organism."},
    {id:"science_tech-032", term:"physics", pos:"n", ipa:"/ˈfɪzɪks/", meaning_vi:"vật lý", example:"The laws of physics."},
    {id:"science_tech-033", term:"radiation", pos:"n", ipa:"/ˌreɪdiˈeɪʃn/", meaning_vi:"phóng xạ", example:"Exposure to radiation."},
    {id:"science_tech-034", term:"robotics", pos:"n", ipa:"/roʊˈbɑːtɪks/", meaning_vi:"rô-bốt học", example:"Advancements in robotics."},
    {id:"science_tech-035", term:"satellite", pos:"n", ipa:"/ˈsætəlaɪt/", meaning_vi:"vệ tinh", example:"GPS uses satellites."},
    {id:"science_tech-036", term:"species", pos:"n", ipa:"/ˈspiːʃiːz/", meaning_vi:"loài", example:"An endangered species."},
    {id:"science_tech-037", term:"technology", pos:"n", ipa:"/tekˈnɑːlə dʒi/", meaning_vi:"công nghệ", example:"Modern technology."},
    {id:"science_tech-038", term:"theory", pos:"n", ipa:"/ˈθɪəri/", meaning_vi:"lý thuyết", example:"The big bang theory."},
    {id:"science_tech-039", term:"universe", pos:"n", ipa:"/ˈjuːnɪvɜːrs/", meaning_vi:"vũ trụ", example:"The vast universe."},
    {id:"science_tech-040", term:"virus", pos:"n", ipa:"/ˈvaɪrəs/", meaning_vi:"vi-rút", example:"A biological virus."}
  ]}
];
