const group_2_decks = [
  { id: "city_buildings", ten: "Tòa nhà trong thành phố", items: [
    {id:"city_buildings-001", term:"hospital", pos:"n", ipa:"/hɑspɪtʌl/", meaning_vi:"bệnh viện", example:"The hospital is near my house."},
    {id:"city_buildings-002", term:"clinic", pos:"n", ipa:"/klɪnɪk/", meaning_vi:"phòng khám", example:"The clinic opens at 9."},
    {id:"city_buildings-003", term:"pharmacy", pos:"n", ipa:"/fɑɹmʌsi/", meaning_vi:"nhà thuốc", example:"The pharmacy is across the street."},
    {id:"city_buildings-004", term:"school", pos:"n", ipa:"skul", meaning_vi:"trường học", example:"My sister goes to this school."},
    {id:"city_buildings-005", term:"university", pos:"n", ipa:"/junʌvɝsʌti/", meaning_vi:"đại học", example:"He studies at the university."},
    {id:"city_buildings-006", term:"library", pos:"n", ipa:"/laɪbɹɛɹi/", meaning_vi:"thư viện", example:"I’m going to the library."},
    {id:"city_buildings-007", term:"bookstore", pos:"n", ipa:"/bʊkstɔɹ/", meaning_vi:"hiệu sách", example:"We stopped by a bookstore."},
    {id:"city_buildings-008", term:"museum", pos:"n", ipa:"/mjuziʌm/", meaning_vi:"bảo tàng", example:"The museum is downtown."},
    {id:"city_buildings-009", term:"art gallery", pos:"n", ipa:"ɑrt ˈgæləri", meaning_vi:"phòng trưng bày nghệ thuật", example:"We visited an art gallery."},
    {id:"city_buildings-010", term:"movie theater", pos:"n", ipa:"ˈmuvi ˈθieɪtər", meaning_vi:"rạp phim", example:"Let’s go to the movie theater."},
    {id:"city_buildings-011", term:"shopping mall", pos:"n", ipa:"ˈʃɑpɪŋ mɔl", meaning_vi:"trung tâm thương mại", example:"Let’s meet at the shopping mall."},
    {id:"city_buildings-012", term:"supermarket", pos:"n", ipa:"/supɝmɑɹkɪt/", meaning_vi:"siêu thị", example:"I’m at the supermarket."},
    {id:"city_buildings-013", term:"convenience store", pos:"n", ipa:"kənˈvinjəns stɔr", meaning_vi:"cửa hàng tiện lợi", example:"There’s a convenience store nearby."},
    {id:"city_buildings-014", term:"restaurant", pos:"n", ipa:"/ɹɛstɝɑnt/", meaning_vi:"nhà hàng", example:"This restaurant is popular."},
    {id:"city_buildings-015", term:"cafe", pos:"n", ipa:"/kʌfeɪ/", meaning_vi:"quán cà phê", example:"Let’s grab coffee at a cafe."},
    {id:"city_buildings-016", term:"bakery", pos:"n", ipa:"/beɪkɝi/", meaning_vi:"tiệm bánh", example:"The bakery smells great."},
    {id:"city_buildings-017", term:"bank", pos:"n", ipa:"/bæŋk/", meaning_vi:"ngân hàng", example:"The bank is on the corner."},
    {id:"city_buildings-018", term:"ATM", pos:"n", ipa:"/eɪtiɛm/", meaning_vi:"cây ATM", example:"The ATM is inside the bank."},
    {id:"city_buildings-019", term:"post office", pos:"n", ipa:"poʊst ˈɔfəs", meaning_vi:"bưu điện", example:"I need to go to the post office."},
    {id:"city_buildings-020", term:"police station", pos:"n", ipa:"pəˈlis ˈsteɪʃən", meaning_vi:"đồn cảnh sát", example:"The police station is close."},
    {id:"city_buildings-021", term:"fire station", pos:"n", ipa:"faɪər ˈsteɪʃən", meaning_vi:"trạm cứu hỏa", example:"The fire station is nearby."},
    {id:"city_buildings-022", term:"city hall", pos:"n", ipa:"ˈsɪti hɔl", meaning_vi:"tòa thị chính", example:"City hall is downtown."},
    {id:"city_buildings-023", term:"courthouse", pos:"n", ipa:"/kɔɹthaʊs/", meaning_vi:"tòa án", example:"The courthouse is huge."},
    {id:"city_buildings-024", term:"office building", pos:"n", ipa:"ˈɔfəs ˈbɪldɪŋ", meaning_vi:"tòa nhà văn phòng", example:"He works in an office building."},
    {id:"city_buildings-025", term:"apartment building", pos:"n", ipa:"əˈpɑrtmənt ˈbɪldɪŋ", meaning_vi:"chung cư", example:"She lives in an apartment building."},
    {id:"city_buildings-026", term:"hotel", pos:"n", ipa:"/hoʊtɛl/", meaning_vi:"khách sạn", example:"We stayed at a hotel."},
    {id:"city_buildings-027", term:"bus station", pos:"n", ipa:"bəs ˈsteɪʃən", meaning_vi:"bến xe buýt", example:"The bus station is crowded."},
    {id:"city_buildings-028", term:"train station", pos:"n", ipa:"treɪn ˈsteɪʃən", meaning_vi:"ga tàu hỏa", example:"The train station is far."},
    {id:"city_buildings-029", term:"subway station", pos:"n", ipa:"ˈsəbˌweɪ ˈsteɪʃən", meaning_vi:"ga tàu điện ngầm", example:"The subway station is nearby."},
    {id:"city_buildings-030", term:"airport", pos:"n", ipa:"/ɛɹpɔɹt/", meaning_vi:"sân bay", example:"The airport is 30 minutes away."},
    {id:"city_buildings-031", term:"park", pos:"n", ipa:"/pɑɹk/", meaning_vi:"công viên", example:"Let’s walk in the park."},
    {id:"city_buildings-032", term:"playground", pos:"n", ipa:"/pleɪɡɹaʊnd/", meaning_vi:"sân chơi", example:"Kids are at the playground."},
    {id:"city_buildings-033", term:"stadium", pos:"n", ipa:"/steɪdiʌm/", meaning_vi:"sân vận động", example:"The stadium is packed."},
    {id:"city_buildings-034", term:"gym", pos:"n", ipa:"/dʒɪm/", meaning_vi:"phòng gym", example:"I go to the gym after work."},
    {id:"city_buildings-035", term:"church", pos:"n", ipa:"/tʃɝtʃ/", meaning_vi:"nhà thờ", example:"The church is old."},
    {id:"city_buildings-036", term:"temple", pos:"n", ipa:"/tɛmpʌl/", meaning_vi:"đền/chùa", example:"The temple is beautiful."},
    {id:"city_buildings-037", term:"bridge", pos:"n", ipa:"/bɹɪdʒ/", meaning_vi:"cầu", example:"Cross the bridge."},
    {id:"city_buildings-038", term:"parking garage", pos:"n", ipa:"ˈpɑrkɪŋ gərɑʒ", meaning_vi:"bãi đỗ xe nhiều tầng", example:"Park in the parking garage."},
    {id:"city_buildings-039", term:"gas station", pos:"n", ipa:"gæs ˈsteɪʃən", meaning_vi:"trạm xăng", example:"Stop at the gas station."},
    {id:"city_buildings-040", term:"barbershop", pos:"n", ipa:"/bɑɹbɝʃɑp/", meaning_vi:"tiệm cắt tóc nam", example:"He went to the barbershop."}
  ]},
  { id: "daily_verbs", ten: "Động từ thường nhật", items: [
    {id:"daily_verbs-001", term:"wake", pos:"v", ipa:"/weɪk/", meaning_vi:"thức dậy", example:"I wake up at 7."},
    {id:"daily_verbs-002", term:"sleep", pos:"v", ipa:"slip", meaning_vi:"ngủ", example:"I sleep about eight hours."},
    {id:"daily_verbs-003", term:"eat", pos:"v", ipa:"it", meaning_vi:"ăn", example:"I eat breakfast at home."},
    {id:"daily_verbs-004", term:"drink", pos:"v", ipa:"/dɹɪŋk/", meaning_vi:"uống", example:"Drink more water."},
    {id:"daily_verbs-005", term:"cook", pos:"v", ipa:"/kʊk/", meaning_vi:"nấu ăn", example:"I cook dinner sometimes."},
    {id:"daily_verbs-006", term:"work", pos:"v", ipa:"/wɝk/", meaning_vi:"làm việc", example:"I work from Monday to Friday."},
    {id:"daily_verbs-007", term:"study", pos:"v", ipa:"/stʌdi/", meaning_vi:"học", example:"She studies English every evening."},
    {id:"daily_verbs-008", term:"read", pos:"v", ipa:"/ɹɛd/", meaning_vi:"đọc", example:"I read before bed."},
    {id:"daily_verbs-009", term:"write", pos:"v", ipa:"/ɹaɪt/", meaning_vi:"viết", example:"He writes emails all day."},
    {id:"daily_verbs-010", term:"listen", pos:"v", ipa:"/lɪsʌn/", meaning_vi:"nghe", example:"I listen to podcasts."},
    {id:"daily_verbs-011", term:"watch", pos:"v", ipa:"/wɑtʃ/", meaning_vi:"xem", example:"We watch movies on weekends."},
    {id:"daily_verbs-012", term:"go", pos:"v", ipa:"/ɡoʊ/", meaning_vi:"đi", example:"I go to school by train."},
    {id:"daily_verbs-013", term:"come", pos:"v", ipa:"/kʌm/", meaning_vi:"đến", example:"Come here for a second."},
    {id:"daily_verbs-014", term:"leave", pos:"v", ipa:"liv", meaning_vi:"rời đi", example:"I have to leave now."},
    {id:"daily_verbs-015", term:"arrive", pos:"v", ipa:"/ɝaɪv/", meaning_vi:"đến nơi", example:"We arrived early."},
    {id:"daily_verbs-016", term:"buy", pos:"v", ipa:"/baɪ/", meaning_vi:"mua", example:"I bought groceries."},
    {id:"daily_verbs-017", term:"sell", pos:"v", ipa:"/sɛl/", meaning_vi:"bán", example:"They sell coffee."},
    {id:"daily_verbs-018", term:"pay", pos:"v", ipa:"/peɪ/", meaning_vi:"trả tiền", example:"I’ll pay by card."},
    {id:"daily_verbs-019", term:"meet", pos:"v", ipa:"mit", meaning_vi:"gặp", example:"Let’s meet at 6."},
    {id:"daily_verbs-020", term:"call", pos:"v", ipa:"/kɔl/", meaning_vi:"gọi", example:"Call me later."},
    {id:"daily_verbs-021", term:"text", pos:"v", ipa:"/tɛkst/", meaning_vi:"nhắn tin", example:"Text me when you arrive."},
    {id:"daily_verbs-022", term:"clean", pos:"v", ipa:"klin", meaning_vi:"dọn dẹp", example:"I cleaned my room."},
    {id:"daily_verbs-023", term:"wash", pos:"v", ipa:"/wɑʃ/", meaning_vi:"rửa/giặt", example:"I washed the dishes."},
    {id:"daily_verbs-024", term:"shower", pos:"v", ipa:"/ʃaʊɝ/", meaning_vi:"tắm", example:"I shower in the morning."},
    {id:"daily_verbs-025", term:"brush", pos:"v", ipa:"/bɹʌʃ/", meaning_vi:"chải", example:"Brush your teeth."},
    {id:"daily_verbs-026", term:"drive", pos:"v", ipa:"/dɹaɪv/", meaning_vi:"lái xe", example:"He drives to work."},
    {id:"daily_verbs-027", term:"ride", pos:"v", ipa:"/ɹaɪd/", meaning_vi:"đi (xe/đạp)", example:"I ride my bike."},
    {id:"daily_verbs-028", term:"walk", pos:"v", ipa:"/wɔk/", meaning_vi:"đi bộ", example:"Let’s walk home."},
    {id:"daily_verbs-029", term:"run", pos:"v", ipa:"/ɹʌn/", meaning_vi:"chạy", example:"I run in the park."},
    {id:"daily_verbs-030", term:"exercise", pos:"v", ipa:"/ɛksɝsaɪz/", meaning_vi:"tập thể dục", example:"I exercise three times a week."},
    {id:"daily_verbs-031", term:"stretch", pos:"v", ipa:"/stɹɛtʃ/", meaning_vi:"giãn cơ", example:"Stretch before you run."},
    {id:"daily_verbs-032", term:"shop", pos:"v", ipa:"/ʃɑp/", meaning_vi:"mua sắm", example:"I shop online."},
    {id:"daily_verbs-033", term:"cook", pos:"v", ipa:"/kʊk/", meaning_vi:"nấu", example:"I cook rice every day."},
    {id:"daily_verbs-034", term:"practice", pos:"v", ipa:"/pɹæktʌs/", meaning_vi:"luyện tập", example:"I practice speaking daily."},
    {id:"daily_verbs-035", term:"plan", pos:"v", ipa:"/plæn/", meaning_vi:"lên kế hoạch", example:"Let’s plan the trip."},
    {id:"daily_verbs-036", term:"check", pos:"v", ipa:"/tʃɛk/", meaning_vi:"kiểm tra", example:"Check your schedule."},
    {id:"daily_verbs-037", term:"wait", pos:"v", ipa:"/weɪt/", meaning_vi:"đợi", example:"Wait a minute."},
    {id:"daily_verbs-038", term:"help", pos:"v", ipa:"/hɛlp/", meaning_vi:"giúp", example:"Can you help me?"},
    {id:"daily_verbs-039", term:"fix", pos:"v", ipa:"/fɪks/", meaning_vi:"sửa", example:"He fixed the laptop."},
    {id:"daily_verbs-040", term:"relax", pos:"v", ipa:"/ɹɪlæks/", meaning_vi:"thư giãn", example:"I relax after work."}
  ]},
  { id: "health", ten: "Sức khỏe", items: [
    {id:"health-001", term:"health", pos:"n", ipa:"/hɛlθ/", meaning_vi:"sức khỏe", example:"Good health is important."},
    {id:"health-002", term:"healthy", pos:"adj", ipa:"/hɛlθi/", meaning_vi:"khỏe mạnh", example:"I’m trying to eat healthy."},
    {id:"health-003", term:"sick", pos:"adj", ipa:"/sɪk/", meaning_vi:"ốm", example:"I feel sick."},
    {id:"health-004", term:"ill", pos:"adj", ipa:"/ɪl/", meaning_vi:"bệnh", example:"She got ill."},
    {id:"health-005", term:"doctor", pos:"n", ipa:"/dɑktɝ/", meaning_vi:"bác sĩ", example:"I need to see a doctor."},
    {id:"health-006", term:"nurse", pos:"n", ipa:"/nɝs/", meaning_vi:"y tá", example:"The nurse was kind."},
    {id:"health-007", term:"hospital", pos:"n", ipa:"/hɑspɪtʌl/", meaning_vi:"bệnh viện", example:"He was taken to the hospital."},
    {id:"health-008", term:"clinic", pos:"n", ipa:"/klɪnɪk/", meaning_vi:"phòng khám", example:"The clinic is open today."},
    {id:"health-009", term:"medicine", pos:"n", ipa:"/mɛdʌsʌn/", meaning_vi:"thuốc", example:"Take your medicine after meals."},
    {id:"health-010", term:"pill", pos:"n", ipa:"/pɪl/", meaning_vi:"viên thuốc", example:"I took a pill."},
    {id:"health-011", term:"pain", pos:"n", ipa:"/peɪn/", meaning_vi:"đau", example:"I’m in pain."},
    {id:"health-012", term:"headache", pos:"n", ipa:"/hɛdeɪk/", meaning_vi:"đau đầu", example:"I have a headache."},
    {id:"health-013", term:"toothache", pos:"n", ipa:"/toothache/", meaning_vi:"đau răng", example:"He has a toothache."},
    {id:"health-014", term:"stomachache", pos:"n", ipa:"/stomachache/", meaning_vi:"đau bụng", example:"I have a stomachache."},
    {id:"health-015", term:"fever", pos:"n", ipa:"/fivɝ/", meaning_vi:"sốt", example:"She has a fever."},
    {id:"health-016", term:"cough", pos:"n", ipa:"/kɑf/", meaning_vi:"ho", example:"I can’t stop coughing."},
    {id:"health-017", term:"cold", pos:"n", ipa:"/koʊld/", meaning_vi:"cảm lạnh", example:"I caught a cold."},
    {id:"health-018", term:"flu", pos:"n", ipa:"/fluː/", meaning_vi:"cúm", example:"The flu is going around."},
    {id:"health-019", term:"injury", pos:"n", ipa:"/ɪndʒɝi/", meaning_vi:"chấn thương", example:"It was a minor injury."},
    {id:"health-020", term:"hurt", pos:"v", ipa:"/hɝt/", meaning_vi:"bị đau", example:"My back hurts."},
    {id:"health-021", term:"tired", pos:"adj", ipa:"/taɪɝd/", meaning_vi:"mệt", example:"I’m tired."},
    {id:"health-022", term:"stress", pos:"n", ipa:"/stɹɛs/", meaning_vi:"căng thẳng", example:"Stress can affect sleep."},
    {id:"health-023", term:"exercise", pos:"n", ipa:"/ɛksɝsaɪz/", meaning_vi:"tập thể dục", example:"I do exercise every morning."},
    {id:"health-024", term:"diet", pos:"n", ipa:"/daɪʌt/", meaning_vi:"chế độ ăn", example:"I’m on a diet."},
    {id:"health-025", term:"sleep", pos:"n", ipa:"slip", meaning_vi:"giấc ngủ", example:"I need more sleep."},
    {id:"health-026", term:"checkup", pos:"n", ipa:"/tʃɛkʌp/", meaning_vi:"khám định kỳ", example:"I’m going for a checkup."},
    {id:"health-027", term:"appointment", pos:"n", ipa:"/ʌpɔɪntmʌnt/", meaning_vi:"cuộc hẹn", example:"I have a doctor’s appointment."},
    {id:"health-028", term:"emergency", pos:"n", ipa:"/ɪmɝdʒʌnsi/", meaning_vi:"cấp cứu", example:"Call 911—it's an emergency."},
    {id:"health-029", term:"ambulance", pos:"n", ipa:"/æmbjʌlʌns/", meaning_vi:"xe cứu thương", example:"An ambulance arrived."},
    {id:"health-030", term:"pharmacy", pos:"n", ipa:"/fɑɹmʌsi/", meaning_vi:"nhà thuốc", example:"The pharmacy closes at 10."},
    {id:"health-031", term:"vitamin", pos:"n", ipa:"/vaɪtʌmʌn/", meaning_vi:"vitamin", example:"I take vitamins daily."},
    {id:"health-032", term:"allergy", pos:"n", ipa:"/ælɝdʒi/", meaning_vi:"dị ứng", example:"I have a peanut allergy."},
    {id:"health-033", term:"bandage", pos:"n", ipa:"/bændɪdʒ/", meaning_vi:"băng", example:"Put a bandage on it."},
    {id:"health-034", term:"rest", pos:"v", ipa:"/ɹɛst/", meaning_vi:"nghỉ ngơi", example:"You should rest."},
    {id:"health-035", term:"recover", pos:"v", ipa:"/ɹɪkʌvɝ/", meaning_vi:"hồi phục", example:"He recovered quickly."},
    {id:"health-036", term:"symptom", pos:"n", ipa:"/sɪmptʌm/", meaning_vi:"triệu chứng", example:"What symptoms do you have?"},
    {id:"health-037", term:"blood pressure", pos:"n", ipa:"bləd ˈprɛʃər", meaning_vi:"huyết áp", example:"My blood pressure is high."},
    {id:"health-038", term:"mental health", pos:"n", ipa:"ˈmɛntəl hɛlθ", meaning_vi:"sức khỏe tinh thần", example:"Mental health matters."},
    {id:"health-039", term:"hydration", pos:"n", ipa:"/haɪdɹeɪʃʌn/", meaning_vi:"bù nước", example:"Hydration is key."},
    {id:"health-040", term:"workout", pos:"n", ipa:"/wɝkaʊt/", meaning_vi:"buổi tập", example:"I did a quick workout."}
  ]},
  { id: "vegetables", ten: "Rau củ", items: [
    {id:"vegetables-001", term:"carrot", pos:"n", ipa:"/kæɹʌt/", meaning_vi:"cà rốt", example:"I add carrots to my soup."},
    {id:"vegetables-002", term:"potato", pos:"n", ipa:"/pʌteɪtoʊ/", meaning_vi:"khoai tây", example:"I like baked potatoes."},
    {id:"vegetables-003", term:"tomato", pos:"n", ipa:"/tʌmeɪtoʊ/", meaning_vi:"cà chua", example:"She bought fresh tomatoes."},
    {id:"vegetables-004", term:"onion", pos:"n", ipa:"/ʌnjʌn/", meaning_vi:"hành", example:"Chop the onion."},
    {id:"vegetables-005", term:"garlic", pos:"n", ipa:"/ɡɑɹlɪk/", meaning_vi:"tỏi", example:"Add some garlic."},
    {id:"vegetables-006", term:"cabbage", pos:"n", ipa:"/kæbʌdʒ/", meaning_vi:"bắp cải", example:"Cabbage is cheap."},
    {id:"vegetables-007", term:"lettuce", pos:"n", ipa:"/lɛtʌs/", meaning_vi:"xà lách", example:"Put lettuce in the sandwich."},
    {id:"vegetables-008", term:"spinach", pos:"n", ipa:"/spɪnʌtʃ/", meaning_vi:"rau bina", example:"Spinach is healthy."},
    {id:"vegetables-009", term:"broccoli", pos:"n", ipa:"/bɹɑkʌli/", meaning_vi:"bông cải xanh", example:"Broccoli is very healthy."},
    {id:"vegetables-010", term:"cauliflower", pos:"n", ipa:"/kɑlʌflaʊɝ/", meaning_vi:"bông cải trắng", example:"Roasted cauliflower is good."},
    {id:"vegetables-011", term:"cucumber", pos:"n", ipa:"/kjukʌmbɝ/", meaning_vi:"dưa leo", example:"I sliced cucumber."},
    {id:"vegetables-012", term:"pumpkin", pos:"n", ipa:"/pʌmpkɪn/", meaning_vi:"bí đỏ", example:"Pumpkin soup is tasty."},
    {id:"vegetables-013", term:"sweet potato", pos:"n", ipa:"swit pəˈteɪˌtoʊ", meaning_vi:"khoai lang", example:"Sweet potatoes are sweet."},
    {id:"vegetables-014", term:"corn", pos:"n", ipa:"/kɔɹn/", meaning_vi:"bắp", example:"Corn is in season."},
    {id:"vegetables-015", term:"peas", pos:"n", ipa:"piz", meaning_vi:"đậu Hà Lan", example:"I like peas."},
    {id:"vegetables-016", term:"beans", pos:"n", ipa:"binz", meaning_vi:"đậu", example:"Beans are high in protein."},
    {id:"vegetables-017", term:"eggplant", pos:"n", ipa:"/ɛɡplænt/", meaning_vi:"cà tím", example:"Eggplant absorbs oil."},
    {id:"vegetables-018", term:"zucchini", pos:"n", ipa:"zuˈkini", meaning_vi:"bí ngòi", example:"Zucchini cooks fast."},
    {id:"vegetables-019", term:"bell pepper", pos:"n", ipa:"bɛl ˈpɛpər", meaning_vi:"ớt chuông", example:"Bell peppers are crunchy."},
    {id:"vegetables-020", term:"chili", pos:"n", ipa:"/tʃɪli/", meaning_vi:"ớt", example:"This chili is spicy."},
    {id:"vegetables-021", term:"ginger", pos:"n", ipa:"/dʒɪndʒɝ/", meaning_vi:"gừng", example:"Ginger tea helps."},
    {id:"vegetables-022", term:"mushroom", pos:"n", ipa:"/mʌʃɹum/", meaning_vi:"nấm", example:"Add mushrooms to the pasta."},
    {id:"vegetables-023", term:"radish", pos:"n", ipa:"/ɹædɪʃ/", meaning_vi:"củ cải", example:"Radish is crunchy."},
    {id:"vegetables-024", term:"beet", pos:"n", ipa:"bit", meaning_vi:"củ dền", example:"Beets turn everything red."},
    {id:"vegetables-025", term:"celery", pos:"n", ipa:"/sɛlɝi/", meaning_vi:"cần tây", example:"Celery is low-calorie."},
    {id:"vegetables-026", term:"asparagus", pos:"n", ipa:"/ʌspɛɹʌɡʌs/", meaning_vi:"măng tây", example:"Asparagus is pricey."},
    {id:"vegetables-027", term:"okra", pos:"n", ipa:"/oʊkɹʌ/", meaning_vi:"đậu bắp", example:"Okra is slimy."},
    {id:"vegetables-028", term:"bamboo shoots", pos:"n", ipa:"bæmˈbu ʃuts", meaning_vi:"măng", example:"I like bamboo shoots."},
    {id:"vegetables-029", term:"leek", pos:"n", ipa:"lik", meaning_vi:"tỏi tây", example:"Leeks taste mild."},
    {id:"vegetables-030", term:"spring onion", pos:"n", ipa:"spərɪŋ ˈənjən", meaning_vi:"hành lá", example:"Top it with spring onion."},
    {id:"vegetables-031", term:"kale", pos:"n", ipa:"/keɪl/", meaning_vi:"cải xoăn", example:"Kale is trendy."},
    {id:"vegetables-032", term:"bok choy", pos:"n", ipa:"bɑk ʧɔɪ", meaning_vi:"cải thìa", example:"Bok choy is common in soups."},
    {id:"vegetables-033", term:"turnip", pos:"n", ipa:"/tɝnʌp/", meaning_vi:"củ cải trắng", example:"Turnips are earthy."},
    {id:"vegetables-034", term:"yam", pos:"n", ipa:"/jæm/", meaning_vi:"khoai mỡ", example:"Yams are sweet."},
    {id:"vegetables-035", term:"artichoke", pos:"n", ipa:"/ɑɹtʌtʃoʊk/", meaning_vi:"atiso", example:"Artichokes take time to cook."},
    {id:"vegetables-036", term:"cilantro", pos:"n", ipa:"/sɪlæntɹoʊ/", meaning_vi:"rau mùi", example:"Cilantro smells strong."},
    {id:"vegetables-037", term:"parsley", pos:"n", ipa:"/pɑɹsli/", meaning_vi:"rau mùi tây", example:"Add parsley on top."},
    {id:"vegetables-038", term:"dill", pos:"n", ipa:"/dɪl/", meaning_vi:"thì là", example:"Dill goes well with fish."},
    {id:"vegetables-039", term:"mint", pos:"n", ipa:"/mɪnt/", meaning_vi:"bạc hà", example:"Mint is refreshing."},
    {id:"vegetables-040", term:"vegetable", pos:"n", ipa:"/vɛdʒtʌbʌl/", meaning_vi:"rau", example:"Eat more vegetables."}
  ]},
  { id: "transportation", ten: "Phương tiện giao thông", items: [
    {id:"transportation-001", term:"car", pos:"n", ipa:"/kɑɹ/", meaning_vi:"ô tô", example:"I drive my car to work."},
    {id:"transportation-002", term:"bus", pos:"n", ipa:"/bʌs/", meaning_vi:"xe buýt", example:"She takes the bus every day."},
    {id:"transportation-003", term:"train", pos:"n", ipa:"/tɹeɪn/", meaning_vi:"tàu hỏa", example:"We traveled by train."},
    {id:"transportation-004", term:"subway", pos:"n", ipa:"/sʌbweɪ/", meaning_vi:"tàu điện ngầm", example:"The subway is very fast."},
    {id:"transportation-005", term:"tram", pos:"n", ipa:"/tɹæm/", meaning_vi:"xe điện", example:"Take the tram downtown."},
    {id:"transportation-006", term:"bike", pos:"n", ipa:"/baɪk/", meaning_vi:"xe đạp", example:"I ride my bike to school."},
    {id:"transportation-007", term:"bicycle", pos:"n", ipa:"/baɪsɪkʌl/", meaning_vi:"xe đạp", example:"He bought a bicycle."},
    {id:"transportation-008", term:"motorcycle", pos:"n", ipa:"/moʊtɝsaɪkʌl/", meaning_vi:"xe máy", example:"He rides a motorcycle."},
    {id:"transportation-009", term:"scooter", pos:"n", ipa:"/skutɝ/", meaning_vi:"xe tay ga", example:"She has a scooter."},
    {id:"transportation-010", term:"taxi", pos:"n", ipa:"/tæksi/", meaning_vi:"taxi", example:"Call a taxi."},
    {id:"transportation-011", term:"ride-share", pos:"n", ipa:"ride-share*", meaning_vi:"xe công nghệ", example:"I used a ride-share app."},
    {id:"transportation-012", term:"truck", pos:"n", ipa:"/tɹʌk/", meaning_vi:"xe tải", example:"A truck blocked the road."},
    {id:"transportation-013", term:"van", pos:"n", ipa:"/væn/", meaning_vi:"xe van", example:"They rented a van."},
    {id:"transportation-014", term:"pickup truck", pos:"n", ipa:"ˈpɪˌkəp trək", meaning_vi:"xe bán tải", example:"He drives a pickup truck."},
    {id:"transportation-015", term:"airplane", pos:"n", ipa:"/ɛɹpleɪn/", meaning_vi:"máy bay", example:"My airplane leaves at noon."},
    {id:"transportation-016", term:"flight", pos:"n", ipa:"/flaɪt/", meaning_vi:"chuyến bay", example:"The flight is delayed."},
    {id:"transportation-017", term:"airport", pos:"n", ipa:"/ɛɹpɔɹt/", meaning_vi:"sân bay", example:"We arrived at the airport early."},
    {id:"transportation-018", term:"helicopter", pos:"n", ipa:"/hɛlɪkɑptɝ/", meaning_vi:"trực thăng", example:"A helicopter flew overhead."},
    {id:"transportation-019", term:"boat", pos:"n", ipa:"/boʊt/", meaning_vi:"thuyền", example:"We took a boat tour."},
    {id:"transportation-020", term:"ship", pos:"n", ipa:"/ʃɪp/", meaning_vi:"tàu biển", example:"The ship left the port."},
    {id:"transportation-021", term:"ferry", pos:"n", ipa:"/fɛɹi/", meaning_vi:"phà", example:"We took the ferry."},
    {id:"transportation-022", term:"station", pos:"n", ipa:"/steɪʃʌn/", meaning_vi:"nhà ga", example:"Meet me at the station."},
    {id:"transportation-023", term:"platform", pos:"n", ipa:"/plætfɔɹm/", meaning_vi:"sân ga", example:"The train is on platform 3."},
    {id:"transportation-024", term:"ticket", pos:"n", ipa:"/tɪkʌt/", meaning_vi:"vé", example:"Keep your ticket."},
    {id:"transportation-025", term:"pass", pos:"n", ipa:"/pæs/", meaning_vi:"vé tháng/thẻ", example:"I bought a monthly pass."},
    {id:"transportation-026", term:"traffic", pos:"n", ipa:"/tɹæfɪk/", meaning_vi:"giao thông", example:"Traffic is heavy today."},
    {id:"transportation-027", term:"traffic jam", pos:"n", ipa:"ˈtræfɪk ʤæm", meaning_vi:"kẹt xe", example:"We’re stuck in a traffic jam."},
    {id:"transportation-028", term:"road", pos:"n", ipa:"/ɹoʊd/", meaning_vi:"đường", example:"This road is closed."},
    {id:"transportation-029", term:"highway", pos:"n", ipa:"/haɪweɪ/", meaning_vi:"xa lộ", example:"Take the highway."},
    {id:"transportation-030", term:"intersection", pos:"n", ipa:"/ɪntɝsɛkʃʌn/", meaning_vi:"ngã tư", example:"Turn at the intersection."},
    {id:"transportation-031", term:"crosswalk", pos:"n", ipa:"/kɹɑswɑk/", meaning_vi:"vạch qua đường", example:"Use the crosswalk."},
    {id:"transportation-032", term:"parking lot", pos:"n", ipa:"ˈpɑrkɪŋ lɔt", meaning_vi:"bãi đỗ xe", example:"The parking lot is full."},
    {id:"transportation-033", term:"gas station", pos:"n", ipa:"gæs ˈsteɪʃən", meaning_vi:"trạm xăng", example:"Stop at the gas station."},
    {id:"transportation-034", term:"speed limit", pos:"n", ipa:"spid ˈlɪmət", meaning_vi:"giới hạn tốc độ", example:"Watch the speed limit."},
    {id:"transportation-035", term:"seat belt", pos:"n", ipa:"sit bɛlt", meaning_vi:"dây an toàn", example:"Wear your seat belt."},
    {id:"transportation-036", term:"driver’s license", pos:"n", ipa:"driver’s* ˈlaɪsəns", meaning_vi:"bằng lái", example:"Do you have a driver’s license?"},
    {id:"transportation-037", term:"commute", pos:"n", ipa:"/kʌmjut/", meaning_vi:"đi làm hằng ngày", example:"My commute is long."},
    {id:"transportation-038", term:"delay", pos:"n", ipa:"/dɪleɪ/", meaning_vi:"trễ", example:"There’s a delay."},
    {id:"transportation-039", term:"route", pos:"n", ipa:"/ɹut/", meaning_vi:"tuyến đường", example:"What route should we take?"},
    {id:"transportation-040", term:"map", pos:"n", ipa:"/mæp/", meaning_vi:"bản đồ", example:"Open the map app."}
  ]}
];
