const group_4_decks = [
    {
        id: "topic_animals",
        ten: "Animals (Động vật)",
        items: [
            { id: "a1", term: "Dog", pos: "n.", ipa: "/dɒɡ/", meaning_vi: "Con chó", example: "The dog is barking loudly." },
            { id: "a2", term: "Cat", pos: "n.", ipa: "/kæt/", meaning_vi: "Con mèo", example: "My cat loves sleeping in the sun." },
            { id: "a3", term: "Mouse", pos: "n.", ipa: "/maʊs/", meaning_vi: "Con chuột", example: "The mouse ran across the floor." },
            { id: "a4", term: "Bird", pos: "n.", ipa: "/bɜːrd/", meaning_vi: "Con chim", example: "A little bird is singing in the tree." },
            { id: "a5", term: "Cow", pos: "n.", ipa: "/kaʊ/", meaning_vi: "Con bò", example: "The cow is eating grass in the field." },
            { id: "a6", term: "Pig", pos: "n.", ipa: "/pɪɡ/", meaning_vi: "Con heo", example: "Pigs are actually very intelligent animals." },
            { id: "a7", term: "Sheep", pos: "n.", ipa: "/ʃiːp/", meaning_vi: "Con cừu", example: "The sheep has thick white wool." },
            { id: "a8", term: "Horse", pos: "n.", ipa: "/hɔːrs/", meaning_vi: "Con ngựa", example: "She learned how to ride a horse." },
            { id: "a9", term: "Chicken", pos: "n.", ipa: "/ˈtʃɪkɪn/", meaning_vi: "Con gà", example: "The chicken laid an egg this morning." },
            { id: "a10", term: "Duck", pos: "n.", ipa: "/dʌk/", meaning_vi: "Con vịt", example: "The duck is swimming in the pond." },
            { id: "a11", term: "Elephant", pos: "n.", ipa: "/ˈelɪfənt/", meaning_vi: "Con voi", example: "Elephants have very long trunks." },
            { id: "a12", term: "Lion", pos: "n.", ipa: "/ˈlaɪən/", meaning_vi: "Sư tử", example: "The lion is the king of the jungle." },
            { id: "a13", term: "Tiger", pos: "n.", ipa: "/ˈtaɪɡər/", meaning_vi: "Con hổ", example: "Tigers have beautiful orange and black stripes." },
            { id: "a14", term: "Bear", pos: "n.", ipa: "/ber/", meaning_vi: "Con gấu", example: "The bear is sleeping in the cave." },
            { id: "a15", term: "Monkey", pos: "n.", ipa: "/ˈmʌŋki/", meaning_vi: "Con khỉ", example: "The monkey is climbing the tree." },
            { id: "a16", term: "Snake", pos: "n.", ipa: "/sneɪk/", meaning_vi: "Con rắn", example: "A green snake is hiding in the grass." },
            { id: "a17", term: "Crocodile", pos: "n.", ipa: "/ˈkrɒkədaɪl/", meaning_vi: "Cá sấu", example: "Do not swim here, there are crocodiles." },
            { id: "a18", term: "Turtle", pos: "n.", ipa: "/ˈtɜːrtl/", meaning_vi: "Con rùa", example: "The turtle moves very slowly." },
            { id: "a19", term: "Frog", pos: "n.", ipa: "/frɒɡ/", meaning_vi: "Con ếch", example: "The frog jumped into the water." },
            { id: "a20", term: "Rabbit", pos: "n.", ipa: "/ˈræbɪt/", meaning_vi: "Con thỏ", example: "Rabbits love to eat carrots." },
            { id: "a21", term: "Deer", pos: "n.", ipa: "/dɪr/", meaning_vi: "Con hươu", example: "We saw a deer in the forest." },
            { id: "a22", term: "Fox", pos: "n.", ipa: "/fɒks/", meaning_vi: "Con cáo", example: "The quick brown fox jumps over the lazy dog." },
            { id: "a23", term: "Wolf", pos: "n.", ipa: "/wʊlf/", meaning_vi: "Chó sói", example: "The wolf is howling at the moon." },
            { id: "a24", term: "Kangaroo", pos: "n.", ipa: "/ˌkæŋɡəˈruː/", meaning_vi: "Chuột túi", example: "Kangaroos carry their babies in a pouch." },
            { id: "a25", term: "Penguin", pos: "n.", ipa: "/ˈpeŋɡwɪn/", meaning_vi: "Chim cánh cụt", example: "Penguins live in cold environments." },
            { id: "a26", term: "Dolphin", pos: "n.", ipa: "/ˈdɒlfɪn/", meaning_vi: "Cá heo", example: "Dolphins are very smart sea creatures." },
            { id: "a27", term: "Whale", pos: "n.", ipa: "/weɪl/", meaning_vi: "Cá voi", example: "The blue whale is the largest animal." },
            { id: "a28", term: "Shark", pos: "n.", ipa: "/ʃɑːrk/", meaning_vi: "Cá mập", example: "Sharks have sharp teeth." },
            { id: "a29", term: "Octopus", pos: "n.", ipa: "/ˈɒktəpəs/", meaning_vi: "Bạch tuộc", example: "An octopus has eight arms." },
            { id: "a30", term: "Crab", pos: "n.", ipa: "/kræb/", meaning_vi: "Con cua", example: "The crab is walking sideways on the beach." },
            { id: "a31", term: "Spider", pos: "n.", ipa: "/ˈspaɪdər/", meaning_vi: "Con nhện", example: "The spider is spinning a web." },
            { id: "a32", term: "Butterfly", pos: "n.", ipa: "/ˈbʌtərflaɪ/", meaning_vi: "Con bướm", example: "The butterfly has colorful wings." },
            { id: "a33", term: "Bee", pos: "n.", ipa: "/biː/", meaning_vi: "Con ong", example: "The bee is collecting nectar from the flower." },
            { id: "a34", term: "Ant", pos: "n.", ipa: "/ænt/", meaning_vi: "Con kiến", example: "An ant can carry things heavier than itself." },
            { id: "a35", term: "Fly", pos: "n.", ipa: "/flaɪ/", meaning_vi: "Con ruồi", example: "There is a fly in my soup." },
            { id: "a36", term: "Mosquito", pos: "n.", ipa: "/məˈskiːtəʊ/", meaning_vi: "Con muỗi", example: "A mosquito bit me on the arm." },
            { id: "a37", term: "Snail", pos: "n.", ipa: "/sneɪl/", meaning_vi: "Ốc sên", example: "The snail leaves a shiny trail behind." },
            { id: "a38", term: "Worm", pos: "n.", ipa: "/wɜːrm/", meaning_vi: "Con giun", example: "Birds like to eat worms." },
            { id: "a39", term: "Bat", pos: "n.", ipa: "/bæt/", meaning_vi: "Con dơi", example: "Bats fly out of the cave at night." },
            { id: "a40", term: "Owl", pos: "n.", ipa: "/aʊl/", meaning_vi: "Cú mèo", example: "The owl is hunting in the dark." }
        ]
    },
    {
        id: "topic_body_parts",
        ten: "Body Parts (Bộ phận cơ thể)",
        items: [
            { id: "bp1", term: "Head", pos: "n.", ipa: "/hed/", meaning_vi: "Cái đầu", example: "She nodded her head." },
            { id: "bp2", term: "Hair", pos: "n.", ipa: "/her/", meaning_vi: "Tóc", example: "He has short black hair." },
            { id: "bp3", term: "Face", pos: "n.", ipa: "/feɪs/", meaning_vi: "Khuôn mặt", example: "Wash your face before going to bed." },
            { id: "bp4", term: "Eye", pos: "n.", ipa: "/aɪ/", meaning_vi: "Con mắt", example: "She has beautiful blue eyes." },
            { id: "bp5", term: "Ear", pos: "n.", ipa: "/ɪr/", meaning_vi: "Cái tai", example: "He whispered something in my ear." },
            { id: "bp6", term: "Nose", pos: "n.", ipa: "/nəʊz/", meaning_vi: "Cái mũi", example: "I have a runny nose today." },
            { id: "bp7", term: "Mouth", pos: "n.", ipa: "/maʊθ/", meaning_vi: "Cái miệng", example: "Open your mouth wide." },
            { id: "bp8", term: "Lip", pos: "n.", ipa: "/lɪp/", meaning_vi: "Môi", example: "Her lips were dry from the cold." },
            { id: "bp9", term: "Tooth", pos: "n.", ipa: "/tuːθ/", meaning_vi: "Răng", example: "Brush your teeth twice a day." },
            { id: "bp10", term: "Tongue", pos: "n.", ipa: "/tʌŋ/", meaning_vi: "Cái lưỡi", example: "I burned my tongue on the hot soup." },
            { id: "bp11", term: "Neck", pos: "n.", ipa: "/nek/", meaning_vi: "Cái cổ", example: "He wore a thick scarf around his neck." },
            { id: "bp12", term: "Shoulder", pos: "n.", ipa: "/ˈʃəʊldər/", meaning_vi: "Bờ vai", example: "She tapped him on the shoulder." },
            { id: "bp13", term: "Arm", pos: "n.", ipa: "/ɑːrm/", meaning_vi: "Cánh tay", example: "He broke his arm playing football." },
            { id: "bp14", term: "Elbow", pos: "n.", ipa: "/ˈelbəʊ/", meaning_vi: "Khuỷu tay", example: "Get your elbows off the table." },
            { id: "bp15", term: "Wrist", pos: "n.", ipa: "/rɪst/", meaning_vi: "Cổ tay", example: "She wears a watch on her left wrist." },
            { id: "bp16", term: "Hand", pos: "n.", ipa: "/hænd/", meaning_vi: "Bàn tay", example: "Wash your hands before eating." },
            { id: "bp17", term: "Finger", pos: "n.", ipa: "/ˈfɪŋɡər/", meaning_vi: "Ngón tay", example: "He has a ring on his finger." },
            { id: "bp18", term: "Thumb", pos: "n.", ipa: "/θʌm/", meaning_vi: "Ngón tay cái", example: "She sucked her thumb when she was a baby." },
            { id: "bp19", term: "Chest", pos: "n.", ipa: "/tʃest/", meaning_vi: "Ngực", example: "He felt a sharp pain in his chest." },
            { id: "bp20", term: "Back", pos: "n.", ipa: "/bæk/", meaning_vi: "Cái lưng", example: "My back hurts from carrying that heavy bag." },
            { id: "bp21", term: "Stomach", pos: "n.", ipa: "/ˈstʌmək/", meaning_vi: "Dạ dày, bụng", example: "Don't exercise on an empty stomach." },
            { id: "bp22", term: "Leg", pos: "n.", ipa: "/leɡ/", meaning_vi: "Cái chân", example: "My legs are tired after the long walk." },
            { id: "bp23", term: "Knee", pos: "n.", ipa: "/niː/", meaning_vi: "Đầu gối", example: "He fell and scraped his knee." },
            { id: "bp24", term: "Ankle", pos: "n.", ipa: "/ˈæŋkl/", meaning_vi: "Mắt cá chân", example: "She twisted her ankle while running." },
            { id: "bp25", term: "Foot", pos: "n.", ipa: "/fʊt/", meaning_vi: "Bàn chân", example: "My right foot is bigger than my left foot." },
            { id: "bp26", term: "Toe", pos: "n.", ipa: "/təʊ/", meaning_vi: "Ngón chân", example: "I stubbed my toe on the chair." },
            { id: "bp27", term: "Skin", pos: "n.", ipa: "/skɪn/", meaning_vi: "Da", example: "Apply lotion to keep your skin soft." },
            { id: "bp28", term: "Bone", pos: "n.", ipa: "/bəʊn/", meaning_vi: "Xương", example: "The dog buried a bone in the yard." },
            { id: "bp29", term: "Muscle", pos: "n.", ipa: "/ˈmʌsl/", meaning_vi: "Cơ bắp", example: "He exercises to build muscle." },
            { id: "bp30", term: "Heart", pos: "n.", ipa: "/hɑːrt/", meaning_vi: "Trái tim", example: "The heart pumps blood around the body." },
            { id: "bp31", term: "Brain", pos: "n.", ipa: "/breɪn/", meaning_vi: "Não bộ", example: "The brain controls the nervous system." },
            { id: "bp32", term: "Blood", pos: "n.", ipa: "/blʌd/", meaning_vi: "Máu", example: "He lost a lot of blood in the accident." },
            { id: "bp33", term: "Lung", pos: "n.", ipa: "/lʌŋ/", meaning_vi: "Phổi", example: "Smoking damages your lungs." },
            { id: "bp34", term: "Liver", pos: "n.", ipa: "/ˈlɪvər/", meaning_vi: "Gan", example: "Drinking too much alcohol affects the liver." },
            { id: "bp35", term: "Nail", pos: "n.", ipa: "/neɪl/", meaning_vi: "Móng (tay/chân)", example: "She painted her nails red." },
            { id: "bp36", term: "Eyebrow", pos: "n.", ipa: "/ˈaɪbraʊ/", meaning_vi: "Lông mày", example: "He raised an eyebrow in surprise." },
            { id: "bp37", term: "Eyelash", pos: "n.", ipa: "/ˈaɪlæʃ/", meaning_vi: "Lông mi", example: "She has very long eyelashes." },
            { id: "bp38", term: "Cheek", pos: "n.", ipa: "/tʃiːk/", meaning_vi: "Má", example: "Tears ran down her cheeks." },
            { id: "bp39", term: "Chin", pos: "n.", ipa: "/tʃɪn/", meaning_vi: "Cằm", example: "He rested his chin on his hand." },
            { id: "bp40", term: "Beard", pos: "n.", ipa: "/bɪrd/", meaning_vi: "Râu quai nón", example: "He decided to grow a beard." }
        ]
    },
    {
        id: "topic_clothing",
        ten: "Clothing & Accessories (Quần áo & Phụ kiện)",
        items: [
            { id: "c1", term: "Shirt", pos: "n.", ipa: "/ʃɜːrt/", meaning_vi: "Áo sơ mi", example: "He is wearing a white shirt." },
            { id: "c2", term: "T-shirt", pos: "n.", ipa: "/ˈtiː ʃɜːrt/", meaning_vi: "Áo thun", example: "I bought a new graphic T-shirt." },
            { id: "c3", term: "Pants", pos: "n.", ipa: "/pænts/", meaning_vi: "Quần dài", example: "These pants are too tight for me." },
            { id: "c4", term: "Jeans", pos: "n.", ipa: "/dʒiːnz/", meaning_vi: "Quần bò, quần jeans", example: "She wears blue jeans every day." },
            { id: "c5", term: "Shorts", pos: "n.", ipa: "/ʃɔːrts/", meaning_vi: "Quần đùi", example: "He wore shorts to the beach." },
            { id: "c6", term: "Dress", pos: "n.", ipa: "/dres/", meaning_vi: "Váy liền thân", example: "She looked beautiful in her red dress." },
            { id: "c7", term: "Skirt", pos: "n.", ipa: "/skɜːrt/", meaning_vi: "Chân váy", example: "She wore a black skirt to the office." },
            { id: "c8", term: "Jacket", pos: "n.", ipa: "/ˈdʒækɪt/", meaning_vi: "Áo khoác ngắn", example: "It's cold, you should wear a jacket." },
            { id: "c9", term: "Coat", pos: "n.", ipa: "/kəʊt/", meaning_vi: "Áo khoác dài, áo choàng", example: "He put on his heavy winter coat." },
            { id: "c10", term: "Sweater", pos: "n.", ipa: "/ˈswetər/", meaning_vi: "Áo len", example: "This wool sweater is very warm." },
            { id: "c11", term: "Suit", pos: "n.", ipa: "/suːt/", meaning_vi: "Bộ com-lê", example: "He wore a black suit to the wedding." },
            { id: "c12", term: "Tie", pos: "n.", ipa: "/taɪ/", meaning_vi: "Cà vạt", example: "You must wear a tie with that shirt." },
            { id: "c13", term: "Uniform", pos: "n.", ipa: "/ˈjuːnɪfɔːrm/", meaning_vi: "Đồng phục", example: "The students have to wear a school uniform." },
            { id: "c14", term: "Underwear", pos: "n.", ipa: "/ˈʌndərwer/", meaning_vi: "Đồ lót", example: "Pack enough underwear for the trip." },
            { id: "c15", term: "Pajamas", pos: "n.", ipa: "/pəˈdʒɑːməz/", meaning_vi: "Đồ ngủ", example: "He changed into his pajamas before bed." },
            { id: "c16", term: "Swimsuit", pos: "n.", ipa: "/ˈswɪmsuːt/", meaning_vi: "Đồ bơi", example: "Don't forget your swimsuit for the beach." },
            { id: "c17", term: "Hat", pos: "n.", ipa: "/hæt/", meaning_vi: "Cái mũ, nón", example: "Wear a hat to protect your face from the sun." },
            { id: "c18", term: "Cap", pos: "n.", ipa: "/kæp/", meaning_vi: "Mũ lưỡi trai", example: "He was wearing a baseball cap." },
            { id: "c19", term: "Scarf", pos: "n.", ipa: "/skɑːrf/", meaning_vi: "Khăn quàng cổ", example: "She wrapped a scarf around her neck." },
            { id: "c20", term: "Gloves", pos: "n.", ipa: "/ɡlʌvz/", meaning_vi: "Găng tay", example: "My hands are freezing, I need gloves." },
            { id: "c21", term: "Socks", pos: "n.", ipa: "/sɒks/", meaning_vi: "Tất, vớ", example: "He is wearing mismatched socks." },
            { id: "c22", term: "Shoes", pos: "n.", ipa: "/ʃuːz/", meaning_vi: "Giày", example: "Take off your shoes before entering." },
            { id: "c23", term: "Sneakers", pos: "n.", ipa: "/ˈsniːkərz/", meaning_vi: "Giày thể thao", example: "I bought a new pair of running sneakers." },
            { id: "c24", term: "Boots", pos: "n.", ipa: "/buːts/", meaning_vi: "Giày bốt, ủng", example: "She wore waterproof boots in the rain." },
            { id: "c25", term: "Slippers", pos: "n.", ipa: "/ˈslɪpərz/", meaning_vi: "Dép đi trong nhà", example: "I put on my warm slippers." },
            { id: "c26", term: "Sandals", pos: "n.", ipa: "/ˈsændlz/", meaning_vi: "Dép xăng đan", example: "Sandals are comfortable in the summer." },
            { id: "c27", term: "Belt", pos: "n.", ipa: "/belt/", meaning_vi: "Thắt lưng", example: "His pants were too big, so he used a belt." },
            { id: "c28", term: "Glasses", pos: "n.", ipa: "/ˈɡlæsɪz/", meaning_vi: "Mắt kính", example: "I can't read without my glasses." },
            { id: "c29", term: "Sunglasses", pos: "n.", ipa: "/ˈsʌnɡlæsɪz/", meaning_vi: "Kính râm", example: "It's bright outside, put on your sunglasses." },
            { id: "c30", term: "Watch", pos: "n.", ipa: "/wɒtʃ/", meaning_vi: "Đồng hồ đeo tay", example: "He checked his watch to see the time." },
            { id: "c31", term: "Ring", pos: "n.", ipa: "/rɪŋ/", meaning_vi: "Chiếc nhẫn", example: "She is wearing a beautiful diamond ring." },
            { id: "c32", term: "Necklace", pos: "n.", ipa: "/ˈnekləs/", meaning_vi: "Dây chuyền", example: "He gave her a gold necklace for her birthday." },
            { id: "c33", term: "Bracelet", pos: "n.", ipa: "/ˈbreɪslət/", meaning_vi: "Vòng đeo tay", example: "She wears a silver bracelet on her wrist." },
            { id: "c34", term: "Earrings", pos: "n.", ipa: "/ˈɪrɪŋz/", meaning_vi: "Hoa tai", example: "She lost one of her earrings." },
            { id: "c35", term: "Wallet", pos: "n.", ipa: "/ˈwɒlɪt/", meaning_vi: "Ví tiền (nam)", example: "He left his wallet at home." },
            { id: "c36", term: "Purse", pos: "n.", ipa: "/pɜːrs/", meaning_vi: "Ví nữ, túi xách nhỏ", example: "She put her phone in her purse." },
            { id: "c37", term: "Bag", pos: "n.", ipa: "/bæɡ/", meaning_vi: "Túi xách", example: "I carry my laptop in this bag." },
            { id: "c38", term: "Backpack", pos: "n.", ipa: "/ˈbækpæk/", meaning_vi: "Ba lô", example: "The student's backpack is very heavy." },
            { id: "c39", term: "Umbrella", pos: "n.", ipa: "/ʌmˈbrelə/", meaning_vi: "Cái ô, dù", example: "Take an umbrella, it's going to rain." },
            { id: "c40", term: "Raincoat", pos: "n.", ipa: "/ˈreɪnkəʊt/", meaning_vi: "Áo mưa", example: "He wore a yellow raincoat in the storm." }
        ]
    },
    {
        id: "topic_nature_weather",
        ten: "Nature & Weather (Thiên nhiên & Thời tiết)",
        items: [
            { id: "nw1", term: "Sun", pos: "n.", ipa: "/sʌn/", meaning_vi: "Mặt trời", example: "The sun rises in the east." },
            { id: "nw2", term: "Moon", pos: "n.", ipa: "/muːn/", meaning_vi: "Mặt trăng", example: "There is a full moon tonight." },
            { id: "nw3", term: "Star", pos: "n.", ipa: "/stɑːr/", meaning_vi: "Ngôi sao", example: "I can see many stars in the sky." },
            { id: "nw4", term: "Sky", pos: "n.", ipa: "/skaɪ/", meaning_vi: "Bầu trời", example: "The sky is clear and blue today." },
            { id: "nw5", term: "Cloud", pos: "n.", ipa: "/klaʊd/", meaning_vi: "Đám mây", example: "Dark clouds are gathering in the sky." },
            { id: "nw6", term: "Rain", pos: "n., v.", ipa: "/reɪn/", meaning_vi: "Cơn mưa, đổ mưa", example: "We stayed inside because of the rain." },
            { id: "nw7", term: "Snow", pos: "n.", ipa: "/snəʊ/", meaning_vi: "Tuyết", example: "The children are playing in the snow." },
            { id: "nw8", term: "Wind", pos: "n.", ipa: "/wɪnd/", meaning_vi: "Gió", example: "The wind is blowing very hard." },
            { id: "nw9", term: "Storm", pos: "n.", ipa: "/stɔːrm/", meaning_vi: "Cơn bão", example: "The storm destroyed many houses." },
            { id: "nw10", term: "Lightning", pos: "n.", ipa: "/ˈlaɪtnɪŋ/", meaning_vi: "Sét", example: "The tree was struck by lightning." },
            { id: "nw11", term: "Thunder", pos: "n.", ipa: "/ˈθʌndər/", meaning_vi: "Sấm", example: "The thunder woke me up last night." },
            { id: "nw12", term: "Fog", pos: "n.", ipa: "/fɒɡ/", meaning_vi: "Sương mù", example: "The fog was so thick I couldn't drive." },
            { id: "nw13", term: "Ice", pos: "n.", ipa: "/aɪs/", meaning_vi: "Băng, đá", example: "Be careful, there is ice on the road." },
            { id: "nw14", term: "Fire", pos: "n.", ipa: "/ˈfaɪər/", meaning_vi: "Lửa", example: "We sat around the fire to stay warm." },
            { id: "nw15", term: "Water", pos: "n.", ipa: "/ˈwɔːtər/", meaning_vi: "Nước", example: "Plants need water to survive." },
            { id: "nw16", term: "Earth", pos: "n.", ipa: "/ɜːrθ/", meaning_vi: "Trái đất, đất", example: "The Earth goes around the sun." },
            { id: "nw17", term: "Tree", pos: "n.", ipa: "/triː/", meaning_vi: "Cái cây", example: "They planted an apple tree in the garden." },
            { id: "nw18", term: "Flower", pos: "n.", ipa: "/ˈflaʊər/", meaning_vi: "Bông hoa", example: "She received a beautiful bouquet of flowers." },
            { id: "nw19", term: "Grass", pos: "n.", ipa: "/ɡræs/", meaning_vi: "Cỏ", example: "Please keep off the grass." },
            { id: "nw20", term: "Leaf", pos: "n.", ipa: "/liːf/", meaning_vi: "Chiếc lá", example: "The leaves fall from the trees in autumn." },
            { id: "nw21", term: "Forest", pos: "n.", ipa: "/ˈfɒrɪst/", meaning_vi: "Khu rừng", example: "Wild animals live in the forest." },
            { id: "nw22", term: "Mountain", pos: "n.", ipa: "/ˈmaʊntn/", meaning_vi: "Ngọn núi", example: "They climbed the highest mountain." },
            { id: "nw23", term: "Hill", pos: "n.", ipa: "/hɪl/", meaning_vi: "Ngọn đồi", example: "We walked up the hill to see the view." },
            { id: "nw24", term: "Valley", pos: "n.", ipa: "/ˈvæli/", meaning_vi: "Thung lũng", example: "There is a river flowing through the valley." },
            { id: "nw25", term: "River", pos: "n.", ipa: "/ˈrɪvər/", meaning_vi: "Dòng sông", example: "We went fishing in the river." },
            { id: "nw26", term: "Lake", pos: "n.", ipa: "/leɪk/", meaning_vi: "Hồ", example: "The lake is frozen in winter." },
            { id: "nw27", term: "Ocean", pos: "n.", ipa: "/ˈəʊʃn/", meaning_vi: "Đại dương", example: "The Pacific Ocean is the largest ocean." },
            { id: "nw28", term: "Sea", pos: "n.", ipa: "/siː/", meaning_vi: "Biển", example: "I love swimming in the sea." },
            { id: "nw29", term: "Beach", pos: "n.", ipa: "/biːtʃ/", meaning_vi: "Bãi biển", example: "We relaxed on the sandy beach." },
            { id: "nw30", term: "Sand", pos: "n.", ipa: "/sænd/", meaning_vi: "Cát", example: "The children are playing in the sand." },
            { id: "nw31", term: "Rock", pos: "n.", ipa: "/rɒk/", meaning_vi: "Tảng đá", example: "He sat on a large rock." },
            { id: "nw32", term: "Island", pos: "n.", ipa: "/ˈaɪlənd/", meaning_vi: "Hòn đảo", example: "They live on a small tropical island." },
            { id: "nw33", term: "Cave", pos: "n.", ipa: "/keɪv/", meaning_vi: "Hang động", example: "Bats sleep inside the dark cave." },
            { id: "nw34", term: "Desert", pos: "n.", ipa: "/ˈdezərt/", meaning_vi: "Sa mạc", example: "Camels can survive in the desert." },
            { id: "nw35", term: "Plant", pos: "n.", ipa: "/plænt/", meaning_vi: "Thực vật, cây trồng", example: "Don't forget to water the plants." },
            { id: "nw36", term: "Weather", pos: "n.", ipa: "/ˈweðər/", meaning_vi: "Thời tiết", example: "What is the weather like today?" },
            { id: "nw37", term: "Climate", pos: "n.", ipa: "/ˈklaɪmət/", meaning_vi: "Khí hậu", example: "This region has a dry climate." },
            { id: "nw38", term: "Hot", pos: "adj.", ipa: "/hɒt/", meaning_vi: "Nóng", example: "It is very hot outside today." },
            { id: "nw39", term: "Cold", pos: "adj.", ipa: "/kəʊld/", meaning_vi: "Lạnh", example: "Wear a jacket, it's cold." },
            { id: "nw40", term: "Warm", pos: "adj.", ipa: "/wɔːrm/", meaning_vi: "Ấm áp", example: "The weather is warm and sunny." }
        ]
    },
    {
        id: "topic_transportation",
        ten: "Transportation (Giao thông & Phương tiện)",
        items: [
            { id: "tr1", term: "Car", pos: "n.", ipa: "/kɑːr/", meaning_vi: "Ô tô", example: "He drives his car to work every day." },
            { id: "tr2", term: "Bus", pos: "n.", ipa: "/bʌs/", meaning_vi: "Xe buýt", example: "I take the bus to school." },
            { id: "tr3", term: "Train", pos: "n.", ipa: "/treɪn/", meaning_vi: "Tàu hỏa", example: "The train departs at 7 AM." },
            { id: "tr4", term: "Bicycle", pos: "n.", ipa: "/ˈbaɪsɪkl/", meaning_vi: "Xe đạp", example: "He rides his bicycle in the park." },
            { id: "tr5", term: "Motorcycle", pos: "n.", ipa: "/ˈməʊtərsaɪkl/", meaning_vi: "Xe máy", example: "You must wear a helmet on a motorcycle." },
            { id: "tr6", term: "Airplane", pos: "n.", ipa: "/ˈerpleɪn/", meaning_vi: "Máy bay", example: "The airplane landed safely." },
            { id: "tr7", term: "Helicopter", pos: "n.", ipa: "/ˈhelɪkɒptər/", meaning_vi: "Trực thăng", example: "The president arrived in a helicopter." },
            { id: "tr8", term: "Boat", pos: "n.", ipa: "/bəʊt/", meaning_vi: "Con thuyền nhỏ", example: "We rented a boat to go fishing." },
            { id: "tr9", term: "Ship", pos: "n.", ipa: "/ʃɪp/", meaning_vi: "Tàu thủy lớn", example: "Goods are transported by cargo ships." },
            { id: "tr10", term: "Subway", pos: "n.", ipa: "/ˈsʌbweɪ/", meaning_vi: "Tàu điện ngầm", example: "The subway is the fastest way to travel in the city." },
            { id: "tr11", term: "Taxi", pos: "n.", ipa: "/ˈtæksi/", meaning_vi: "Xe taxi", example: "We took a taxi to the airport." },
            { id: "tr12", term: "Truck", pos: "n.", ipa: "/trʌk/", meaning_vi: "Xe tải", example: "A large truck is blocking the road." },
            { id: "tr13", term: "Van", pos: "n.", ipa: "/væn/", meaning_vi: "Xe tải nhỏ, xe khách", example: "They moved their furniture in a van." },
            { id: "tr14", term: "Scooter", pos: "n.", ipa: "/ˈskuːtər/", meaning_vi: "Xe tay ga, xe trượt", example: "Kids love riding their scooters." },
            { id: "tr15", term: "Ferry", pos: "n.", ipa: "/ˈferi/", meaning_vi: "Phà", example: "We took the ferry across the river." },
            { id: "tr16", term: "Tram", pos: "n.", ipa: "/træm/", meaning_vi: "Xe điện", example: "The tram runs through the city center." },
            { id: "tr17", term: "Ambulance", pos: "n.", ipa: "/ˈæmbjələns/", meaning_vi: "Xe cứu thương", example: "The ambulance rushed to the hospital." },
            { id: "tr18", term: "Police car", pos: "n.", ipa: "/pəˈliːs kɑːr/", meaning_vi: "Xe cảnh sát", example: "A police car passed by with its siren on." },
            { id: "tr19", term: "Fire engine", pos: "n.", ipa: "/ˈfaɪər endʒɪn/", meaning_vi: "Xe cứu hỏa", example: "The fire engine arrived quickly." },
            { id: "tr20", term: "Tractor", pos: "n.", ipa: "/ˈtræktər/", meaning_vi: "Máy kéo", example: "The farmer uses a tractor in the field." },
            { id: "tr21", term: "Wheel", pos: "n.", ipa: "/wiːl/", meaning_vi: "Bánh xe", example: "One of the car's wheels is flat." },
            { id: "tr22", term: "Engine", pos: "n.", ipa: "/ˈendʒɪn/", meaning_vi: "Động cơ", example: "He started the car engine." },
            { id: "tr23", term: "Ticket", pos: "n.", ipa: "/ˈtɪkɪt/", meaning_vi: "Vé", example: "Show your ticket to the conductor." },
            { id: "tr24", term: "Station", pos: "n.", ipa: "/ˈsteɪʃn/", meaning_vi: "Nhà ga, trạm", example: "I will meet you at the train station." },
            { id: "tr25", term: "Airport", pos: "n.", ipa: "/ˈerpɔːrt/", meaning_vi: "Sân bay", example: "We arrived at the airport two hours early." },
            { id: "tr26", term: "Port", pos: "n.", ipa: "/pɔːrt/", meaning_vi: "Cảng", example: "The ship docked at the port." },
            { id: "tr27", term: "Road", pos: "n.", ipa: "/rəʊd/", meaning_vi: "Con đường", example: "Drive carefully on this bumpy road." },
            { id: "tr28", term: "Street", pos: "n.", ipa: "/striːt/", meaning_vi: "Đường phố", example: "Our shop is on the main street." },
            { id: "tr29", term: "Highway", pos: "n.", ipa: "/ˈhaɪweɪ/", meaning_vi: "Đường cao tốc", example: "Speed limits are higher on the highway." },
            { id: "tr30", term: "Bridge", pos: "n.", ipa: "/brɪdʒ/", meaning_vi: "Cây cầu", example: "The car drove over the bridge." },
            { id: "tr31", term: "Traffic", pos: "n.", ipa: "/ˈtræfɪk/", meaning_vi: "Giao thông", example: "There is heavy traffic in the morning." },
            { id: "tr32", term: "Passenger", pos: "n.", ipa: "/ˈpæsɪndʒər/", meaning_vi: "Hành khách", example: "The bus can hold 50 passengers." },
            { id: "tr33", term: "Driver", pos: "n.", ipa: "/ˈdraɪvər/", meaning_vi: "Tài xế", example: "The driver stopped at the red light." },
            { id: "tr34", term: "Pilot", pos: "n.", ipa: "/ˈpaɪlət/", meaning_vi: "Phi công", example: "The pilot announced our arrival." },
            { id: "tr35", term: "Flight", pos: "n.", ipa: "/flaɪt/", meaning_vi: "Chuyến bay", example: "How was your flight?" },
            { id: "tr36", term: "Ride", pos: "v.", ipa: "/raɪd/", meaning_vi: "Cưỡi, đi (xe đạp, xe máy)", example: "I learned to ride a bike when I was 5." },
            { id: "tr37", term: "Drive", pos: "v.", ipa: "/draɪv/", meaning_vi: "Lái xe (ô tô)", example: "Can you drive a manual car?" },
            { id: "tr38", term: "Sail", pos: "v.", ipa: "/seɪl/", meaning_vi: "Chèo thuyền, giăng buồm", example: "We are going to sail across the bay." },
            { id: "tr39", term: "Fly", pos: "v.", ipa: "/flaɪ/", meaning_vi: "Bay", example: "I will fly to London tomorrow." },
            { id: "tr40", term: "Walk", pos: "v.", ipa: "/wɔːk/", meaning_vi: "Đi bộ", example: "It is close enough to walk there." }
        ]
    },
    {
        id: "topic_places",
        ten: "City & Places (Thành phố & Địa điểm)",
        items: [
            { id: "cp1", term: "City", pos: "n.", ipa: "/ˈsɪti/", meaning_vi: "Thành phố", example: "New York is a very busy city." },
            { id: "cp2", term: "Town", pos: "n.", ipa: "/taʊn/", meaning_vi: "Thị trấn", example: "He grew up in a small town." },
            { id: "cp3", term: "Village", pos: "n.", ipa: "/ˈvɪlɪdʒ/", meaning_vi: "Ngôi làng", example: "There is a peaceful village near the mountain." },
            { id: "cp4", term: "Capital", pos: "n.", ipa: "/ˈkæpɪtl/", meaning_vi: "Thủ đô", example: "Paris is the capital of France." },
            { id: "cp5", term: "Building", pos: "n.", ipa: "/ˈbɪldɪŋ/", meaning_vi: "Tòa nhà", example: "That is the tallest building in the city." },
            { id: "cp6", term: "House", pos: "n.", ipa: "/haʊs/", meaning_vi: "Ngôi nhà", example: "They bought a new house." },
            { id: "cp7", term: "Apartment", pos: "n.", ipa: "/əˈpɑːrtmənt/", meaning_vi: "Căn hộ", example: "She lives in a small apartment." },
            { id: "cp8", term: "School", pos: "n.", ipa: "/skuːl/", meaning_vi: "Trường học", example: "The children walk to school together." },
            { id: "cp9", term: "University", pos: "n.", ipa: "/ˌjuːnɪˈvɜːrsəti/", meaning_vi: "Trường đại học", example: "He studies law at the university." },
            { id: "cp10", term: "Hospital", pos: "n.", ipa: "/ˈhɒspɪtl/", meaning_vi: "Bệnh viện", example: "The ambulance rushed to the hospital." },
            { id: "cp11", term: "Clinic", pos: "n.", ipa: "/ˈklɪnɪk/", meaning_vi: "Phòng khám", example: "I have a dental appointment at the clinic." },
            { id: "cp12", term: "Bank", pos: "n.", ipa: "/bæŋk/", meaning_vi: "Ngân hàng", example: "I need to withdraw money from the bank." },
            { id: "cp13", term: "Post office", pos: "n.", ipa: "/ˈpəʊst ɒfɪs/", meaning_vi: "Bưu điện", example: "I will mail this package at the post office." },
            { id: "cp14", term: "Police station", pos: "n.", ipa: "/pəˈliːs steɪʃn/", meaning_vi: "Đồn cảnh sát", example: "Report the stolen car to the police station." },
            { id: "cp15", term: "Library", pos: "n.", ipa: "/ˈlaɪbreri/", meaning_vi: "Thư viện", example: "Students study quietly in the library." },
            { id: "cp16", term: "Museum", pos: "n.", ipa: "/mjuˈziːəm/", meaning_vi: "Bảo tàng", example: "The museum has ancient dinosaur bones." },
            { id: "cp17", term: "Park", pos: "n.", ipa: "/pɑːrk/", meaning_vi: "Công viên", example: "We walked our dog in the park." },
            { id: "cp18", term: "Zoo", pos: "n.", ipa: "/zuː/", meaning_vi: "Sở thú", example: "The kids love seeing lions at the zoo." },
            { id: "cp19", term: "Restaurant", pos: "n.", ipa: "/ˈrestrɒnt/", meaning_vi: "Nhà hàng", example: "We had dinner at a fancy restaurant." },
            { id: "cp20", term: "Cafe", pos: "n.", ipa: "/kæˈfeɪ/", meaning_vi: "Quán cà phê", example: "Let's meet at the cafe for a drink." },
            { id: "cp21", term: "Bar", pos: "n.", ipa: "/bɑːr/", meaning_vi: "Quán rượu", example: "He went to a bar to watch the football game." },
            { id: "cp22", term: "Hotel", pos: "n.", ipa: "/həʊˈtel/", meaning_vi: "Khách sạn", example: "We stayed at a five-star hotel." },
            { id: "cp23", term: "Supermarket", pos: "n.", ipa: "/ˈsuːpərmɑːrkɪt/", meaning_vi: "Siêu thị", example: "I buy groceries at the supermarket." },
            { id: "cp24", term: "Mall", pos: "n.", ipa: "/mɔːl/", meaning_vi: "Trung tâm thương mại", example: "Teenagers love hanging out at the mall." },
            { id: "cp25", term: "Shop", pos: "n.", ipa: "/ʃɒp/", meaning_vi: "Cửa hàng", example: "The clothes shop opens at 9 AM." },
            { id: "cp26", term: "Bakery", pos: "n.", ipa: "/ˈbeɪkəri/", meaning_vi: "Tiệm bánh", example: "The bakery smells like fresh bread." },
            { id: "cp27", term: "Pharmacy", pos: "n.", ipa: "/ˈfɑːrməsi/", meaning_vi: "Tiệm thuốc", example: "Get your medicine from the pharmacy." },
            { id: "cp28", term: "Cinema", pos: "n.", ipa: "/ˈsɪnəmə/", meaning_vi: "Rạp chiếu phim", example: "We watched an action movie at the cinema." },
            { id: "cp29", term: "Theater", pos: "n.", ipa: "/ˈθiːətər/", meaning_vi: "Nhà hát", example: "They watched a play at the theater." },
            { id: "cp30", term: "Gym", pos: "n.", ipa: "/dʒɪm/", meaning_vi: "Phòng tập thể hình", example: "He lifts weights at the gym." },
            { id: "cp31", term: "Stadium", pos: "n.", ipa: "/ˈsteɪdiəm/", meaning_vi: "Sân vận động", example: "Thousands of fans filled the stadium." },
            { id: "cp32", term: "Pool", pos: "n.", ipa: "/puːl/", meaning_vi: "Hồ bơi", example: "We swam in the hotel pool." },
            { id: "cp33", term: "Church", pos: "n.", ipa: "/tʃɜːrtʃ/", meaning_vi: "Nhà thờ", example: "They go to church every Sunday." },
            { id: "cp34", term: "Temple", pos: "n.", ipa: "/ˈtempl/", meaning_vi: "Ngôi đền", example: "We visited an ancient Buddhist temple." },
            { id: "cp35", term: "Airport", pos: "n.", ipa: "/ˈerpɔːrt/", meaning_vi: "Sân bay", example: "Our flight departs from the airport." },
            { id: "cp36", term: "Station", pos: "n.", ipa: "/ˈsteɪʃn/", meaning_vi: "Nhà ga", example: "The train station is crowded." },
            { id: "cp37", term: "Bus stop", pos: "n.", ipa: "/ˈbʌs stɒp/", meaning_vi: "Trạm xe buýt", example: "Wait for the bus at the bus stop." },
            { id: "cp38", term: "Square", pos: "n.", ipa: "/skwer/", meaning_vi: "Quảng trường", example: "People gathered in the city square." },
            { id: "cp39", term: "Market", pos: "n.", ipa: "/ˈmɑːrkɪt/", meaning_vi: "Chợ", example: "She buys fresh fruit at the local market." },
            { id: "cp40", term: "Factory", pos: "n.", ipa: "/ˈfæktəri/", meaning_vi: "Nhà máy", example: "He works in a car factory." }
        ]
    },
    {
        id: "topic_sports",
        ten: "Sports & Hobbies (Thể thao & Sở thích)",
        items: [
            { id: "sh1", term: "Sport", pos: "n.", ipa: "/spɔːrt/", meaning_vi: "Thể thao", example: "Swimming is my favorite sport." },
            { id: "sh2", term: "Football", pos: "n.", ipa: "/ˈfʊtbɔːl/", meaning_vi: "Bóng đá", example: "The boys are playing football outside." },
            { id: "sh3", term: "Basketball", pos: "n.", ipa: "/ˈbæskɪtbɔːl/", meaning_vi: "Bóng rổ", example: "He is very tall and plays basketball." },
            { id: "sh4", term: "Baseball", pos: "n.", ipa: "/ˈbeɪsbɔːl/", meaning_vi: "Bóng chày", example: "He hit the baseball with a bat." },
            { id: "sh5", term: "Tennis", pos: "n.", ipa: "/ˈtenɪs/", meaning_vi: "Quần vợt", example: "She plays tennis every weekend." },
            { id: "sh6", term: "Volleyball", pos: "n.", ipa: "/ˈvɒlibɔːl/", meaning_vi: "Bóng chuyền", example: "We played beach volleyball." },
            { id: "sh7", term: "Golf", pos: "n.", ipa: "/ɡɒlf/", meaning_vi: "Môn đánh gôn", example: "Businessmen often play golf together." },
            { id: "sh8", term: "Rugby", pos: "n.", ipa: "/ˈrʌɡbi/", meaning_vi: "Bóng bầu dục", example: "Rugby is a very physical game." },
            { id: "sh9", term: "Boxing", pos: "n.", ipa: "/ˈbɒksɪŋ/", meaning_vi: "Quyền anh", example: "He wears heavy gloves for boxing." },
            { id: "sh10", term: "Wrestling", pos: "n.", ipa: "/ˈreslɪŋ/", meaning_vi: "Môn đấu vật", example: "Wrestling requires strength and skill." },
            { id: "sh11", term: "Swimming", pos: "n.", ipa: "/ˈswɪmɪŋ/", meaning_vi: "Bơi lội", example: "Swimming is good for your health." },
            { id: "sh12", term: "Running", pos: "n.", ipa: "/ˈrʌnɪŋ/", meaning_vi: "Chạy bộ", example: "She goes running in the morning." },
            { id: "sh13", term: "Cycling", pos: "n.", ipa: "/ˈsaɪklɪŋ/", meaning_vi: "Đạp xe", example: "Cycling is an eco-friendly transport." },
            { id: "sh14", term: "Skiing", pos: "n.", ipa: "/ˈskiːɪŋ/", meaning_vi: "Trượt tuyết", example: "We go skiing in the mountains every winter." },
            { id: "sh15", term: "Skating", pos: "n.", ipa: "/ˈskeɪtɪŋ/", meaning_vi: "Trượt băng", example: "Ice skating is fun but difficult." },
            { id: "sh16", term: "Surfing", pos: "n.", ipa: "/ˈsɜːrfɪŋ/", meaning_vi: "Lướt sóng", example: "Hawaii is famous for surfing." },
            { id: "sh17", term: "Diving", pos: "n.", ipa: "/ˈdaɪvɪŋ/", meaning_vi: "Lặn", example: "He enjoys deep sea diving." },
            { id: "sh18", term: "Team", pos: "n.", ipa: "/tiːm/", meaning_vi: "Đội tuyển", example: "Our team won the championship." },
            { id: "sh19", term: "Player", pos: "n.", ipa: "/ˈpleɪər/", meaning_vi: "Cầu thủ, người chơi", example: "He is the best player on the team." },
            { id: "sh20", term: "Coach", pos: "n.", ipa: "/kəʊtʃ/", meaning_vi: "Huấn luyện viên", example: "The coach trained them hard." },
            { id: "sh21", term: "Referee", pos: "n.", ipa: "/ˌrefəˈriː/", meaning_vi: "Trọng tài", example: "The referee blew the whistle." },
            { id: "sh22", term: "Ball", pos: "n.", ipa: "/bɔːl/", meaning_vi: "Quả bóng", example: "Kick the ball into the net." },
            { id: "sh23", term: "Bat", pos: "n.", ipa: "/bæt/", meaning_vi: "Cái gậy (bóng chày)", example: "He swung the bat and missed." },
            { id: "sh24", term: "Racket", pos: "n.", ipa: "/ˈrækɪt/", meaning_vi: "Cái vợt", example: "You need a racket to play tennis." },
            { id: "sh25", term: "Net", pos: "n.", ipa: "/net/", meaning_vi: "Lưới", example: "The ball went over the net." },
            { id: "sh26", term: "Goal", pos: "n.", ipa: "/ɡəʊl/", meaning_vi: "Bàn thắng, khung thành", example: "He scored the winning goal." },
            { id: "sh27", term: "Score", pos: "n., v.", ipa: "/skɔːr/", meaning_vi: "Điểm số, ghi bàn", example: "The final score was 2-1." },
            { id: "sh28", term: "Win", pos: "v.", ipa: "/wɪn/", meaning_vi: "Chiến thắng", example: "I hope our team will win." },
            { id: "sh29", term: "Lose", pos: "v.", ipa: "/luːz/", meaning_vi: "Thua cuộc", example: "Nobody likes to lose a game." },
            { id: "sh30", term: "Match", pos: "n.", ipa: "/mætʃ/", meaning_vi: "Trận đấu", example: "The football match starts at 8 PM." },
            { id: "sh31", term: "Hobby", pos: "n.", ipa: "/ˈhɒbi/", meaning_vi: "Sở thích", example: "My favorite hobby is reading." },
            { id: "sh32", term: "Reading", pos: "n.", ipa: "/ˈriːdɪŋ/", meaning_vi: "Việc đọc sách", example: "Reading helps you learn new things." },
            { id: "sh33", term: "Writing", pos: "n.", ipa: "/ˈraɪtɪŋ/", meaning_vi: "Việc viết lách", example: "She enjoys writing poetry." },
            { id: "sh34", term: "Singing", pos: "n.", ipa: "/ˈsɪŋɪŋ/", meaning_vi: "Ca hát", example: "He is taking singing lessons." },
            { id: "sh35", term: "Dancing", pos: "n.", ipa: "/ˈdænsɪŋ/", meaning_vi: "Nhảy múa", example: "They spent the night dancing." },
            { id: "sh36", term: "Painting", pos: "n.", ipa: "/ˈpeɪntɪŋ/", meaning_vi: "Hội họa, sơn", example: "She bought colors for her painting." },
            { id: "sh37", term: "Drawing", pos: "n.", ipa: "/ˈdrɔːɪŋ/", meaning_vi: "Vẽ tranh", example: "His drawing of the house is beautiful." },
            { id: "sh38", term: "Photography", pos: "n.", ipa: "/fəˈtɒɡrəfi/", meaning_vi: "Nhiếp ảnh", example: "He loves nature photography." },
            { id: "sh39", term: "Cooking", pos: "n.", ipa: "/ˈkʊkɪŋ/", meaning_vi: "Nấu ăn", example: "Cooking is a relaxing hobby for her." },
            { id: "sh40", term: "Gardening", pos: "n.", ipa: "/ˈɡɑːrdnɪŋ/", meaning_vi: "Làm vườn", example: "He spends his weekends gardening." }
        ]
    },
    {
        id: "topic_education",
        ten: "School & Education (Giáo dục)",
        items: [
            { id: "se1", term: "School", pos: "n.", ipa: "/skuːl/", meaning_vi: "Trường học", example: "The kids are at school." },
            { id: "se2", term: "Class", pos: "n.", ipa: "/klæs/", meaning_vi: "Lớp học", example: "Pay attention in class." },
            { id: "se3", term: "Classroom", pos: "n.", ipa: "/ˈklæsruːm/", meaning_vi: "Phòng học", example: "The classroom is very quiet." },
            { id: "se4", term: "Student", pos: "n.", ipa: "/ˈstuːdnt/", meaning_vi: "Học sinh", example: "She is a very smart student." },
            { id: "se5", term: "Teacher", pos: "n.", ipa: "/ˈtiːtʃər/", meaning_vi: "Giáo viên", example: "The teacher wrote on the board." },
            { id: "se6", term: "Principal", pos: "n.", ipa: "/ˈprɪnsəpl/", meaning_vi: "Hiệu trưởng", example: "The principal gave a speech." },
            { id: "se7", term: "Lesson", pos: "n.", ipa: "/ˈlesn/", meaning_vi: "Bài học", example: "Today's lesson is about history." },
            { id: "se8", term: "Subject", pos: "n.", ipa: "/ˈsʌbdʒɪkt/", meaning_vi: "Môn học", example: "Math is my favorite subject." },
            { id: "se9", term: "Math", pos: "n.", ipa: "/mæθ/", meaning_vi: "Toán học", example: "Math is very difficult for me." },
            { id: "se10", term: "Science", pos: "n.", ipa: "/ˈsaɪəns/", meaning_vi: "Khoa học", example: "We did an experiment in science class." },
            { id: "se11", term: "History", pos: "n.", ipa: "/ˈhɪstri/", meaning_vi: "Lịch sử", example: "I love learning about history." },
            { id: "se12", term: "Geography", pos: "n.", ipa: "/dʒiˈɒɡrəfi/", meaning_vi: "Địa lý", example: "Geography teaches us about the world." },
            { id: "se13", term: "Art", pos: "n.", ipa: "/ɑːrt/", meaning_vi: "Mỹ thuật", example: "She drew a picture in art class." },
            { id: "se14", term: "Music", pos: "n.", ipa: "/ˈmjuːzɪk/", meaning_vi: "Âm nhạc", example: "They learned to sing in music class." },
            { id: "se15", term: "Language", pos: "n.", ipa: "/ˈlæŋɡwɪdʒ/", meaning_vi: "Ngôn ngữ", example: "English is a global language." },
            { id: "se16", term: "Homework", pos: "n.", ipa: "/ˈhəʊmwɜːrk/", meaning_vi: "Bài tập về nhà", example: "I have to finish my homework." },
            { id: "se17", term: "Test", pos: "n.", ipa: "/test/", meaning_vi: "Bài kiểm tra", example: "We have a math test tomorrow." },
            { id: "se18", term: "Exam", pos: "n.", ipa: "/ɪɡˈzæm/", meaning_vi: "Kỳ thi", example: "He passed the final exam." },
            { id: "se19", term: "Grade", pos: "n.", ipa: "/ɡreɪd/", meaning_vi: "Điểm số, Khối lớp", example: "She got a good grade on her test." },
            { id: "se20", term: "Book", pos: "n.", ipa: "/bʊk/", meaning_vi: "Sách", example: "Open your book to page ten." },
            { id: "se21", term: "Notebook", pos: "n.", ipa: "/ˈnəʊtbʊk/", meaning_vi: "Quyển vở", example: "Write the answers in your notebook." },
            { id: "se22", term: "Pen", pos: "n.", ipa: "/pen/", meaning_vi: "Bút máy, bút bi", example: "Can I borrow your blue pen?" },
            { id: "se23", term: "Pencil", pos: "n.", ipa: "/ˈpensl/", meaning_vi: "Bút chì", example: "Use a pencil so you can erase mistakes." },
            { id: "se24", term: "Eraser", pos: "n.", ipa: "/ɪˈreɪsər/", meaning_vi: "Cục tẩy", example: "I need an eraser to fix this drawing." },
            { id: "se25", term: "Ruler", pos: "n.", ipa: "/ˈruːlər/", meaning_vi: "Cây thước", example: "Use a ruler to draw a straight line." },
            { id: "se26", term: "Desk", pos: "n.", ipa: "/desk/", meaning_vi: "Bàn học", example: "Sit at your desk quietly." },
            { id: "se27", term: "Chair", pos: "n.", ipa: "/tʃer/", meaning_vi: "Cái ghế", example: "The student sat in his chair." },
            { id: "se28", term: "Board", pos: "n.", ipa: "/bɔːrd/", meaning_vi: "Cái bảng", example: "Look at the words on the board." },
            { id: "se29", term: "Chalk", pos: "n.", ipa: "/tʃɔːk/", meaning_vi: "Phấn", example: "The teacher uses chalk to write." },
            { id: "se30", term: "Computer", pos: "n.", ipa: "/kəmˈpjuːtər/", meaning_vi: "Máy vi tính", example: "We use the computer in IT class." },
            { id: "se31", term: "Dictionary", pos: "n.", ipa: "/ˈdɪkʃəneri/", meaning_vi: "Từ điển", example: "Look up the word in the dictionary." },
            { id: "se32", term: "Backpack", pos: "n.", ipa: "/ˈbækpæk/", meaning_vi: "Ba lô", example: "He put his books in his backpack." },
            { id: "se33", term: "Uniform", pos: "n.", ipa: "/ˈjuːnɪfɔːrm/", meaning_vi: "Đồng phục", example: "The school uniform is blue and white." },
            { id: "se34", term: "Learn", pos: "v.", ipa: "/lɜːrn/", meaning_vi: "Học hỏi", example: "Children learn very fast." },
            { id: "se35", term: "Study", pos: "v.", ipa: "/ˈstʌdi/", meaning_vi: "Học tập", example: "I need to study for my exam." },
            { id: "se36", term: "Teach", pos: "v.", ipa: "/tiːtʃ/", meaning_vi: "Dạy học", example: "She teaches English at the school." },
            { id: "se37", term: "Read", pos: "v.", ipa: "/riːd/", meaning_vi: "Đọc", example: "I read a chapter every night." },
            { id: "se38", term: "Write", pos: "v.", ipa: "/raɪt/", meaning_vi: "Viết", example: "Write your name on the paper." },
            { id: "se39", term: "Draw", pos: "v.", ipa: "/drɔː/", meaning_vi: "Vẽ", example: "Can you draw a picture of a cat?" },
            { id: "se40", term: "Spell", pos: "v.", ipa: "/spel/", meaning_vi: "Đánh vần", example: "How do you spell your name?" }
        ]
    }
];
