const group_1_decks = [
  { id: "daily_conversation", ten: "Giao tiếp hằng ngày", items: [
    {id:"daily_conversation-001", term:"What's up?", pos:"phrase", ipa:"wəts əp?", meaning_vi:"Dạo này sao?", example:"What's up?"},
    {id:"daily_conversation-002", term:"How's it going?", pos:"phrase", ipa:"haʊz ɪt goʊɪŋ?", meaning_vi:"Dạo này thế nào?", example:"How's it going?"},
    {id:"daily_conversation-003", term:"I'm good.", pos:"phrase", ipa:"əm gʊd.", meaning_vi:"Tôi ổn.", example:"I'm good, thanks."},
    {id:"daily_conversation-004", term:"Not bad.", pos:"phrase", ipa:"nɑt bæd.", meaning_vi:"Không tệ.", example:"Not bad—just busy."},
    {id:"daily_conversation-005", term:"Long time no see.", pos:"phrase", ipa:"lɔŋ taɪm noʊ si.", meaning_vi:"Lâu rồi không gặp.", example:"Long time no see!"},
    {id:"daily_conversation-006", term:"Nice to meet you.", pos:"phrase", ipa:"nis tɪ mit ju.", meaning_vi:"Rất vui được gặp bạn.", example:"Nice to meet you."},
    {id:"daily_conversation-007", term:"Good to see you.", pos:"phrase", ipa:"gʊd tɪ si ju.", meaning_vi:"Rất vui gặp bạn.", example:"Good to see you."},
    {id:"daily_conversation-008", term:"How are you?", pos:"phrase", ipa:"haʊ ər ju?", meaning_vi:"Bạn khỏe không?", example:"How are you?"},
    {id:"daily_conversation-009", term:"I'm doing great.", pos:"phrase", ipa:"əm duɪŋ greɪt.", meaning_vi:"Tôi rất ổn.", example:"I'm doing great today."},
    {id:"daily_conversation-010", term:"Thanks a lot.", pos:"phrase", ipa:"θæŋks ə lɔt.", meaning_vi:"Cảm ơn nhiều.", example:"Thanks a lot!"},
    {id:"daily_conversation-011", term:"No problem.", pos:"phrase", ipa:"noʊ ˈprɑbləm.", meaning_vi:"Không có gì.", example:"No problem."},
    {id:"daily_conversation-012", term:"You're welcome.", pos:"phrase", ipa:"jʊr ˈwɛlkəm.", meaning_vi:"Không có chi.", example:"You're welcome."},
    {id:"daily_conversation-013", term:"Excuse me.", pos:"phrase", ipa:"ɪkˈskjuz mi.", meaning_vi:"Xin lỗi (lịch sự).", example:"Excuse me, can I ask you something?"},
    {id:"daily_conversation-014", term:"Sorry about that.", pos:"phrase", ipa:"ˈsɑri əˈbaʊt ðət.", meaning_vi:"Xin lỗi vì chuyện đó.", example:"Sorry about that."},
    {id:"daily_conversation-015", term:"My bad.", pos:"phrase", ipa:"maɪ bæd.", meaning_vi:"Lỗi tôi rồi.", example:"My bad—I forgot."},
    {id:"daily_conversation-016", term:"I got it.", pos:"phrase", ipa:"aɪ gɑt ɪt.", meaning_vi:"Tôi hiểu rồi.", example:"Got it."},
    {id:"daily_conversation-017", term:"I don't get it.", pos:"phrase", ipa:"aɪ doʊnt gɪt ɪt.", meaning_vi:"Tôi không hiểu.", example:"I don't get it."},
    {id:"daily_conversation-018", term:"Could you repeat that?", pos:"phrase", ipa:"kʊd ju rɪˈpit ðət?", meaning_vi:"Bạn nói lại được không?", example:"Could you repeat that, please?"},
    {id:"daily_conversation-019", term:"Could you say that again?", pos:"phrase", ipa:"kʊd ju seɪ ðət əˈgɛn?", meaning_vi:"Nói lại được không?", example:"Could you say that again?"},
    {id:"daily_conversation-020", term:"Speak a little slower.", pos:"phrase", ipa:"spik ə ˈlɪtəl sloʊər.", meaning_vi:"Nói chậm lại một chút.", example:"Could you speak a little slower?"},
    {id:"daily_conversation-021", term:"What do you mean?", pos:"phrase", ipa:"wət du ju min?", meaning_vi:"Ý bạn là sao?", example:"What do you mean?"},
    {id:"daily_conversation-022", term:"I'm serious.", pos:"phrase", ipa:"əm ˈsɪriəs.", meaning_vi:"Tôi nói nghiêm túc đó.", example:"I'm serious."},
    {id:"daily_conversation-023", term:"Just kidding.", pos:"phrase", ipa:"ʤɪst ˈkɪdɪŋ.", meaning_vi:"Đùa thôi.", example:"Just kidding."},
    {id:"daily_conversation-024", term:"That makes sense.", pos:"phrase", ipa:"ðət meɪks sɛns.", meaning_vi:"Nghe hợp lý.", example:"That makes sense."},
    {id:"daily_conversation-025", term:"I agree.", pos:"phrase", ipa:"aɪ əˈgri.", meaning_vi:"Tôi đồng ý.", example:"I agree."},
    {id:"daily_conversation-026", term:"I disagree.", pos:"phrase", ipa:"aɪ dɪsəˈgri.", meaning_vi:"Tôi không đồng ý.", example:"I disagree."},
    {id:"daily_conversation-027", term:"Maybe.", pos:"phrase", ipa:"/meɪbi/", meaning_vi:"Có thể.", example:"Maybe."},
    {id:"daily_conversation-028", term:"It depends.", pos:"phrase", ipa:"ɪt dɪˈpɛndz.", meaning_vi:"Còn tùy.", example:"It depends."},
    {id:"daily_conversation-029", term:"Sounds good.", pos:"phrase", ipa:"saʊnz gʊd.", meaning_vi:"Nghe được đó.", example:"Sounds good."},
    {id:"daily_conversation-030", term:"Sure.", pos:"phrase", ipa:"/ʃʊɹ/", meaning_vi:"Được chứ.", example:"Sure."},
    {id:"daily_conversation-031", term:"Of course.", pos:"phrase", ipa:"əv kɔrs.", meaning_vi:"Tất nhiên.", example:"Of course."},
    {id:"daily_conversation-032", term:"Let’s go.", pos:"phrase", ipa:"let’s* goʊ.", meaning_vi:"Đi thôi.", example:"Let’s go."},
    {id:"daily_conversation-033", term:"I’m in.", pos:"phrase", ipa:"i’m* ɪn.", meaning_vi:"Tôi tham gia.", example:"I’m in."},
    {id:"daily_conversation-034", term:"I’m out.", pos:"phrase", ipa:"i’m* aʊt.", meaning_vi:"Tôi không tham gia.", example:"I’m out."},
    {id:"daily_conversation-035", term:"Give me a sec.", pos:"phrase", ipa:"gɪv mi ə sɛk.", meaning_vi:"Cho tôi chút.", example:"Give me a sec."},
    {id:"daily_conversation-036", term:"I’m on my way.", pos:"phrase", ipa:"i’m* ɔn maɪ weɪ.", meaning_vi:"Tôi đang tới.", example:"I’m on my way."},
    {id:"daily_conversation-037", term:"See you soon.", pos:"phrase", ipa:"si ju sun.", meaning_vi:"Gặp lại sớm nhé.", example:"See you soon."},
    {id:"daily_conversation-038", term:"Take care.", pos:"phrase", ipa:"teɪk kɛr.", meaning_vi:"Giữ gìn nhé.", example:"Take care."},
    {id:"daily_conversation-039", term:"Have a good one.", pos:"phrase", ipa:"hæv ə gʊd wən.", meaning_vi:"Chúc một ngày tốt lành.", example:"Have a good one!"},
    {id:"daily_conversation-040", term:"Bye for now.", pos:"phrase", ipa:"baɪ fər naʊ.", meaning_vi:"Tạm biệt nhé.", example:"Bye for now."}
  ]},
  { id: "time", ten: "Thời gian", items: [
    {id:"time-001", term:"Monday", pos:"n", ipa:"/mʌndi/", meaning_vi:"Thứ Hai", example:"I have class on Monday."},
    {id:"time-002", term:"Tuesday", pos:"n", ipa:"ˈtuzˌdeɪ", meaning_vi:"Thứ Ba", example:"Let's meet on Tuesday."},
    {id:"time-003", term:"Wednesday", pos:"n", ipa:"/wɛnzdi/", meaning_vi:"Thứ Tư", example:"Wednesday works for me."},
    {id:"time-004", term:"Thursday", pos:"n", ipa:"/θɝzdeɪ/", meaning_vi:"Thứ Năm", example:"I’m free on Thursday."},
    {id:"time-005", term:"Friday", pos:"n", ipa:"/fɹaɪdi/", meaning_vi:"Thứ Sáu", example:"It’s Friday—finally!"},
    {id:"time-006", term:"Saturday", pos:"n", ipa:"/sætɝdi/", meaning_vi:"Thứ Bảy", example:"We’ll go out on Saturday."},
    {id:"time-007", term:"Sunday", pos:"n", ipa:"/sʌndeɪ/", meaning_vi:"Chủ nhật", example:"I usually rest on Sunday."},
    {id:"time-008", term:"January", pos:"n", ipa:"/dʒænjuɛɹi/", meaning_vi:"Tháng 1", example:"My birthday is in January."},
    {id:"time-009", term:"February", pos:"n", ipa:"/fɛbjʌwɛɹi/", meaning_vi:"Tháng 2", example:"February is short."},
    {id:"time-010", term:"March", pos:"n", ipa:"/mɑɹtʃ/", meaning_vi:"Tháng 3", example:"It starts getting warmer in March."},
    {id:"time-011", term:"April", pos:"n", ipa:"/eɪpɹʌl/", meaning_vi:"Tháng 4", example:"April can be rainy."},
    {id:"time-012", term:"May", pos:"n", ipa:"/meɪ/", meaning_vi:"Tháng 5", example:"May is my favorite month."},
    {id:"time-013", term:"June", pos:"n", ipa:"/dʒun/", meaning_vi:"Tháng 6", example:"School ends in June."},
    {id:"time-014", term:"July", pos:"n", ipa:"/dʒulaɪ/", meaning_vi:"Tháng 7", example:"July is really hot."},
    {id:"time-015", term:"August", pos:"n", ipa:"/ɑɡʌst/", meaning_vi:"Tháng 8", example:"We travel in August."},
    {id:"time-016", term:"September", pos:"n", ipa:"/sɛptɛmbɝ/", meaning_vi:"Tháng 9", example:"Classes start in September."},
    {id:"time-017", term:"October", pos:"n", ipa:"/ɑktoʊbɝ/", meaning_vi:"Tháng 10", example:"October has Halloween."},
    {id:"time-018", term:"November", pos:"n", ipa:"/noʊvɛmbɝ/", meaning_vi:"Tháng 11", example:"Thanksgiving is in November."},
    {id:"time-019", term:"December", pos:"n", ipa:"/dɪsɛmbɝ/", meaning_vi:"Tháng 12", example:"December means winter."},
    {id:"time-020", term:"morning", pos:"n", ipa:"/mɔɹnɪŋ/", meaning_vi:"buổi sáng", example:"Good morning!"},
    {id:"time-021", term:"afternoon", pos:"n", ipa:"/æftɝnun/", meaning_vi:"buổi chiều", example:"We meet in the afternoon."},
    {id:"time-022", term:"evening", pos:"n", ipa:"/ivnɪŋ/", meaning_vi:"buổi tối", example:"Good evening."},
    {id:"time-023", term:"night", pos:"n", ipa:"/naɪt/", meaning_vi:"đêm", example:"I sleep well at night."},
    {id:"time-024", term:"midnight", pos:"n", ipa:"/mɪdnaɪt/", meaning_vi:"nửa đêm", example:"I was awake at midnight."},
    {id:"time-025", term:"noon", pos:"n", ipa:"/nun/", meaning_vi:"buổi trưa", example:"Let’s eat lunch at noon."},
    {id:"time-026", term:"today", pos:"adv", ipa:"/tʌdeɪ/", meaning_vi:"hôm nay", example:"Today is Monday."},
    {id:"time-027", term:"tomorrow", pos:"adv", ipa:"/tʌmɑɹoʊ/", meaning_vi:"ngày mai", example:"See you tomorrow."},
    {id:"time-028", term:"yesterday", pos:"adv", ipa:"/jɛstɝdeɪ/", meaning_vi:"hôm qua", example:"I saw him yesterday."},
    {id:"time-029", term:"week", pos:"n", ipa:"/wik/", meaning_vi:"tuần", example:"There are 7 days in a week."},
    {id:"time-030", term:"month", pos:"n", ipa:"/mʌnθ/", meaning_vi:"tháng", example:"Next month is July."},
    {id:"time-031", term:"year", pos:"n", ipa:"/jɪɹ/", meaning_vi:"năm", example:"This year is going fast."},
    {id:"time-032", term:"decade", pos:"n", ipa:"/dɛkeɪd/", meaning_vi:"thập kỷ", example:"A decade is ten years."},
    {id:"time-033", term:"century", pos:"n", ipa:"/sɛntʃɝi/", meaning_vi:"thế kỷ", example:"The 21st century."},
    {id:"time-034", term:"second", pos:"n", ipa:"/sɛkʌnd/", meaning_vi:"giây", example:"Wait one second."},
    {id:"time-035", term:"minute", pos:"n", ipa:"/mɪnʌt/", meaning_vi:"phút", example:"Give me five minutes."},
    {id:"time-036", term:"hour", pos:"n", ipa:"/aʊɝ/", meaning_vi:"giờ", example:"The test is one hour long."},
    {id:"time-037", term:"early", pos:"adj/adv", ipa:"/ɝli/", meaning_vi:"sớm", example:"I wake up early."},
    {id:"time-038", term:"late", pos:"adj/adv", ipa:"/leɪt/", meaning_vi:"trễ", example:"Don’t be late."},
    {id:"time-039", term:"always", pos:"adv", ipa:"/ɔlweɪz/", meaning_vi:"luôn luôn", example:"I always try my best."},
    {id:"time-040", term:"never", pos:"adv", ipa:"/nɛvɝ/", meaning_vi:"không bao giờ", example:"I never give up."}
  ]},
  { id: "jobs", ten: "Nghề nghiệp", items: [
    {id:"jobs-001", term:"teacher", pos:"n", ipa:"/titʃɝ/", meaning_vi:"giáo viên", example:"She works as a teacher."},
    {id:"jobs-002", term:"doctor", pos:"n", ipa:"/dɑktɝ/", meaning_vi:"bác sĩ", example:"I need to see a doctor."},
    {id:"jobs-003", term:"nurse", pos:"n", ipa:"/nɝs/", meaning_vi:"y tá", example:"The nurse was very kind."},
    {id:"jobs-004", term:"engineer", pos:"n", ipa:"/ɛndʒʌnɪɹ/", meaning_vi:"kỹ sư", example:"My brother is an engineer."},
    {id:"jobs-005", term:"software developer", pos:"n", ipa:"/ˈsɔftˌwɛr dɪˈvɛləpər/", meaning_vi:"lập trình viên", example:"He’s a software developer."},
    {id:"jobs-006", term:"designer", pos:"n", ipa:"/dɪzaɪnɝ/", meaning_vi:"nhà thiết kế", example:"She’s a graphic designer."},
    {id:"jobs-007", term:"accountant", pos:"n", ipa:"/ʌkaʊntʌnt/", meaning_vi:"kế toán", example:"My aunt is an accountant."},
    {id:"jobs-008", term:"chef", pos:"n", ipa:"/ʃɛf/", meaning_vi:"đầu bếp", example:"The chef cooked a great meal."},
    {id:"jobs-009", term:"waiter", pos:"n", ipa:"/weɪtɝ/", meaning_vi:"bồi bàn (nam)", example:"The waiter brought our food."},
    {id:"jobs-010", term:"waitress", pos:"n", ipa:"/weɪtɹʌs/", meaning_vi:"bồi bàn (nữ)", example:"The waitress was friendly."},
    {id:"jobs-011", term:"cashier", pos:"n", ipa:"/kæʃɪɹ/", meaning_vi:"thu ngân", example:"The cashier helped me."},
    {id:"jobs-012", term:"salesperson", pos:"n", ipa:"/seɪlzpɝsʌn/", meaning_vi:"nhân viên bán hàng", example:"Ask a salesperson for help."},
    {id:"jobs-013", term:"driver", pos:"n", ipa:"/dɹaɪvɝ/", meaning_vi:"tài xế", example:"He works as a driver."},
    {id:"jobs-014", term:"pilot", pos:"n", ipa:"/paɪlʌt/", meaning_vi:"phi công", example:"The pilot announced the delay."},
    {id:"jobs-015", term:"flight attendant", pos:"n", ipa:"/flaɪt əˈtɛndənt/", meaning_vi:"tiếp viên hàng không", example:"The flight attendant was helpful."},
    {id:"jobs-016", term:"police officer", pos:"n", ipa:"/pəˈlis ˈɔfəsər/", meaning_vi:"cảnh sát", example:"A police officer guided traffic."},
    {id:"jobs-017", term:"firefighter", pos:"n", ipa:"/faɪɹfaɪtɝ/", meaning_vi:"lính cứu hỏa", example:"Firefighters arrived quickly."},
    {id:"jobs-018", term:"dentist", pos:"n", ipa:"/dɛntʌst/", meaning_vi:"nha sĩ", example:"I have a dentist appointment."},
    {id:"jobs-019", term:"pharmacist", pos:"n", ipa:"/fɑɹmʌsɪst/", meaning_vi:"dược sĩ", example:"Talk to the pharmacist."},
    {id:"jobs-020", term:"lawyer", pos:"n", ipa:"/lɔjɝ/", meaning_vi:"luật sư", example:"She hired a lawyer."},
    {id:"jobs-021", term:"judge", pos:"n", ipa:"/dʒʌdʒ/", meaning_vi:"thẩm phán", example:"The judge made a decision."},
    {id:"jobs-022", term:"manager", pos:"n", ipa:"/mænʌdʒɝ/", meaning_vi:"quản lý", example:"My manager is supportive."},
    {id:"jobs-023", term:"boss", pos:"n", ipa:"/bɑs/", meaning_vi:"sếp", example:"I’ll ask my boss."},
    {id:"jobs-024", term:"barista", pos:"n", ipa:"/bɑɹistʌ/", meaning_vi:"nhân viên pha cà phê", example:"The barista made my latte."},
    {id:"jobs-025", term:"mechanic", pos:"n", ipa:"/mʌkænɪk/", meaning_vi:"thợ sửa xe", example:"The mechanic fixed my car."},
    {id:"jobs-026", term:"electrician", pos:"n", ipa:"/ɪlɛktɹɪʃʌn/", meaning_vi:"thợ điện", example:"We called an electrician."},
    {id:"jobs-027", term:"plumber", pos:"n", ipa:"/plʌmɝ/", meaning_vi:"thợ sửa ống nước", example:"A plumber can fix it."},
    {id:"jobs-028", term:"construction worker", pos:"n", ipa:"/kənˈstrʌkʃən ˈwɜrkər/", meaning_vi:"công nhân xây dựng", example:"Construction workers start early."},
    {id:"jobs-029", term:"architect", pos:"n", ipa:"/ɑɹkʌtɛkt/", meaning_vi:"kiến trúc sư", example:"The architect designed the house."},
    {id:"jobs-030", term:"scientist", pos:"n", ipa:"/saɪʌntɪst/", meaning_vi:"nhà khoa học", example:"Scientists study diseases."},
    {id:"jobs-031", term:"researcher", pos:"n", ipa:"/ɹisɝtʃɝ/", meaning_vi:"nhà nghiên cứu", example:"She is a researcher."},
    {id:"jobs-032", term:"professor", pos:"n", ipa:"/pɹʌfɛsɝ/", meaning_vi:"giáo sư", example:"The professor gave a lecture."},
    {id:"jobs-033", term:"student", pos:"n", ipa:"/studʌnt/", meaning_vi:"học sinh/sinh viên", example:"I’m a student."},
    {id:"jobs-034", term:"translator", pos:"n", ipa:"/tɹænsleɪtɝ/", meaning_vi:"phiên dịch", example:"He works as a translator."},
    {id:"jobs-035", term:"photographer", pos:"n", ipa:"/fʌtɑɡɹʌfɝ/", meaning_vi:"nhiếp ảnh gia", example:"The photographer took pictures."},
    {id:"jobs-036", term:"musician", pos:"n", ipa:"/mjuzɪʃʌn/", meaning_vi:"nhạc sĩ", example:"She’s a musician."},
    {id:"jobs-037", term:"actor", pos:"n", ipa:"/æktɝ/", meaning_vi:"diễn viên", example:"He’s an actor."},
    {id:"jobs-038", term:"athlete", pos:"n", ipa:"/æθlit/", meaning_vi:"vận động viên", example:"She’s a professional athlete."},
    {id:"jobs-039", term:"office worker", pos:"n", ipa:"/ˈɔfɪs ˈwɜrkər/", meaning_vi:"nhân viên văn phòng", example:"He’s an office worker."},
    {id:"jobs-040", term:"entrepreneur", pos:"n", ipa:"/ɑntɹʌpɹʌnɝ/", meaning_vi:"doanh nhân", example:"She’s an entrepreneur."}
  ]},
  { id: "fruits", ten: "Trái cây", items: [
    {id:"fruits-001", term:"apple", pos:"n", ipa:"/æpʌl/", meaning_vi:"táo", example:"I eat an apple every day."},
    {id:"fruits-002", term:"banana", pos:"n", ipa:"/bʌnænʌ/", meaning_vi:"chuối", example:"She likes bananas for breakfast."},
    {id:"fruits-003", term:"orange", pos:"n", ipa:"/ɔɹʌndʒ/", meaning_vi:"cam", example:"Would you like an orange?"},
    {id:"fruits-004", term:"mango", pos:"n", ipa:"/mæŋɡoʊ/", meaning_vi:"xoài", example:"This mango is very sweet."},
    {id:"fruits-005", term:"grape", pos:"n", ipa:"/ɡɹeɪp/", meaning_vi:"nho", example:"Grapes are easy to snack on."},
    {id:"fruits-006", term:"strawberry", pos:"n", ipa:"/stɹɔbɛɹi/", meaning_vi:"dâu tây", example:"These strawberries are fresh."},
    {id:"fruits-007", term:"blueberry", pos:"n", ipa:"/blubɛɹi/", meaning_vi:"việt quất", example:"I add blueberries to yogurt."},
    {id:"fruits-008", term:"raspberry", pos:"n", ipa:"/ɹæzbɛɹi/", meaning_vi:"mâm xôi đỏ", example:"Raspberries spoil quickly."},
    {id:"fruits-009", term:"watermelon", pos:"n", ipa:"/wɔtɝmɛlʌn/", meaning_vi:"dưa hấu", example:"Watermelon is perfect in summer."},
    {id:"fruits-010", term:"pineapple", pos:"n", ipa:"/paɪnæpʌl/", meaning_vi:"dứa", example:"Pineapple goes well on pizza."},
    {id:"fruits-011", term:"pear", pos:"n", ipa:"/pɛɹ/", meaning_vi:"lê", example:"This pear is ripe."},
    {id:"fruits-012", term:"peach", pos:"n", ipa:"/pitʃ/", meaning_vi:"đào", example:"Peaches smell amazing."},
    {id:"fruits-013", term:"plum", pos:"n", ipa:"/plʌm/", meaning_vi:"mận", example:"I bought some plums."},
    {id:"fruits-014", term:"cherry", pos:"n", ipa:"/tʃɛɹi/", meaning_vi:"anh đào", example:"Cherries are expensive here."},
    {id:"fruits-015", term:"kiwi", pos:"n", ipa:"/kiwi/", meaning_vi:"kiwi", example:"I peeled a kiwi."},
    {id:"fruits-016", term:"lemon", pos:"n", ipa:"/lɛmʌn/", meaning_vi:"chanh vàng", example:"Add lemon to the tea."},
    {id:"fruits-017", term:"lime", pos:"n", ipa:"/laɪm/", meaning_vi:"chanh xanh", example:"Squeeze some lime on it."},
    {id:"fruits-018", term:"coconut", pos:"n", ipa:"/koʊkʌnʌt/", meaning_vi:"dừa", example:"I drank coconut water."},
    {id:"fruits-019", term:"avocado", pos:"n", ipa:"/ævʌkɑdoʊ/", meaning_vi:"bơ", example:"Avocado toast is popular."},
    {id:"fruits-020", term:"papaya", pos:"n", ipa:"/pʌpaɪʌ/", meaning_vi:"đu đủ", example:"Papaya is good for digestion."},
    {id:"fruits-021", term:"dragon fruit", pos:"n", ipa:"/ˈdræɡən frut/", meaning_vi:"thanh long", example:"Dragon fruit looks cool."},
    {id:"fruits-022", term:"guava", pos:"n", ipa:"/ɡwɑvʌ/", meaning_vi:"ổi", example:"Guava smells strong."},
    {id:"fruits-023", term:"pomegranate", pos:"n", ipa:"/pɑmʌɡɹænʌt/", meaning_vi:"lựu", example:"Pomegranate seeds are tasty."},
    {id:"fruits-024", term:"fig", pos:"n", ipa:"/fɪɡ/", meaning_vi:"sung", example:"Figs are sweet."},
    {id:"fruits-025", term:"apricot", pos:"n", ipa:"/eɪpɹʌkɑt/", meaning_vi:"mơ", example:"Apricots are in season."},
    {id:"fruits-026", term:"blackberry", pos:"n", ipa:"/blækbɛɹi/", meaning_vi:"mâm xôi đen", example:"Blackberries stain easily."},
    {id:"fruits-027", term:"cantaloupe", pos:"n", ipa:"/kæntʌloʊp/", meaning_vi:"dưa lưới", example:"Cantaloupe is sweet."},
    {id:"fruits-028", term:"honeydew", pos:"n", ipa:"/hʌnidu/", meaning_vi:"dưa gang", example:"Honeydew is refreshing."},
    {id:"fruits-029", term:"tangerine", pos:"n", ipa:"/tændʒɝin/", meaning_vi:"quýt", example:"I bought tangerines."},
    {id:"fruits-030", term:"grapefruit", pos:"n", ipa:"/ɡɹeɪpfɹut/", meaning_vi:"bưởi chùm", example:"Grapefruit can be bitter."},
    {id:"fruits-031", term:"passion fruit", pos:"n", ipa:"/ˈpæʃən frut/", meaning_vi:"chanh dây", example:"Passion fruit tastes tart."},
    {id:"fruits-032", term:"lychee", pos:"n", ipa:"/ˈlaɪtʃi/", meaning_vi:"vải", example:"Lychee is my favorite."},
    {id:"fruits-033", term:"durian", pos:"n", ipa:"/ˈdʊriən/", meaning_vi:"sầu riêng", example:"Durian has a strong smell."},
    {id:"fruits-034", term:"jackfruit", pos:"n", ipa:"/ˈdʒækfrut/", meaning_vi:"mít", example:"Jackfruit is huge."},
    {id:"fruits-035", term:"starfruit", pos:"n", ipa:"/ˈstɑrfrut/", meaning_vi:"khế", example:"Starfruit is crunchy."},
    {id:"fruits-036", term:"cranberry", pos:"n", ipa:"/kɹænbɛɹi/", meaning_vi:"nam việt quất", example:"Cranberry juice is tart."},
    {id:"fruits-037", term:"date", pos:"n", ipa:"/deɪt/", meaning_vi:"chà là", example:"Dates are very sweet."},
    {id:"fruits-038", term:"prune", pos:"n", ipa:"/pɹun/", meaning_vi:"mận khô", example:"Prunes help digestion."},
    {id:"fruits-039", term:"raisins", pos:"n", ipa:"/ɹeɪzʌnz/", meaning_vi:"nho khô", example:"I put raisins in oatmeal."},
    {id:"fruits-040", term:"fruit salad", pos:"n", ipa:"/frut ˈsæləd/", meaning_vi:"salad trái cây", example:"We made a fruit salad."}
  ]},
  { id: "emotions", ten: "Cảm xúc", items: [
    {id:"emotions-001", term:"happy", pos:"adj", ipa:"/hæpi/", meaning_vi:"vui", example:"I feel happy today."},
    {id:"emotions-002", term:"sad", pos:"adj", ipa:"/sæd/", meaning_vi:"buồn", example:"He looks sad."},
    {id:"emotions-003", term:"angry", pos:"adj", ipa:"/æŋɡɹi/", meaning_vi:"tức giận", example:"She’s angry about the delay."},
    {id:"emotions-004", term:"excited", pos:"adj", ipa:"/ɪksaɪtʌd/", meaning_vi:"phấn khích", example:"I’m excited for the trip."},
    {id:"emotions-005", term:"nervous", pos:"adj", ipa:"/nɝvʌs/", meaning_vi:"hồi hộp", example:"I’m nervous before exams."},
    {id:"emotions-006", term:"calm", pos:"adj", ipa:"/kɑm/", meaning_vi:"bình tĩnh", example:"Stay calm."},
    {id:"emotions-007", term:"tired", pos:"adj", ipa:"/taɪɝd/", meaning_vi:"mệt", example:"I’m tired after work."},
    {id:"emotions-008", term:"sleepy", pos:"adj", ipa:"/slipi/", meaning_vi:"buồn ngủ", example:"I’m sleepy."},
    {id:"emotions-009", term:"stressed", pos:"adj", ipa:"/stɹɛst/", meaning_vi:"căng thẳng", example:"I’m stressed this week."},
    {id:"emotions-010", term:"relaxed", pos:"adj", ipa:"/ɹɪlækst/", meaning_vi:"thư giãn", example:"I feel relaxed now."},
    {id:"emotions-011", term:"scared", pos:"adj", ipa:"/skɛɹd/", meaning_vi:"sợ", example:"I’m scared of heights."},
    {id:"emotions-012", term:"afraid", pos:"adj", ipa:"/ʌfɹeɪd/", meaning_vi:"sợ (trang trọng)", example:"Don’t be afraid."},
    {id:"emotions-013", term:"surprised", pos:"adj", ipa:"/sɝpɹaɪzd/", meaning_vi:"ngạc nhiên", example:"I was surprised to see you."},
    {id:"emotions-014", term:"confused", pos:"adj", ipa:"/kʌnfjuzd/", meaning_vi:"bối rối", example:"I’m confused."},
    {id:"emotions-015", term:"bored", pos:"adj", ipa:"/bɔɹd/", meaning_vi:"chán", example:"I’m bored."},
    {id:"emotions-016", term:"curious", pos:"adj", ipa:"/kjʊɹiʌs/", meaning_vi:"tò mò", example:"I’m curious about that."},
    {id:"emotions-017", term:"proud", pos:"adj", ipa:"/pɹaʊd/", meaning_vi:"tự hào", example:"I’m proud of you."},
    {id:"emotions-018", term:"ashamed", pos:"adj", ipa:"/ʌʃeɪmd/", meaning_vi:"xấu hổ", example:"He felt ashamed."},
    {id:"emotions-019", term:"embarrassed", pos:"adj", ipa:"/ɪmbɛɹʌst/", meaning_vi:"ngại", example:"I was embarrassed."},
    {id:"emotions-020", term:"jealous", pos:"adj", ipa:"/dʒɛlʌs/", meaning_vi:"ghen tị", example:"She got jealous."},
    {id:"emotions-021", term:"grateful", pos:"adj", ipa:"/ɡɹeɪtfʌl/", meaning_vi:"biết ơn", example:"I’m grateful for your help."},
    {id:"emotions-022", term:"thankful", pos:"adj", ipa:"/θæŋkfʌl/", meaning_vi:"biết ơn", example:"I’m thankful."},
    {id:"emotions-023", term:"hopeful", pos:"adj", ipa:"/hoʊpfʌl/", meaning_vi:"hy vọng", example:"I’m hopeful."},
    {id:"emotions-024", term:"worried", pos:"adj", ipa:"/wɝid/", meaning_vi:"lo lắng", example:"I’m worried about him."},
    {id:"emotions-025", term:"anxious", pos:"adj", ipa:"/æŋkʃʌs/", meaning_vi:"lo âu", example:"I feel anxious."},
    {id:"emotions-026", term:"lonely", pos:"adj", ipa:"/loʊnli/", meaning_vi:"cô đơn", example:"He felt lonely."},
    {id:"emotions-027", term:"confident", pos:"adj", ipa:"/kɑnfʌdʌnt/", meaning_vi:"tự tin", example:"I feel confident."},
    {id:"emotions-028", term:"shy", pos:"adj", ipa:"/ʃaɪ/", meaning_vi:"nhút nhát", example:"She’s shy."},
    {id:"emotions-029", term:"brave", pos:"adj", ipa:"/bɹeɪv/", meaning_vi:"dũng cảm", example:"That was brave."},
    {id:"emotions-030", term:"frustrated", pos:"adj", ipa:"/fɹʌstɹeɪtʌd/", meaning_vi:"bực bội", example:"I’m frustrated."},
    {id:"emotions-031", term:"content", pos:"adj", ipa:"/kɑntɛnt/", meaning_vi:"hài lòng", example:"I feel content."},
    {id:"emotions-032", term:"disappointed", pos:"adj", ipa:"/dɪsʌpɔɪntɪd/", meaning_vi:"thất vọng", example:"I’m disappointed."},
    {id:"emotions-033", term:"motivated", pos:"adj", ipa:"/moʊtʌveɪtʌd/", meaning_vi:"có động lực", example:"I feel motivated today."},
    {id:"emotions-034", term:"overwhelmed", pos:"adj", ipa:"/oʊvɝwɛlmd/", meaning_vi:"quá tải", example:"I’m overwhelmed."},
    {id:"emotions-035", term:"relieved", pos:"adj", ipa:"/ɹɪlivd/", meaning_vi:"nhẹ nhõm", example:"I’m relieved."},
    {id:"emotions-036", term:"upset", pos:"adj", ipa:"/ʌpsɛt/", meaning_vi:"buồn bực", example:"I’m upset."},
    {id:"emotions-037", term:"serious", pos:"adj", ipa:"/sɪɹiʌs/", meaning_vi:"nghiêm túc", example:"He looks serious."},
    {id:"emotions-038", term:"friendly", pos:"adj", ipa:"/fɹɛndli/", meaning_vi:"thân thiện", example:"She’s friendly."},
    {id:"emotions-039", term:"irritated", pos:"adj", ipa:"/ɪɹʌteɪtʌd/", meaning_vi:"khó chịu", example:"He seems irritated."},
    {id:"emotions-040", term:"thrilled", pos:"adj", ipa:"/θɹɪld/", meaning_vi:"cực kỳ vui", example:"I’m thrilled!"}
  ]}
];
