const group_8_decks = [
  { id: "cooking", ten: "Nấu ăn & Bếp núc", items: [
    {id:"cooking-001", term:"bake", pos:"v", ipa:"/beɪk/", meaning_vi:"nướng (bánh)", example:"I love to bake cookies."},
    {id:"cooking-002", term:"boil", pos:"v", ipa:"/bɔɪl/", meaning_vi:"luộc", example:"Boil the water first."},
    {id:"cooking-003", term:"fry", pos:"v", ipa:"/fraɪ/", meaning_vi:"chiên, rán", example:"I fry eggs for breakfast."},
    {id:"cooking-004", term:"roast", pos:"v", ipa:"/roʊst/", meaning_vi:"quay, nướng (thịt)", example:"We roast a chicken on Sunday."},
    {id:"cooking-005", term:"grill", pos:"v", ipa:"/ɡrɪl/", meaning_vi:"nướng vỉ", example:"Let's grill some meat."},
    {id:"cooking-006", term:"steam", pos:"v", ipa:"/stiːm/", meaning_vi:"hấp", example:"Steamed fish is healthy."},
    {id:"cooking-007", term:"stir-fry", pos:"v", ipa:"/ˈstɜːr fraɪ/", meaning_vi:"xào", example:"I will stir-fry the vegetables."},
    {id:"cooking-008", term:"chop", pos:"v", ipa:"/tʃɑːp/", meaning_vi:"băm, chặt", example:"Chop the onions finely."},
    {id:"cooking-009", term:"slice", pos:"v", ipa:"/slaɪs/", meaning_vi:"thái lát", example:"Slice the tomato."},
    {id:"cooking-010", term:"peel", pos:"v", ipa:"/piːl/", meaning_vi:"gọt vỏ", example:"Peel the potato before boiling."},
    {id:"cooking-011", term:"pour", pos:"v", ipa:"/pɔːr/", meaning_vi:"rót, đổ", example:"Pour the milk into a glass."},
    {id:"cooking-012", term:"mix", pos:"v", ipa:"/mɪks/", meaning_vi:"trộn", example:"Mix all the ingredients."},
    {id:"cooking-013", term:"stir", pos:"v", ipa:"/stɜːr/", meaning_vi:"khuấy", example:"Stir the soup well."},
    {id:"cooking-014", term:"blend", pos:"v", ipa:"/blend/", meaning_vi:"xay", example:"Blend the fruits to make a smoothie."},
    {id:"cooking-015", term:"whisk", pos:"v", ipa:"/wɪsk/", meaning_vi:"đánh (trứng)", example:"Whisk the eggs in a bowl."},
    {id:"cooking-016", term:"recipe", pos:"n", ipa:"/ˈresəpi/", meaning_vi:"công thức nấu ăn", example:"This is my grandmother's recipe."},
    {id:"cooking-017", term:"ingredient", pos:"n", ipa:"/ɪnˈɡriːdiənt/", meaning_vi:"nguyên liệu", example:"Do we have all the ingredients?"},
    {id:"cooking-018", term:"pan", pos:"n", ipa:"/pæn/", meaning_vi:"chảo", example:"Heat the pan on the stove."},
    {id:"cooking-019", term:"pot", pos:"n", ipa:"/pɑːt/", meaning_vi:"nồi", example:"Cook the soup in a large pot."},
    {id:"cooking-020", term:"cutting board", pos:"n", ipa:"/ˈkʌtɪŋ bɔːrd/", meaning_vi:"thớt", example:"Use the cutting board to chop meat."}
  ]},
  { id: "space", ten: "Không gian & Vũ trụ", items: [
    {id:"space-001", term:"universe", pos:"n", ipa:"/ˈjuːnɪvɜːrs/", meaning_vi:"vũ trụ", example:"The universe is expanding."},
    {id:"space-002", term:"galaxy", pos:"n", ipa:"/ˈɡæləksi/", meaning_vi:"dải ngân hà", example:"We live in the Milky Way galaxy."},
    {id:"space-003", term:"solar system", pos:"n", ipa:"/ˈsoʊlər ˈsɪstəm/", meaning_vi:"hệ mặt trời", example:"There are 8 planets in our solar system."},
    {id:"space-004", term:"planet", pos:"n", ipa:"/ˈplænɪt/", meaning_vi:"hành tinh", example:"Mars is a red planet."},
    {id:"space-005", term:"star", pos:"n", ipa:"/stɑːr/", meaning_vi:"ngôi sao", example:"Look at the shining stars."},
    {id:"space-006", term:"moon", pos:"n", ipa:"/muːn/", meaning_vi:"mặt trăng", example:"The moon revolves around the Earth."},
    {id:"space-007", term:"sun", pos:"n", ipa:"/sʌn/", meaning_vi:"mặt trời", example:"The sun provides light and heat."},
    {id:"space-008", term:"earth", pos:"n", ipa:"/ɜːrθ/", meaning_vi:"trái đất", example:"Earth is our home."},
    {id:"space-009", term:"orbit", pos:"n/v", ipa:"/ˈɔːrbɪt/", meaning_vi:"quỹ đạo, quay quanh", example:"The Earth orbits the Sun."},
    {id:"space-010", term:"asteroid", pos:"n", ipa:"/ˈæstərɔɪd/", meaning_vi:"tiểu hành tinh", example:"An asteroid hit the planet long ago."},
    {id:"space-011", term:"comet", pos:"n", ipa:"/ˈkɑːmɪt/", meaning_vi:"sao chổi", example:"Halley's Comet is famous."},
    {id:"space-012", term:"meteor", pos:"n", ipa:"/ˈmiːtiər/", meaning_vi:"sao băng", example:"I saw a meteor shower last night."},
    {id:"space-013", term:"black hole", pos:"n", ipa:"/blæk hoʊl/", meaning_vi:"hố đen", example:"Nothing can escape a black hole."},
    {id:"space-014", term:"astronaut", pos:"n", ipa:"/ˈæstrənɔːt/", meaning_vi:"phi hành gia", example:"The astronaut landed on the moon."},
    {id:"space-015", term:"spaceship", pos:"n", ipa:"/ˈspeɪsʃɪp/", meaning_vi:"tàu vũ trụ", example:"The spaceship launched successfully."},
    {id:"space-016", term:"rocket", pos:"n", ipa:"/ˈrɑːkɪt/", meaning_vi:"tên lửa", example:"A rocket flies very fast."},
    {id:"space-017", term:"satellite", pos:"n", ipa:"/ˈsætəlaɪt/", meaning_vi:"vệ tinh", example:"Satellites give us internet."},
    {id:"space-018", term:"telescope", pos:"n", ipa:"/ˈtelɪskoʊp/", meaning_vi:"kính viễn vọng", example:"I look at the stars through a telescope."},
    {id:"space-019", term:"gravity", pos:"n", ipa:"/ˈɡrævəti/", meaning_vi:"trọng lực", example:"There is zero gravity in space."},
    {id:"space-020", term:"alien", pos:"n", ipa:"/ˈeɪliən/", meaning_vi:"người ngoài hành tinh", example:"Do you believe in aliens?"}
  ]},
  { id: "environment", ten: "Môi trường & Tự nhiên", items: [
    {id:"environment-001", term:"environment", pos:"n", ipa:"/ɪnˈvaɪrənmənt/", meaning_vi:"môi trường", example:"We must protect the environment."},
    {id:"environment-002", term:"nature", pos:"n", ipa:"/ˈneɪtʃər/", meaning_vi:"thiên nhiên", example:"I love spending time in nature."},
    {id:"environment-003", term:"pollution", pos:"n", ipa:"/pəˈluːʃn/", meaning_vi:"sự ô nhiễm", example:"Air pollution is a big problem."},
    {id:"environment-004", term:"climate", pos:"n", ipa:"/ˈklaɪmət/", meaning_vi:"khí hậu", example:"The climate here is tropical."},
    {id:"environment-005", term:"climate change", pos:"n", ipa:"/ˈklaɪmət tʃeɪndʒ/", meaning_vi:"biến đổi khí hậu", example:"Climate change affects everyone."},
    {id:"environment-006", term:"global warming", pos:"n", ipa:"/ˈɡloʊbl ˈwɔːrmɪŋ/", meaning_vi:"ấm lên toàn cầu", example:"Global warming melts ice caps."},
    {id:"environment-007", term:"recycle", pos:"v", ipa:"/ˌriːˈsaɪkl/", meaning_vi:"tái chế", example:"Always recycle your plastic bottles."},
    {id:"environment-008", term:"reuse", pos:"v", ipa:"/ˌriːˈjuːz/", meaning_vi:"tái sử dụng", example:"Reuse this bag instead of buying a new one."},
    {id:"environment-009", term:"reduce", pos:"v", ipa:"/rɪˈduːs/", meaning_vi:"cắt giảm", example:"We need to reduce waste."},
    {id:"environment-010", term:"waste", pos:"n/v", ipa:"/weɪst/", meaning_vi:"rác thải / lãng phí", example:"Don't waste water."},
    {id:"environment-011", term:"trash", pos:"n", ipa:"/træʃ/", meaning_vi:"rác", example:"Throw the trash in the bin."},
    {id:"environment-012", term:"garbage", pos:"n", ipa:"/ˈɡɑːrbɪdʒ/", meaning_vi:"rác", example:"The garbage truck comes on Mondays."},
    {id:"environment-013", term:"plastic", pos:"n", ipa:"/ˈplæstɪk/", meaning_vi:"nhựa", example:"Plastic bags harm the ocean."},
    {id:"environment-014", term:"eco-friendly", pos:"adj", ipa:"/iːkoʊ ˈfrendli/", meaning_vi:"thân thiện với môi trường", example:"Use eco-friendly products."},
    {id:"environment-015", term:"protect", pos:"v", ipa:"/prəˈtekt/", meaning_vi:"bảo vệ", example:"Protect the forest."},
    {id:"environment-016", term:"destroy", pos:"v", ipa:"/dɪˈstrɔɪ/", meaning_vi:"phá hủy", example:"Wildfires destroy habitats."},
    {id:"environment-017", term:"conservation", pos:"n", ipa:"/ˌkɑːnsərˈveɪʃn/", meaning_vi:"sự bảo tồn", example:"Wildlife conservation is important."},
    {id:"environment-018", term:"wildlife", pos:"n", ipa:"/ˈwaɪldlaɪf/", meaning_vi:"động vật hoang dã", example:"The park is full of wildlife."},
    {id:"environment-019", term:"emission", pos:"n", ipa:"/ɪˈmɪʃn/", meaning_vi:"khí thải", example:"Car emissions pollute the air."},
    {id:"environment-020", term:"solar energy", pos:"n", ipa:"/ˈsoʊlər ˈenərdʒi/", meaning_vi:"năng lượng mặt trời", example:"Solar energy is renewable."}
  ]},
  { id: "phrasal_verbs", ten: "Cụm động từ thiết yếu", items: [
    {id:"phrasal_verbs-001", term:"give up", pos:"v", ipa:"/ɡɪv ʌp/", meaning_vi:"từ bỏ", example:"Never give up on your dreams."},
    {id:"phrasal_verbs-002", term:"go on", pos:"v", ipa:"/ɡoʊ ɑːn/", meaning_vi:"tiếp tục", example:"Please go on reading."},
    {id:"phrasal_verbs-003", term:"carry out", pos:"v", ipa:"/ˈkæri aʊt/", meaning_vi:"tiến hành", example:"They will carry out an experiment."},
    {id:"phrasal_verbs-004", term:"set up", pos:"v", ipa:"/set ʌp/", meaning_vi:"thiết lập, thành lập", example:"He set up a new company."},
    {id:"phrasal_verbs-005", term:"pick up", pos:"v", ipa:"/pɪk ʌp/", meaning_vi:"đón (ai đó) / nhặt lên", example:"I will pick you up at 8."},
    {id:"phrasal_verbs-006", term:"find out", pos:"v", ipa:"/faɪnd aʊt/", meaning_vi:"tìm ra, phát hiện", example:"I need to find out the truth."},
    {id:"phrasal_verbs-007", term:"grow up", pos:"v", ipa:"/ɡroʊ ʌp/", meaning_vi:"lớn lên", example:"What do you want to be when you grow up?"},
    {id:"phrasal_verbs-008", term:"bring up", pos:"v", ipa:"/brɪŋ ʌp/", meaning_vi:"đề cập tới / nuôi dưỡng", example:"Don't bring up that topic again."},
    {id:"phrasal_verbs-009", term:"point out", pos:"v", ipa:"/pɔɪnt aʊt/", meaning_vi:"chỉ ra", example:"He pointed out my mistakes."},
    {id:"phrasal_verbs-010", term:"turn out", pos:"v", ipa:"/tɜːrn aʊt/", meaning_vi:"hóa ra", example:"It turned out to be a great day."},
    {id:"phrasal_verbs-011", term:"turn on", pos:"v", ipa:"/tɜːrn ɑːn/", meaning_vi:"bật", example:"Turn on the lights, please."},
    {id:"phrasal_verbs-012", term:"turn off", pos:"v", ipa:"/tɜːrn ɔːf/", meaning_vi:"tắt", example:"Turn off the TV before sleeping."},
    {id:"phrasal_verbs-013", term:"look for", pos:"v", ipa:"/lʊk fɔːr/", meaning_vi:"tìm kiếm", example:"I am looking for my keys."},
    {id:"phrasal_verbs-014", term:"look after", pos:"v", ipa:"/lʊk ˈæftər/", meaning_vi:"chăm sóc", example:"Can you look after my dog?"},
    {id:"phrasal_verbs-015", term:"look forward to", pos:"v", ipa:"/lʊk ˈfɔːrwərd tuː/", meaning_vi:"mong đợi", example:"I look forward to seeing you."},
    {id:"phrasal_verbs-016", term:"take off", pos:"v", ipa:"/teɪk ɔːf/", meaning_vi:"cất cánh / cởi ra", example:"The plane takes off at noon."},
    {id:"phrasal_verbs-017", term:"take over", pos:"v", ipa:"/teɪk ˈoʊvər/", meaning_vi:"tiếp quản", example:"She will take over the project."},
    {id:"phrasal_verbs-018", term:"break down", pos:"v", ipa:"/breɪk daʊn/", meaning_vi:"hỏng hóc", example:"My car broke down on the highway."},
    {id:"phrasal_verbs-019", term:"work out", pos:"v", ipa:"/wɜːrk aʊt/", meaning_vi:"tập thể dục / tìm ra cách", example:"I work out at the gym."},
    {id:"phrasal_verbs-020", term:"catch up", pos:"v", ipa:"/kætʃ ʌp/", meaning_vi:"bắt kịp / hỏi thăm", example:"Let's catch up over coffee."}
  ]},
  { id: "idioms", ten: "Thành ngữ thông dụng", items: [
    {id:"idioms-001", term:"piece of cake", pos:"phrase", ipa:"/piːs əv keɪk/", meaning_vi:"dễ như ăn kẹo", example:"The test was a piece of cake."},
    {id:"idioms-002", term:"break a leg", pos:"phrase", ipa:"/breɪk ə leɡ/", meaning_vi:"chúc may mắn", example:"Break a leg on your performance!"},
    {id:"idioms-003", term:"under the weather", pos:"phrase", ipa:"/ˈʌndər ðə ˈweðər/", meaning_vi:"cảm thấy không khỏe", example:"I'm feeling a bit under the weather today."},
    {id:"idioms-004", term:"bite the bullet", pos:"phrase", ipa:"/baɪt ðə ˈbʊlɪt/", meaning_vi:"cắn răng chịu đựng", example:"I have to bite the bullet and go to the dentist."},
    {id:"idioms-005", term:"hit the sack", pos:"phrase", ipa:"/hɪt ðə sæk/", meaning_vi:"đi ngủ", example:"I'm exhausted, time to hit the sack."},
    {id:"idioms-006", term:"cost an arm and a leg", pos:"phrase", ipa:"/kɔːst ən ɑːrm ənd ə leɡ/", meaning_vi:"rất đắt đỏ", example:"That sports car costs an arm and a leg."},
    {id:"idioms-007", term:"cut corners", pos:"phrase", ipa:"/kʌt ˈkɔːrnərz/", meaning_vi:"làm ẩu, đi đường tắt", example:"Don't cut corners when building a house."},
    {id:"idioms-008", term:"call it a day", pos:"phrase", ipa:"/kɔːl ɪt ə deɪ/", meaning_vi:"kết thúc công việc hôm nay", example:"We've done enough. Let's call it a day."},
    {id:"idioms-009", term:"better late than never", pos:"phrase", ipa:"/ˈbetər leɪt ðən ˈnevər/", meaning_vi:"thà muộn còn hơn không", example:"He finally arrived. Well, better late than never."},
    {id:"idioms-010", term:"blessing in disguise", pos:"phrase", ipa:"/ˈblesɪŋ ɪn dɪsˈɡaɪz/", meaning_vi:"trong cái rủi có cái may", example:"Losing that job was a blessing in disguise."},
    {id:"idioms-011", term:"beat around the bush", pos:"phrase", ipa:"/biːt əˈraʊnd ðə bʊʃ/", meaning_vi:"nói vòng vo", example:"Stop beating around the bush and tell me the truth!"},
    {id:"idioms-012", term:"hit the nail on the head", pos:"phrase", ipa:"/hɪt ðə neɪl ɑːn ðə hed/", meaning_vi:"nói trúng phóc", example:"You hit the nail on the head with that answer."},
    {id:"idioms-013", term:"let the cat out of the bag", pos:"phrase", ipa:"/let ðə kæt aʊt əv ðə bæɡ/", meaning_vi:"để lộ bí mật", example:"Who let the cat out of the bag about the surprise party?"},
    {id:"idioms-014", term:"on cloud nine", pos:"phrase", ipa:"/ɑːn klaʊd naɪn/", meaning_vi:"cực kỳ hạnh phúc", example:"She was on cloud nine after getting engaged."},
    {id:"idioms-015", term:"spill the beans", pos:"phrase", ipa:"/spɪl ðə biːnz/", meaning_vi:"tiết lộ bí mật", example:"Come on, spill the beans! What did he say?"},
    {id:"idioms-016", term:"pull someone's leg", pos:"phrase", ipa:"/pʊl ˈsʌmwʌnz leɡ/", meaning_vi:"trêu chọc ai đó", example:"Are you serious, or are you just pulling my leg?"},
    {id:"idioms-017", term:"so far so good", pos:"phrase", ipa:"/soʊ fɑːr soʊ ɡʊd/", meaning_vi:"cho đến giờ vẫn ổn", example:"How is the new job? So far, so good."},
    {id:"idioms-018", term:"out of the blue", pos:"phrase", ipa:"/aʊt əv ðə bluː/", meaning_vi:"bất thình lình", example:"He called me completely out of the blue."},
    {id:"idioms-019", term:"time flies", pos:"phrase", ipa:"/taɪm flaɪz/", meaning_vi:"thời gian trôi nhanh", example:"Time flies when you're having fun."},
    {id:"idioms-020", term:"hang in there", pos:"phrase", ipa:"/hæŋ ɪn ðer/", meaning_vi:"cố gắng lên, đừng bỏ cuộc", example:"Hang in there, things will get better."}
  ]}
];
