const group_7_decks = [
  { id: "problems_complaints", ten: "Phàn nàn & Vấn đề", items: [
    {id:"problems_complaints-001", term:"This is broken", pos:"phrase", ipa:"ðɪs ɪz ˈbroʊkən", meaning_vi:"Cái này bị hỏng", example:"This is broken."},
    {id:"problems_complaints-002", term:"It doesn’t work", pos:"phrase", ipa:"ɪt doesn’t* wərk", meaning_vi:"Nó không hoạt động", example:"It doesn’t work."},
    {id:"problems_complaints-003", term:"I have a problem", pos:"phrase", ipa:"aɪ hæv ə ˈprɑbləm", meaning_vi:"Tôi có vấn đề", example:"I have a problem."},
    {id:"problems_complaints-004", term:"Can you fix this?", pos:"phrase", ipa:"kən ju fɪks ðɪs?", meaning_vi:"Bạn sửa được không?", example:"Can you fix this?"},
    {id:"problems_complaints-005", term:"I need help", pos:"phrase", ipa:"aɪ nid hɛlp", meaning_vi:"Tôi cần giúp", example:"I need help."},
    {id:"problems_complaints-006", term:"This is too slow", pos:"phrase", ipa:"ðɪs ɪz tu sloʊ", meaning_vi:"Cái này quá chậm", example:"This is too slow."},
    {id:"problems_complaints-007", term:"This is too expensive", pos:"phrase", ipa:"ðɪs ɪz tu ɪkˈspɛnsɪv", meaning_vi:"Cái này quá đắt", example:"This is too expensive."},
    {id:"problems_complaints-008", term:"I want a refund", pos:"phrase", ipa:"aɪ wɔnt ə ˈriˌfənd", meaning_vi:"Tôi muốn hoàn tiền", example:"I want a refund."},
    {id:"problems_complaints-009", term:"I want to complain", pos:"phrase", ipa:"aɪ wɔnt tɪ kəmˈpleɪn", meaning_vi:"Tôi muốn khiếu nại", example:"I want to complain."},
    {id:"problems_complaints-010", term:"This is unacceptable", pos:"phrase", ipa:"ðɪs ɪz ˌənəkˈsɛptəbəl", meaning_vi:"Không thể chấp nhận được", example:"This is unacceptable."},
    {id:"problems_complaints-011", term:"problem", pos:"n", ipa:"/ˈpɹɑbləm/", meaning_vi:"vấn đề", example:"What’s the problem?"},
    {id:"problems_complaints-012", term:"issue", pos:"n", ipa:"/ˈɪʃu/", meaning_vi:"vấn đề/sự cố", example:"There is an issue."},
    {id:"problems_complaints-013", term:"trouble", pos:"n", ipa:"/ˈtɹʌbəl/", meaning_vi:"rắc rối", example:"I’m in trouble."},
    {id:"problems_complaints-014", term:"mistake", pos:"n", ipa:"/mɪˈsteɪk/", meaning_vi:"lỗi lầm", example:"I made a mistake."},
    {id:"problems_complaints-015", term:"error", pos:"n", ipa:"/ˈɛɹɝ/", meaning_vi:"lỗi", example:"System error."},
    {id:"problems_complaints-016", term:"fault", pos:"n", ipa:"/fɔlt/", meaning_vi:"lỗi (trách nhiệm)", example:"It’s my fault."},
    {id:"problems_complaints-017", term:"blame", pos:"v", ipa:"/bleɪm/", meaning_vi:"đổ lỗi", example:"Don’t blame me."},
    {id:"problems_complaints-018", term:"complain", pos:"v", ipa:"/kəmˈpleɪn/", meaning_vi:"phàn nàn", example:"He complains a lot."},
    {id:"problems_complaints-019", term:"argue", pos:"v", ipa:"/ˈɑɹɡju/", meaning_vi:"cãi nhau/tranh luận", example:"Stop arguing."},
    {id:"problems_complaints-020", term:"fight", pos:"v/n", ipa:"/faɪt/", meaning_vi:"đánh/cãi nhau", example:"They had a fight."},
    {id:"problems_complaints-021", term:"broken", pos:"adj", ipa:"/ˈbɹoʊkən/", meaning_vi:"bị hỏng", example:"My phone is broken."},
    {id:"problems_complaints-022", term:"damaged", pos:"adj", ipa:"/ˈdæmɪdʒd/", meaning_vi:"bị hư hại", example:"The box is damaged."},
    {id:"problems_complaints-023", term:"ruined", pos:"adj", ipa:"/ˈɹuɪnd/", meaning_vi:"bị phá hỏng", example:"My day is ruined."},
    {id:"problems_complaints-024", term:"dirty", pos:"adj", ipa:"/ˈdɝti/", meaning_vi:"dơ/bẩn", example:"This table is dirty."},
    {id:"problems_complaints-025", term:"messy", pos:"adj", ipa:"/ˈmɛsi/", meaning_vi:"bừa bộn", example:"Your room is messy."},
    {id:"problems_complaints-026", term:"noisy", pos:"adj", ipa:"/ˈnɔɪzi/", meaning_vi:"ồn ào", example:"It’s too noisy here."},
    {id:"problems_complaints-027", term:"crowded", pos:"adj", ipa:"/ˈkɹaʊdɪd/", meaning_vi:"đông đúc", example:"The bus is crowded."},
    {id:"problems_complaints-028", term:"slow", pos:"adj", ipa:"/sloʊ/", meaning_vi:"chậm", example:"The service is slow."},
    {id:"problems_complaints-029", term:"late", pos:"adj", ipa:"/leɪt/", meaning_vi:"trễ", example:"The train is late."},
    {id:"problems_complaints-030", term:"lost", pos:"adj", ipa:"/lɔst/", meaning_vi:"mất/lạc", example:"My bag is lost."},
    {id:"problems_complaints-031", term:"terrible", pos:"adj", ipa:"/ˈtɛɹəbəl/", meaning_vi:"khủng khiếp", example:"The food was terrible."},
    {id:"problems_complaints-032", term:"awful", pos:"adj", ipa:"/ˈɔfəl/", meaning_vi:"tồi tệ", example:"This weather is awful."},
    {id:"problems_complaints-033", term:"horrible", pos:"adj", ipa:"/ˈhɔɹəbəl/", meaning_vi:"kinh khủng", example:"A horrible smell."},
    {id:"problems_complaints-034", term:"annoying", pos:"adj", ipa:"/əˈnɔɪɪŋ/", meaning_vi:"phiền phức", example:"That noise is annoying."},
    {id:"problems_complaints-035", term:"rude", pos:"adj", ipa:"/ɹud/", meaning_vi:"thô lỗ", example:"The waiter was rude."},
    {id:"problems_complaints-036", term:"unfair", pos:"adj", ipa:"/ʌnˈfɛɹ/", meaning_vi:"không công bằng", example:"That’s unfair!"},
    {id:"problems_complaints-037", term:"angry", pos:"adj", ipa:"/ˈæŋɡɹi/", meaning_vi:"tức giận", example:"I’m very angry."},
    {id:"problems_complaints-038", term:"upset", pos:"adj", ipa:"/ʌpˈsɛt/", meaning_vi:"bực mình", example:"She looks upset."},
    {id:"problems_complaints-039", term:"disappointed", pos:"adj", ipa:"/ˌdɪsəˈpɔɪntɪd/", meaning_vi:"thất vọng", example:"I’m disappointed."},
    {id:"problems_complaints-040", term:"stressful", pos:"adj", ipa:"/ˈstɹɛsfəl/", meaning_vi:"căng thẳng", example:"This job is stressful."}
  ]},
  { id: "making_plans", ten: "Lên kế hoạch", items: [
    {id:"making_plans-001", term:"Are you free tonight?", pos:"phrase", ipa:"ər ju fri təˈnaɪt?", meaning_vi:"Tối nay bạn rảnh không?", example:"Are you free tonight?"},
    {id:"making_plans-002", term:"Let’s meet", pos:"phrase", ipa:"let’s* mit", meaning_vi:"Hẹn gặp nhé", example:"Let’s meet."},
    {id:"making_plans-003", term:"What time works for you?", pos:"phrase", ipa:"wət taɪm wərks fər ju?", meaning_vi:"Giờ nào hợp với bạn?", example:"What time works for you?"},
    {id:"making_plans-004", term:"See you later", pos:"phrase", ipa:"si ju ˈleɪtər", meaning_vi:"Gặp bạn sau", example:"See you later."},
    {id:"making_plans-005", term:"See you tomorrow", pos:"phrase", ipa:"si ju təˈmɑˌroʊ", meaning_vi:"Gặp ngày mai", example:"See you tomorrow."},
    {id:"making_plans-006", term:"Let’s go out", pos:"phrase", ipa:"let’s* goʊ aʊt", meaning_vi:"Đi chơi nhé", example:"Let’s go out."},
    {id:"making_plans-007", term:"Make a plan", pos:"phrase", ipa:"meɪk ə plæn", meaning_vi:"Lập kế hoạch", example:"Make a plan."},
    {id:"making_plans-008", term:"Set a time", pos:"phrase", ipa:"sɛt ə taɪm", meaning_vi:"Chọn giờ", example:"Set a time."},
    {id:"making_plans-009", term:"I’ll be there", pos:"phrase", ipa:"i’ll* bi ðɛr", meaning_vi:"Tôi sẽ đến", example:"I’ll be there."},
    {id:"making_plans-010", term:"Don’t be late", pos:"phrase", ipa:"don’t* bi leɪt", meaning_vi:"Đừng trễ", example:"Don’t be late."},
    {id:"making_plans-011", term:"plan", pos:"n", ipa:"/plæn/", meaning_vi:"kế hoạch", example:"My plan."},
    {id:"making_plans-012", term:"schedule", pos:"n", ipa:"/ˈskɛdʒʊl/", meaning_vi:"lịch", example:"Check my schedule."},
    {id:"making_plans-013", term:"appointment", pos:"n", ipa:"/əˈpɔɪntmənt/", meaning_vi:"cuộc hẹn", example:"I have an appointment."},
    {id:"making_plans-014", term:"meeting", pos:"n", ipa:"/ˈmitɪŋ/", meaning_vi:"cuộc gặp", example:"We have a meeting."},
    {id:"making_plans-015", term:"time", pos:"n", ipa:"/taɪm/", meaning_vi:"thời gian", example:"What time?"},
    {id:"making_plans-016", term:"date", pos:"n", ipa:"/deɪt/", meaning_vi:"ngày", example:"Pick a date."},
    {id:"making_plans-017", term:"place", pos:"n", ipa:"/pleɪs/", meaning_vi:"địa điểm", example:"Choose a place."},
    {id:"making_plans-018", term:"location", pos:"n", ipa:"/loʊˈkeɪʃən/", meaning_vi:"vị trí", example:"Send me the location."},
    {id:"making_plans-019", term:"invite", pos:"v", ipa:"/ɪnˈvaɪt/", meaning_vi:"mời", example:"Invite your friends."},
    {id:"making_plans-020", term:"confirm", pos:"v", ipa:"/kənˈfɝm/", meaning_vi:"xác nhận", example:"Confirm the plan."},
    {id:"making_plans-021", term:"cancel", pos:"v", ipa:"/ˈkænsəl/", meaning_vi:"hủy", example:"Cancel the plan."},
    {id:"making_plans-022", term:"change", pos:"v", ipa:"/tʃeɪndʒ/", meaning_vi:"đổi", example:"Change the time."},
    {id:"making_plans-023", term:"available", pos:"adj", ipa:"/əˈveɪləbəl/", meaning_vi:"rảnh", example:"I’m available."},
    {id:"making_plans-024", term:"busy", pos:"adj", ipa:"/ˈbɪzi/", meaning_vi:"bận", example:"I’m busy."},
    {id:"making_plans-025", term:"tomorrow", pos:"adv", ipa:"/təˈmɑɹoʊ/", meaning_vi:"ngày mai", example:"See you tomorrow."},
    {id:"making_plans-026", term:"tonight", pos:"adv", ipa:"/təˈnaɪt/", meaning_vi:"tối nay", example:"Tonight is good."},
    {id:"making_plans-027", term:"weekend", pos:"n", ipa:"/ˈwikɛnd/", meaning_vi:"cuối tuần", example:"This weekend."},
    {id:"making_plans-028", term:"next week", pos:"phrase", ipa:"nɛkst wik", meaning_vi:"tuần sau", example:"Next week works."},
    {id:"making_plans-029", term:"later", pos:"adv", ipa:"/ˈleɪtɝ/", meaning_vi:"sau", example:"Talk later."},
    {id:"making_plans-030", term:"soon", pos:"adv", ipa:"/sun/", meaning_vi:"sớm", example:"See you soon."},
    {id:"making_plans-031", term:"set up", pos:"v", ipa:"sɛt əp", meaning_vi:"sắp xếp", example:"Set up a meeting."},
    {id:"making_plans-032", term:"join", pos:"v", ipa:"/dʒɔɪn/", meaning_vi:"tham gia", example:"Join us."},
    {id:"making_plans-033", term:"come", pos:"v", ipa:"/kʌm/", meaning_vi:"đến", example:"Come with me."},
    {id:"making_plans-034", term:"go", pos:"v", ipa:"/ɡoʊ/", meaning_vi:"đi", example:"Let’s go."},
    {id:"making_plans-035", term:"remind", pos:"v", ipa:"/ɹiˈmaɪnd/", meaning_vi:"nhắc", example:"Remind me."},
    {id:"making_plans-036", term:"message", pos:"v", ipa:"/ˈmɛsɪdʒ/", meaning_vi:"nhắn", example:"Message me."},
    {id:"making_plans-037", term:"plan ahead", pos:"phrase", ipa:"plæn əˈhɛd", meaning_vi:"lên kế hoạch trước", example:"Plan ahead."},
    {id:"making_plans-038", term:"make time", pos:"phrase", ipa:"meɪk taɪm", meaning_vi:"sắp xếp thời gian", example:"Make time."},
    {id:"making_plans-039", term:"reschedule", pos:"v", ipa:"/ɹiˈskɛdʒʊl/", meaning_vi:"đổi lịch", example:"Can we reschedule?"},
    {id:"making_plans-040", term:"hang out", pos:"v", ipa:"hæŋ aʊt", meaning_vi:"đi chơi", example:"Let's hang out this weekend."}
  ]},
  { id: "asking_help", ten: "Nhờ giúp đỡ", items: [
    {id:"asking_help-001", term:"Can you help me?", pos:"phrase", ipa:"kən ju hɛlp mi?", meaning_vi:"Bạn giúp tôi được không?", example:"Can you help me?"},
    {id:"asking_help-002", term:"I need assistance.", pos:"phrase", ipa:"aɪ nid əˈsɪstəns.", meaning_vi:"Tôi cần hỗ trợ.", example:"I need assistance."},
    {id:"asking_help-003", term:"Could you give me a hand?", pos:"phrase", ipa:"kʊd ju gɪv mi ə hænd?", meaning_vi:"Bạn có thể giúp tôi một tay không?", example:"Could you give me a hand?"},
    {id:"asking_help-004", term:"Please help.", pos:"phrase", ipa:"pliz hɛlp.", meaning_vi:"Xin hãy giúp đỡ.", example:"Please help."},
    {id:"asking_help-005", term:"I’m lost.", pos:"phrase", ipa:"i’m* lɔst.", meaning_vi:"Tôi bị lạc.", example:"I’m lost."},
    {id:"asking_help-006", term:"Can you show me?", pos:"phrase", ipa:"kən ju ʃoʊ mi?", meaning_vi:"Bạn chỉ cho tôi được không?", example:"Can you show me?"},
    {id:"asking_help-007", term:"What should I do?", pos:"phrase", ipa:"wət ʃʊd aɪ du?", meaning_vi:"Tôi nên làm gì?", example:"What should I do?"},
    {id:"asking_help-008", term:"I don’t understand.", pos:"phrase", ipa:"aɪ don’t* ˌəndərˈstænd.", meaning_vi:"Tôi không hiểu.", example:"I don’t understand."},
    {id:"asking_help-009", term:"Could you repeat that?", pos:"phrase", ipa:"kʊd ju rɪˈpit ðæt?", meaning_vi:"Bạn có thể lặp lại không?", example:"Could you repeat that?"},
    {id:"asking_help-010", term:"How does this work?", pos:"phrase", ipa:"haʊ dəz ðɪs wərk?", meaning_vi:"Cái này hoạt động thế nào?", example:"How does this work?"},
    {id:"asking_help-011", term:"help", pos:"v", ipa:"/hɛlp/", meaning_vi:"giúp đỡ", example:"Please help me."},
    {id:"asking_help-012", term:"assist", pos:"v", ipa:"/əˈsɪst/", meaning_vi:"hỗ trợ", example:"Can you assist me?"},
    {id:"asking_help-013", term:"guide", pos:"v", ipa:"/ɡaɪd/", meaning_vi:"hướng dẫn", example:"Please guide me."},
    {id:"asking_help-014", term:"show", pos:"v", ipa:"/ʃoʊ/", meaning_vi:"chỉ dẫn", example:"Show me the way."},
    {id:"asking_help-015", term:"explain", pos:"v", ipa:"/ɪkˈspleɪn/", meaning_vi:"giải thích", example:"Can you explain this?"},
    {id:"asking_help-016", term:"support", pos:"n", ipa:"/səˈpɔɹt/", meaning_vi:"sự hỗ trợ", example:"I need your support."},
    {id:"asking_help-017", term:"advice", pos:"n", ipa:"/ædˈvaɪs/", meaning_vi:"lời khuyên", example:"Give me some advice."},
    {id:"asking_help-018", term:"favor", pos:"n", ipa:"/ˈfeɪvɝ/", meaning_vi:"đặc ân", example:"Do me a favor."},
    {id:"asking_help-019", term:"direction", pos:"n", ipa:"/dəˈɹɛkʃən/", meaning_vi:"phương hướng", example:"I need directions."},
    {id:"asking_help-020", term:"clarify", pos:"v", ipa:"/ˈklɛɹəˌfaɪ/", meaning_vi:"làm rõ", example:"Could you clarify that?"},
    {id:"asking_help-021", term:"translate", pos:"v", ipa:"/tɹænsˈleɪt/", meaning_vi:"dịch", example:"Can you translate this?"},
    {id:"asking_help-022", term:"fix", pos:"v", ipa:"/fɪks/", meaning_vi:"sửa", example:"Can you fix this?"},
    {id:"asking_help-023", term:"borrow", pos:"v", ipa:"/ˈbɑɹoʊ/", meaning_vi:"mượn", example:"Can I borrow your pen?"},
    {id:"asking_help-024", term:"lend", pos:"v", ipa:"/lɛnd/", meaning_vi:"cho mượn", example:"Can you lend me some money?"},
    {id:"asking_help-025", term:"find", pos:"v", ipa:"/faɪnd/", meaning_vi:"tìm", example:"Help me find my keys."},
    {id:"asking_help-026", term:"call", pos:"v", ipa:"/kɔl/", meaning_vi:"gọi", example:"Call a doctor, please."},
    {id:"asking_help-027", term:"emergency", pos:"n", ipa:"/ɪˈmɝdʒənsi/", meaning_vi:"trường hợp khẩn cấp", example:"This is an emergency."},
    {id:"asking_help-028", term:"lost", pos:"adj", ipa:"/lɔst/", meaning_vi:"lạc", example:"I am lost."},
    {id:"asking_help-029", term:"confused", pos:"adj", ipa:"/kənˈfjuzd/", meaning_vi:"bối rối", example:"I’m a bit confused."},
    {id:"asking_help-030", term:"stuck", pos:"adj", ipa:"/stʌk/", meaning_vi:"bị kẹt", example:"I’m stuck here."},
    {id:"asking_help-031", term:"heavy", pos:"adj", ipa:"/ˈhɛvi/", meaning_vi:"nặng", example:"This bag is too heavy."},
    {id:"asking_help-032", term:"broken", pos:"adj", ipa:"/ˈbɹoʊkən/", meaning_vi:"hỏng", example:"My car is broken."},
    {id:"asking_help-033", term:"hurt", pos:"adj", ipa:"/hɝt/", meaning_vi:"đau", example:"I’m hurt."},
    {id:"asking_help-034", term:"sick", pos:"adj", ipa:"/sɪk/", meaning_vi:"ốm", example:"I feel sick."},
    {id:"asking_help-035", term:"safe", pos:"adj", ipa:"/seɪf/", meaning_vi:"an toàn", example:"Is it safe here?"},
    {id:"asking_help-036", term:"danger", pos:"n", ipa:"/ˈdeɪndʒɝ/", meaning_vi:"nguy hiểm", example:"I’m in danger."},
    {id:"asking_help-037", term:"police", pos:"n", ipa:"/pəˈlis/", meaning_vi:"cảnh sát", example:"Call the police."},
    {id:"asking_help-038", term:"ambulance", pos:"n", ipa:"/ˈæmbjələns/", meaning_vi:"xe cứu thương", example:"Get an ambulance."},
    {id:"asking_help-039", term:"thank", pos:"v", ipa:"/θæŋk/", meaning_vi:"cảm ơn", example:"Thank you for your help."},
    {id:"asking_help-040", term:"rescue", pos:"v", ipa:"/ˈrɛskju/", meaning_vi:"cứu hộ", example:"The firemen rescued the cat."}
  ]},
  { id: "technology_internet", ten: "Công nghệ & Internet", items: [
    {id:"technology_internet-001", term:"Connect to Wi-Fi", pos:"phrase", ipa:"kəˈnɛkt tʊ waɪ-faɪ", meaning_vi:"Kết nối Wi-Fi", example:"Connect to Wi-Fi."},
    {id:"technology_internet-002", term:"What’s the password?", pos:"phrase", ipa:"wəts ðə ˈpæˌswərd?", meaning_vi:"Mật khẩu là gì?", example:"What’s the password?"},
    {id:"technology_internet-003", term:"My phone is dead", pos:"phrase", ipa:"maɪ foʊn ɪz dɛd", meaning_vi:"Điện thoại tôi hết pin", example:"My phone is dead."},
    {id:"technology_internet-004", term:"I need a charger", pos:"phrase", ipa:"aɪ nid ə ˈʧɑrʤər", meaning_vi:"Tôi cần cục sạc", example:"I need a charger."},
    {id:"technology_internet-005", term:"The screen is broken", pos:"phrase", ipa:"ðə skrin ɪz ˈbroʊkən", meaning_vi:"Màn hình bị vỡ", example:"The screen is broken."},
    {id:"technology_internet-006", term:"I lost my signal", pos:"phrase", ipa:"aɪ lɔst maɪ ˈsɪgnəl", meaning_vi:"Tôi mất sóng", example:"I lost my signal."},
    {id:"technology_internet-007", term:"Can you hear me?", pos:"phrase", ipa:"kən ju hir mi?", meaning_vi:"Bạn nghe tôi không?", example:"Can you hear me?"},
    {id:"technology_internet-008", term:"Send me a link", pos:"phrase", ipa:"sɛnd mi ə lɪŋk", meaning_vi:"Gửi link cho tôi", example:"Send me a link."},
    {id:"technology_internet-009", term:"I’ll text you", pos:"phrase", ipa:"i’ll* tɛkst ju", meaning_vi:"Tôi sẽ nhắn tin", example:"I’ll text you."},
    {id:"technology_internet-010", term:"Turn it off", pos:"phrase", ipa:"tɜrn ɪt ɔf", meaning_vi:"Tắt nó đi", example:"Turn it off."},
    {id:"technology_internet-011", term:"internet", pos:"n", ipa:"/ˈɪntɝnɛt/", meaning_vi:"mạng", example:"The internet is down."},
    {id:"technology_internet-012", term:"website", pos:"n", ipa:"/ˈwɛbˌsaɪt/", meaning_vi:"trang web", example:"Visit our website."},
    {id:"technology_internet-013", term:"link", pos:"n", ipa:"/lɪŋk/", meaning_vi:"đường dẫn", example:"Click the link."},
    {id:"technology_internet-014", term:"password", pos:"n", ipa:"/ˈpæswɝd/", meaning_vi:"mật khẩu", example:"Enter your password."},
    {id:"technology_internet-015", term:"app", pos:"n", ipa:"/æp/", meaning_vi:"ứng dụng", example:"Download the app."},
    {id:"technology_internet-016", term:"screen", pos:"n", ipa:"/skɹin/", meaning_vi:"màn hình", example:"Touch the screen."},
    {id:"technology_internet-017", term:"keyboard", pos:"n", ipa:"/ˈkibɔɹd/", meaning_vi:"bàn phím", example:"Type on the keyboard."},
    {id:"technology_internet-018", term:"mouse", pos:"n", ipa:"/maʊs/", meaning_vi:"chuột", example:"Move the mouse."},
    {id:"technology_internet-019", term:"laptop", pos:"n", ipa:"/ˈlæptɑp/", meaning_vi:"máy tính xách tay", example:"Open your laptop."},
    {id:"technology_internet-020", term:"phone", pos:"n", ipa:"/foʊn/", meaning_vi:"điện thoại", example:"Call me on my phone."},
    {id:"technology_internet-021", term:"tablet", pos:"n", ipa:"/ˈtæblət/", meaning_vi:"máy tính bảng", example:"I read on my tablet."},
    {id:"technology_internet-022", term:"charger", pos:"n", ipa:"/ˈtʃɑɹdʒɝ/", meaning_vi:"cục sạc", example:"Plug in the charger."},
    {id:"technology_internet-023", term:"battery", pos:"n", ipa:"/ˈbætɝi/", meaning_vi:"pin", example:"Low battery."},
    {id:"technology_internet-024", term:"signal", pos:"n", ipa:"/ˈsɪɡnəl/", meaning_vi:"sóng/tín hiệu", example:"No signal here."},
    {id:"technology_internet-025", term:"download", pos:"v", ipa:"/ˈdaʊnˌloʊd/", meaning_vi:"tải xuống", example:"Download the file."},
    {id:"technology_internet-026", term:"upload", pos:"v", ipa:"/ˈʌpˌloʊd/", meaning_vi:"tải lên", example:"Upload your photo."},
    {id:"technology_internet-027", term:"search", pos:"v", ipa:"/sɝtʃ/", meaning_vi:"tìm kiếm", example:"Search online."},
    {id:"technology_internet-028", term:"click", pos:"v", ipa:"/klɪk/", meaning_vi:"nhấp chuột", example:"Click here."},
    {id:"technology_internet-029", term:"scroll", pos:"v", ipa:"/skɹoʊl/", meaning_vi:"cuộn", example:"Scroll down."},
    {id:"technology_internet-030", term:"type", pos:"v", ipa:"/taɪp/", meaning_vi:"gõ", example:"Type fast."},
    {id:"technology_internet-031", term:"delete", pos:"v", ipa:"/dɪˈlit/", meaning_vi:"xóa", example:"Delete the text."},
    {id:"technology_internet-032", term:"save", pos:"v", ipa:"/seɪv/", meaning_vi:"lưu", example:"Save your work."},
    {id:"technology_internet-033", term:"copy", pos:"v", ipa:"/ˈkɑpi/", meaning_vi:"sao chép", example:"Copy this."},
    {id:"technology_internet-034", term:"paste", pos:"v", ipa:"/peɪst/", meaning_vi:"dán", example:"Paste it there."},
    {id:"technology_internet-035", term:"send", pos:"v", ipa:"/sɛnd/", meaning_vi:"gửi", example:"Send an email."},
    {id:"technology_internet-036", term:"receive", pos:"v", ipa:"/ɹɪˈsiv/", meaning_vi:"nhận", example:"Did you receive it?"},
    {id:"technology_internet-037", term:"online", pos:"adj", ipa:"/ˈɔnlaɪn/", meaning_vi:"trực tuyến", example:"I am online."},
    {id:"technology_internet-038", term:"offline", pos:"adj", ipa:"/ˈɔflaɪn/", meaning_vi:"ngoại tuyến", example:"The game is offline."},
    {id:"technology_internet-039", term:"social media", pos:"n", ipa:"ˈsoʊʃəl ˈmidiə", meaning_vi:"mạng xã hội", example:"I use social media."},
    {id:"technology_internet-040", term:"reboot", pos:"v", ipa:"/riˈbut/", meaning_vi:"khởi động lại", example:"Reboot the computer."}
  ]},
  { id: "fitness_gym", ten: "Thể dục & Gym", items: [
    {id:"fitness_gym-001", term:"I go to the gym.", pos:"phrase", ipa:"aɪ goʊ tʊ ðə ʤɪm.", meaning_vi:"Tôi đi phòng gym.", example:"I go to the gym."},
    {id:"fitness_gym-002", term:"Let’s work out.", pos:"phrase", ipa:"let’s* wɜrk aʊt.", meaning_vi:"Tập luyện thôi.", example:"Let’s work out."},
    {id:"fitness_gym-003", term:"I need to lose weight.", pos:"phrase", ipa:"aɪ nid tɪ luz weɪt.", meaning_vi:"Tôi cần giảm cân.", example:"I need to lose weight."},
    {id:"fitness_gym-004", term:"I want to build muscle.", pos:"phrase", ipa:"aɪ wɑnt tɪ bɪld ˈməsəl.", meaning_vi:"Tôi muốn tăng cơ.", example:"I want to build muscle."},
    {id:"fitness_gym-005", term:"I do cardio.", pos:"phrase", ipa:"aɪ du ˈkɑrdiˌoʊ.", meaning_vi:"Tôi tập cardio.", example:"I do cardio."},
    {id:"fitness_gym-006", term:"I lift weights.", pos:"phrase", ipa:"aɪ lɪft weɪts.", meaning_vi:"Tôi nâng tạ.", example:"I lift weights."},
    {id:"fitness_gym-007", term:"I’m tired.", pos:"phrase", ipa:"i’m* ˈtaɪərd.", meaning_vi:"Tôi mệt.", example:"I’m tired."},
    {id:"fitness_gym-008", term:"Take a rest.", pos:"phrase", ipa:"teɪk ə rɛst.", meaning_vi:"Nghỉ một chút.", example:"Take a rest."},
    {id:"fitness_gym-009", term:"Drink water.", pos:"phrase", ipa:"drɪŋk ˈwɔtər.", meaning_vi:"Uống nước.", example:"Drink water."},
    {id:"fitness_gym-010", term:"Good workout!", pos:"phrase", ipa:"gʊd ˈwɜrkˌaʊt!", meaning_vi:"Buổi tập tốt!", example:"Good workout!"},
    {id:"fitness_gym-011", term:"gym", pos:"n", ipa:"/dʒɪm/", meaning_vi:"phòng gym", example:"The gym is crowded."},
    {id:"fitness_gym-012", term:"workout", pos:"n", ipa:"/ˈwɝkaʊt/", meaning_vi:"buổi tập", example:"That was a good workout."},
    {id:"fitness_gym-013", term:"exercise", pos:"n", ipa:"/ˈɛksɝsaɪz/", meaning_vi:"bài tập", example:"Exercise is healthy."},
    {id:"fitness_gym-014", term:"training", pos:"n", ipa:"/ˈtɹeɪnɪŋ/", meaning_vi:"tập luyện", example:"Daily training."},
    {id:"fitness_gym-015", term:"muscle", pos:"n", ipa:"/ˈmʌsəl/", meaning_vi:"cơ bắp", example:"Build muscle."},
    {id:"fitness_gym-016", term:"weight", pos:"n", ipa:"/weɪt/", meaning_vi:"cân nặng", example:"I lost weight."},
    {id:"fitness_gym-017", term:"dumbbell", pos:"n", ipa:"/ˈdʌmbɛl/", meaning_vi:"tạ tay", example:"Lift the dumbbell."},
    {id:"fitness_gym-018", term:"barbell", pos:"n", ipa:"/ˈbɑɹbɛl/", meaning_vi:"tạ đòn", example:"Use the barbell."},
    {id:"fitness_gym-019", term:"treadmill", pos:"n", ipa:"/ˈtɹɛdmɪl/", meaning_vi:"máy chạy", example:"Run on the treadmill."},
    {id:"fitness_gym-020", term:"yoga", pos:"n", ipa:"/ˈjoʊɡə/", meaning_vi:"yoga", example:"I do yoga."},
    {id:"fitness_gym-021", term:"stretch", pos:"n", ipa:"/stɹɛtʃ/", meaning_vi:"giãn cơ", example:"Stretch your body."},
    {id:"fitness_gym-022", term:"push-up", pos:"n", ipa:"/ˈpʊʃʌp/", meaning_vi:"hít đất", example:"Do push-ups."},
    {id:"fitness_gym-023", term:"sit-up", pos:"n", ipa:"ˈsɪtˌəp", meaning_vi:"gập bụng", example:"Do sit-ups."},
    {id:"fitness_gym-024", term:"plank", pos:"n", ipa:"/plæŋk/", meaning_vi:"plank", example:"Hold a plank."},
    {id:"fitness_gym-025", term:"protein", pos:"n", ipa:"/ˈpɹoʊtin/", meaning_vi:"đạm", example:"Eat protein."},
    {id:"fitness_gym-026", term:"energy", pos:"n", ipa:"/ˈɛnɝdʒi/", meaning_vi:"năng lượng", example:"I need energy."},
    {id:"fitness_gym-027", term:"trainer", pos:"n", ipa:"/ˈtɹeɪnɝ/", meaning_vi:"huấn luyện viên", example:"The trainer helps me."},
    {id:"fitness_gym-028", term:"membership", pos:"n", ipa:"/ˈmɛmbɝʃɪp/", meaning_vi:"thẻ thành viên", example:"Gym membership."},
    {id:"fitness_gym-029", term:"locker", pos:"n", ipa:"/ˈlɑkɝ/", meaning_vi:"tủ khóa", example:"Put your bag in the locker."},
    {id:"fitness_gym-030", term:"shower", pos:"n", ipa:"/ˈʃaʊɝ/", meaning_vi:"phòng tắm", example:"Take a shower."},
    {id:"fitness_gym-031", term:"strong", pos:"adj", ipa:"/stɹɔŋ/", meaning_vi:"mạnh", example:"I feel strong."},
    {id:"fitness_gym-032", term:"healthy", pos:"adj", ipa:"/ˈhɛlθi/", meaning_vi:"khỏe mạnh", example:"Stay healthy."},
    {id:"fitness_gym-033", term:"fit", pos:"adj", ipa:"/fɪt/", meaning_vi:"thể lực tốt", example:"I want to be fit."},
    {id:"fitness_gym-034", term:"weak", pos:"adj", ipa:"/wik/", meaning_vi:"yếu", example:"I feel weak."},
    {id:"fitness_gym-035", term:"sore", pos:"adj", ipa:"/sɔɹ/", meaning_vi:"đau cơ", example:"My muscles are sore."},
    {id:"fitness_gym-036", term:"heavy", pos:"adj", ipa:"/ˈhɛvi/", meaning_vi:"nặng", example:"This weight is heavy."},
    {id:"fitness_gym-037", term:"light", pos:"adj", ipa:"/laɪt/", meaning_vi:"nhẹ", example:"Use lighter weights."},
    {id:"fitness_gym-038", term:"fast", pos:"adj", ipa:"/fæst/", meaning_vi:"nhanh", example:"Run fast."},
    {id:"fitness_gym-039", term:"slow", pos:"adj", ipa:"/sloʊ/", meaning_vi:"chậm", example:"Go slow."},
    {id:"fitness_gym-040", term:"sweat", pos:"n", ipa:"/swɛt/", meaning_vi:"mồ hôi", example:"I break a sweat easily."}
  ]}
];
