const group_9_decks = [
  { id: "it_software_pro", ten: "Công nghệ & Phần mềm", items: [
    {id:"it-001", term:"database", pos:"n", ipa:"/ˈdeɪtəbeɪs/", meaning_vi:"cơ sở dữ liệu", example:"The database stores all user information."},
    {id:"it-002", term:"algorithm", pos:"n", ipa:"/ˈælɡərɪðəm/", meaning_vi:"thuật toán", example:"The search algorithm is highly efficient."},
    {id:"it-003", term:"server", pos:"n", ipa:"/ˈsɜːrvər/", meaning_vi:"máy chủ", example:"The website is hosted on a cloud server."},
    {id:"it-004", term:"bandwidth", pos:"n", ipa:"/ˈbændwɪdθ/", meaning_vi:"băng thông", example:"We need more bandwidth for streaming."},
    {id:"it-005", term:"encryption", pos:"n", ipa:"/ɪnˈkrɪpʃn/", meaning_vi:"mã hóa", example:"End-to-end encryption protects your messages."},
    {id:"it-006", term:"hardware", pos:"n", ipa:"/ˈhɑːrdwer/", meaning_vi:"phần cứng", example:"I need to upgrade my computer's hardware."},
    {id:"it-007", term:"software", pos:"n", ipa:"/ˈsɔːftwer/", meaning_vi:"phần mềm", example:"Please install the latest software update."},
    {id:"it-008", term:"debug", pos:"v", ipa:"/ˌdiːˈbʌɡ/", meaning_vi:"sửa lỗi", example:"The developer is trying to debug the program."},
    {id:"it-009", term:"interface", pos:"n", ipa:"/ˈɪntərfeɪs/", meaning_vi:"giao diện", example:"The user interface is very intuitive."},
    {id:"it-010", term:"framework", pos:"n", ipa:"/ˈfreɪmwɜːrk/", meaning_vi:"khung ứng dụng", example:"We use the React framework for this web app."},
    {id:"it-011", term:"deployment", pos:"n", ipa:"/dɪˈplɔɪmənt/", meaning_vi:"triển khai", example:"The code deployment will happen at midnight."},
    {id:"it-012", term:"repository", pos:"n", ipa:"/rɪˈpɑːzətɔːri/", meaning_vi:"kho lưu trữ mã", example:"Push your code to the GitHub repository."},
    {id:"it-013", term:"frontend", pos:"n", ipa:"/ˈfrʌntend/", meaning_vi:"giao diện người dùng", example:"He is a frontend web developer."},
    {id:"it-014", term:"backend", pos:"n", ipa:"/ˈbækend/", meaning_vi:"hệ thống máy chủ", example:"The backend handles all the data processing."},
    {id:"it-015", term:"cache", pos:"n", ipa:"/kæʃ/", meaning_vi:"bộ nhớ đệm", example:"Clear your browser cache if the page doesn't load."},
    {id:"it-016", term:"firewall", pos:"n", ipa:"/ˈfaɪərwɔːl/", meaning_vi:"tường lửa", example:"The firewall blocks unauthorized access."},
    {id:"it-017", term:"malware", pos:"n", ipa:"/ˈmælwer/", meaning_vi:"phần mềm độc hại", example:"Use an antivirus to scan for malware."},
    {id:"it-018", term:"variable", pos:"n", ipa:"/ˈveriəbl/", meaning_vi:"biến số", example:"Assign a value to the variable."},
    {id:"it-019", term:"function", pos:"n", ipa:"/ˈfʌŋkʃn/", meaning_vi:"hàm", example:"This function calculates the total price."},
    {id:"it-020", term:"compile", pos:"v", ipa:"/kəmˈpaɪl/", meaning_vi:"biên dịch", example:"Wait for the code to compile."},
    {id:"it-021", term:"source code", pos:"n", ipa:"/sɔːrs koʊd/", meaning_vi:"mã nguồn", example:"The source code is available on GitHub."},
    {id:"it-022", term:"cloud computing", pos:"n", ipa:"", meaning_vi:"điện toán đám mây", example:"Cloud computing is cost-effective."},
    {id:"it-023", term:"bandwidth", pos:"n", ipa:"/ˈbændwɪdθ/", meaning_vi:"băng thông", example:"Low bandwidth causes lag."},
    {id:"it-024", term:"browser", pos:"n", ipa:"/ˈbraʊzər/", meaning_vi:"trình duyệt", example:"Which browser do you use?"},
    {id:"it-025", term:"cookies", pos:"n", ipa:"/ˈkʊkiz/", meaning_vi:"dữ liệu trình duyệt", example:"Clear your cookies."},
    {id:"it-026", term:"cybersecurity", pos:"n", ipa:"/ˌsaɪbərsɪˈkjʊrəti/", meaning_vi:"an ninh mạng", example:"Cybersecurity is a top priority."},
    {id:"it-027", term:"domain", pos:"n", ipa:"/doʊˈmeɪn/", meaning_vi:"tên miền", example:"Buy a domain for your website."},
    {id:"it-028", term:"IP address", pos:"n", ipa:"", meaning_vi:"địa chỉ IP", example:"What is my IP address?"},
    {id:"it-029", term:"operating system", pos:"n", ipa:"", meaning_vi:"hệ điều hành", example:"Windows is an operating system."},
    {id:"it-030", term:"plugin", pos:"n", ipa:"/ˈplʌɡɪn/", meaning_vi:"phần bổ trợ", example:"Install the SEO plugin."},
    {id:"it-031", term:"responsive", pos:"adj", ipa:"/rɪˈspɑːnsɪv/", meaning_vi:"tương thích di động", example:"The site must be responsive."},
    {id:"it-032", term:"server-side", pos:"adj", ipa:"", meaning_vi:"phía máy chủ", example:"PHP is a server-side language."},
    {id:"it-033", term:"client-side", pos:"adj", ipa:"", meaning_vi:"phía người dùng", example:"JavaScript runs client-side."},
    {id:"it-034", term:"syntax", pos:"n", ipa:"/ˈsɪntæks/", meaning_vi:"cú pháp", example:"Check your code syntax."},
    {id:"it-035", term:"URL", pos:"n", ipa:"", meaning_vi:"đường dẫn liên kết", example:"Paste the URL here."},
    {id:"it-036", term:"VPN", pos:"n", ipa:"", meaning_vi:"mạng riêng ảo", example:"Use a VPN for privacy."},
    {id:"it-037", term:"widget", pos:"n", ipa:"/ˈwɪdʒɪt/", meaning_vi:"tiện ích nhỏ", example:"Add a weather widget."},
    {id:"it-038", term:"API", pos:"n", ipa:"", meaning_vi:"giao diện lập trình ứng dụng", example:"Connect via the API."},
    {id:"it-039", term:"binary", pos:"n", ipa:"/ˈbaɪnəri/", meaning_vi:"nhị phân", example:"Computers use binary code."},
    {id:"it-040", term:"firmware", pos:"n", ipa:"/ˈfɜːrmwer/", meaning_vi:"phần mềm hệ thống", example:"Update the router firmware."}
  ]},
  { id: "business_finance_pro", ten: "Kinh doanh & Tài chính", items: [
    {id:"bus-001", term:"revenue", pos:"n", ipa:"/ˈrevənuː/", meaning_vi:"doanh thu", example:"The company's revenue increased this year."},
    {id:"bus-002", term:"profit", pos:"n", ipa:"/ˈprɑːfɪt/", meaning_vi:"lợi nhuận", example:"We made a huge profit from the sale."},
    {id:"bus-003", term:"investment", pos:"n", ipa:"/ɪnˈvestmənt/", meaning_vi:"sự đầu tư", example:"Buying real estate is a good investment."},
    {id:"bus-004", term:"bankruptcy", pos:"n", ipa:"/ˈbæŋkrʌptsi/", meaning_vi:"sự phá sản", example:"The firm is facing bankruptcy."},
    {id:"bus-005", term:"shareholder", pos:"n", ipa:"/ˈʃerhoʊldər/", meaning_vi:"cổ đông", example:"The shareholders voted for the new CEO."},
    {id:"bus-006", term:"dividend", pos:"n", ipa:"/ˈdɪvɪdend/", meaning_vi:"cổ tức", example:"The company pays an annual dividend."},
    {id:"bus-007", term:"asset", pos:"n", ipa:"/ˈæset/", meaning_vi:"tài sản", example:"Intellectual property is a valuable asset."},
    {id:"bus-008", term:"liability", pos:"n", ipa:"/ˌlaɪəˈbɪləti/", meaning_vi:"khoản nợ", example:"The business has more liabilities than assets."},
    {id:"bus-009", term:"negotiate", pos:"v", ipa:"/nɪˈɡoʊʃieɪt/", meaning_vi:"đàm phán", example:"We need to negotiate a better deal."},
    {id:"bus-010", term:"contract", pos:"n", ipa:"/ˈkɑːntrækt/", meaning_vi:"hợp đồng", example:"Please sign the contract by Friday."},
    {id:"bus-011", term:"budget", pos:"n", ipa:"/ˈbʌdʒɪt/", meaning_vi:"ngân sách", example:"The marketing team has a tight budget."},
    {id:"bus-012", term:"inflation", pos:"n", ipa:"/ɪnˈfleɪʃn/", meaning_vi:"lạm phát", example:"Inflation decreases the value of money."},
    {id:"bus-013", term:"interest rate", pos:"n", ipa:"", meaning_vi:"lãi suất", example:"The bank raised its interest rate."},
    {id:"bus-014", term:"loan", pos:"n", ipa:"/loʊn/", meaning_vi:"khoản vay", example:"I applied for a bank loan."},
    {id:"bus-015", term:"mortgage", pos:"n", ipa:"/ˈmɔːrɡɪdʒ/", meaning_vi:"thế chấp", example:"They took out a mortgage for the house."},
    {id:"bus-016", term:"audit", pos:"n", ipa:"/ˈɔːdɪt/", meaning_vi:"kiểm toán", example:"The company is undergoing an audit."},
    {id:"bus-017", term:"transaction", pos:"n", ipa:"/trænˈzækʃn/", meaning_vi:"giao dịch", example:"The transaction was successful."},
    {id:"bus-018", term:"entrepreneur", pos:"n", ipa:"/ˌɑːntrəprəˈnɜːr/", meaning_vi:"doanh nhân", example:"She is a successful entrepreneur."},
    {id:"bus-019", term:"startup", pos:"n", ipa:"/ˈstɑːrtʌp/", meaning_vi:"công ty khởi nghiệp", example:"He works for a tech startup."},
    {id:"bus-020", term:"merger", pos:"n", ipa:"/ˈmɜːrdʒər/", meaning_vi:"sự sáp nhập", example:"The merger of the two companies was announced."},
    {id:"bus-021", term:"acquisition", pos:"n", ipa:"/ˌækwɪˈzɪʃn/", meaning_vi:"sự thâu tóm", example:"The acquisition cost millions."},
    {id:"bus-022", term:"bankruptcy", pos:"n", ipa:"/ˈbæŋkrʌptsi/", meaning_vi:"phá sản", example:"The company filed for bankruptcy."},
    {id:"bus-023", term:"capital", pos:"n", ipa:"/ˈkæpɪtl/", meaning_vi:"vốn", example:"We need more capital to expand."},
    {id:"bus-024", term:"cash flow", pos:"n", ipa:"", meaning_vi:"dòng tiền", example:"The business has a healthy cash flow."},
    {id:"bus-025", term:"commodity", pos:"n", ipa:"/kəˈmɑːdəti/", meaning_vi:"hàng hóa", example:"Oil is a vital commodity."},
    {id:"bus-026", term:"deficit", pos:"n", ipa:"/ˈdefɪsɪt/", meaning_vi:"thâm hụt", example:"A trade deficit occurs when imports exceed exports."},
    {id:"bus-027", term:"equity", pos:"n", ipa:"/ˈekwəti/", meaning_vi:"vốn chủ sở hữu", example:"He has 30% equity in the firm."},
    {id:"bus-028", term:"gross profit", pos:"n", ipa:"", meaning_vi:"lợi nhuận gộp", example:"Calculate the gross profit first."},
    {id:"bus-029", term:"net profit", pos:"n", ipa:"", meaning_vi:"lợi nhuận ròng", example:"The net profit was lower than expected."},
    {id:"bus-030", term:"inventory", pos:"n", ipa:"/ˈɪnvəntɔːri/", meaning_vi:"hàng tồn kho", example:"Check the inventory level."},
    {id:"bus-031", term:"monopoly", pos:"n", ipa:"/məˈnɑːpəli/", meaning_vi:"độc quyền", example:"The company has a monopoly on the market."},
    {id:"bus-032", term:"outsource", pos:"v", ipa:"/ˈaʊtsɔːrs/", meaning_vi:"thuê ngoài", example:"We outsource our IT support."},
    {id:"bus-033", term:"overhead", pos:"n", ipa:"/ˈoʊvərhed/", meaning_vi:"chi phí cố định", example:"Rent is part of the overhead."},
    {id:"bus-034", term:"recession", pos:"n", ipa:"/rɪˈseʃn/", meaning_vi:"suy thoái", example:"The economy is entering a recession."},
    {id:"bus-035", term:"subsidiary", pos:"n", ipa:"/səbˈsɪdieri/", meaning_vi:"công ty con", example:"This is a subsidiary of a larger brand."},
    {id:"bus-036", term:"supply chain", pos:"n", ipa:"", meaning_vi:"chuỗi cung ứng", example:"The supply chain was disrupted."},
    {id:"bus-037", term:"tax", pos:"n", ipa:"/tæks/", meaning_vi:"thuế", example:"Pay your taxes on time."},
    {id:"bus-038", term:"wholesale", pos:"n/adj", ipa:"/ˈhoʊlseɪl/", meaning_vi:"bán buôn", example:"They buy at wholesale prices."},
    {id:"bus-039", term:"retail", pos:"n/adj", ipa:"/ˈriːteɪl/", meaning_vi:"bán lẻ", example:"Retail prices are rising."},
    {id:"bus-040", term:"yield", pos:"n/v", ipa:"/jiːld/", meaning_vi:"lợi suất/sản lượng", example:"The investment gives a high yield."}
  ]},
  { id: "marketing_pro", ten: "Marketing & Quảng cáo", items: [
    {id:"mar-001", term:"campaign", pos:"n", ipa:"/kæmˈpeɪn/", meaning_vi:"chiến dịch", example:"The new advertising campaign is successful."},
    {id:"mar-002", term:"target audience", pos:"n", ipa:"", meaning_vi:"khách hàng mục tiêu", example:"Our target audience is teenagers."},
    {id:"mar-003", term:"brand", pos:"n", ipa:"/brænd/", meaning_vi:"thương hiệu", example:"Apple is a well-known brand."},
    {id:"mar-004", term:"promote", pos:"v", ipa:"/prəˈmoʊt/", meaning_vi:"quảng bá", example:"We use social media to promote our products."},
    {id:"mar-005", term:"sponsor", pos:"v/n", ipa:"/ˈspɑːnsər/", meaning_vi:"tài trợ", example:"Nike is the main sponsor."},
    {id:"mar-006", term:"strategy", pos:"n", ipa:"/ˈstrætədʒi/", meaning_vi:"chiến lược", example:"We need a better marketing strategy."},
    {id:"mar-007", term:"market research", pos:"n", ipa:"", meaning_vi:"nghiên cứu thị trường", example:"Research shows a demand for vegan food."},
    {id:"mar-008", term:"competitor", pos:"n", ipa:"/kəmˈpetɪtər/", meaning_vi:"đối thủ cạnh tranh", example:"Stay ahead of competitors."},
    {id:"mar-009", term:"launch", pos:"v", ipa:"/lɔːntʃ/", meaning_vi:"ra mắt", example:"Launch the new product next month."},
    {id:"mar-010", term:"segment", pos:"n", ipa:"/ˈseɡmənt/", meaning_vi:"phân khúc", example:"The luxury market segment."},
    {id:"mar-011", term:"demographic", pos:"n", ipa:"/ˌdeməˈɡræfɪk/", meaning_vi:"nhân khẩu học", example:"Reach a younger demographic."},
    {id:"mar-012", term:"engagement", pos:"n", ipa:"/ɪnˈɡeɪdʒmənt/", meaning_vi:"sự tương tác", example:"The post got high engagement."},
    {id:"mar-013", term:"viral", pos:"adj", ipa:"/ˈvaɪrəl/", meaning_vi:"lan truyền nhanh", example:"The video went viral."},
    {id:"mar-014", term:"conversion", pos:"n", ipa:"/kənˈvɜːrʒn/", meaning_vi:"sự chuyển đổi", example:"High conversion rate on the site."},
    {id:"mar-015", term:"endorsement", pos:"n", ipa:"/ɪnˈdɔːrsmənt/", meaning_vi:"sự chứng thực", example:"Celebrity endorsements boost sales."},
    {id:"mar-016", term:"public relations", pos:"n", ipa:"", meaning_vi:"quan hệ công chúng", example:"The PR team is busy."},
    {id:"mar-017", term:"niche", pos:"n", ipa:"/ˈnɪtʃ/", meaning_vi:"thị trường ngách", example:"Find your niche market."},
    {id:"mar-018", term:"billboard", pos:"n", ipa:"/ˈbɪlbɔːrd/", meaning_vi:"biển quảng cáo", example:"A huge billboard on the road."},
    {id:"mar-019", term:"brochure", pos:"n", ipa:"/ˈbroʊʃʊr/", meaning_vi:"tờ rơi", example:"Hand out brochures."},
    {id:"mar-020", term:"logo", pos:"n", ipa:"/ˈloʊɡoʊ/", meaning_vi:"biểu tượng", example:"The logo is recognizable."},
    {id:"mar-021", term:"affiliate", pos:"n", ipa:"/əˈfɪlieɪt/", meaning_vi:"đại lý liên kết", example:"Join our affiliate program."},
    {id:"mar-022", term:"b2b", pos:"n", ipa:"", meaning_vi:"doanh nghiệp với doanh nghiệp", example:"We are a B2B company."},
    {id:"mar-023", term:"b2c", pos:"n", ipa:"", meaning_vi:"doanh nghiệp với khách hàng", example:"B2C marketing is different."},
    {id:"mar-024", term:"brand awareness", pos:"n", ipa:"", meaning_vi:"nhận diện thương hiệu", example:"Increase brand awareness."},
    {id:"mar-025", term:"brand loyalty", pos:"n", ipa:"", meaning_vi:"sự trung thành thương hiệu", example:"Focus on brand loyalty."},
    {id:"mar-026", term:"call to action", pos:"n", ipa:"", meaning_vi:"lời kêu gọi hành động", example:"Add a call to action button."},
    {id:"mar-027", term:"content marketing", pos:"n", ipa:"", meaning_vi:"tiếp thị nội dung", example:"Content marketing is effective."},
    {id:"mar-028", term:"copywriting", pos:"n", ipa:"", meaning_vi:"viết nội dung quảng cáo", example:"He is good at copywriting."},
    {id:"mar-029", term:"customer journey", pos:"n", ipa:"", meaning_vi:"hành trình khách hàng", example:"Map the customer journey."},
    {id:"mar-030", term:"direct marketing", pos:"n", ipa:"", meaning_vi:"tiếp thị trực tiếp", example:"Direct marketing via email."},
    {id:"mar-031", term:"email marketing", pos:"n", ipa:"", meaning_vi:"tiếp thị qua email", example:"Run an email marketing campaign."},
    {id:"mar-032", term:"influencer", pos:"n", ipa:"/ˈɪnfluənsər/", meaning_vi:"người có tầm ảnh hưởng", example:"Work with social media influencers."},
    {id:"mar-033", term:"leads", pos:"n", ipa:"/liːdz/", meaning_vi:"khách hàng tiềm năng", example:"Generate more leads."},
    {id:"mar-034", term:"market share", pos:"n", ipa:"", meaning_vi:"thị phần", example:"We have a 20% market share."},
    {id:"mar-035", term:"ppc", pos:"n", ipa:"", meaning_vi:"trả tiền cho mỗi lần nhấp chuột", example:"PPC ads are expensive."},
    {id:"mar-036", term:"roi", pos:"n", ipa:"", meaning_vi:"tỷ lệ hoàn vốn", example:"What is the ROI on this ad?"},
    {id:"mar-037", term:"seo", pos:"n", ipa:"", meaning_vi:"tối ưu hóa công cụ tìm kiếm", example:"Improve your SEO ranking."},
    {id:"mar-038", term:"slogan", pos:"n", ipa:"/ˈsloʊɡən/", meaning_vi:"khẩu hiệu", example:"A catchy slogan helps."},
    {id:"mar-039", term:"social media", pos:"n", ipa:"", meaning_vi:"mạng xã hội", example:"Promote on social media."},
    {id:"mar-040", term:"target market", pos:"n", ipa:"", meaning_vi:"thị trường mục tiêu", example:"Define your target market."}
  ]},
  { id: "ielts_academic_pro", ten: "Từ vựng IELTS Academic", items: [
    {id:"ielts-001", term:"fluctuate", pos:"v", ipa:"/ˈflʌktʃueɪt/", meaning_vi:"dao động", example:"The prices fluctuate depending on the season."},
    {id:"ielts-002", term:"plummet", pos:"v", ipa:"/ˈplʌmɪt/", meaning_vi:"giảm mạnh", example:"House prices plummeted last year."},
    {id:"ielts-003", term:"soar", pos:"v", ipa:"/sɔːr/", meaning_vi:"tăng vọt", example:"Unemployment has soared to 10%."},
    {id:"ielts-004", term:"plateau", pos:"v/n", ipa:"/plæˈtoʊ/", meaning_vi:"bình ổn", example:"Sales have reached a plateau."},
    {id:"ielts-005", term:"trend", pos:"n", ipa:"/trend/", meaning_vi:"xu hướng", example:"A downward trend in smoking."},
    {id:"ielts-006", term:"proportion", pos:"n", ipa:"/prəˈpɔːrʃn/", meaning_vi:"tỷ lệ", example:"A large proportion of students passed."},
    {id:"ielts-007", term:"majority", pos:"n", ipa:"/məˈdʒɔːrəti/", meaning_vi:"phần lớn", example:"The majority prefer to work from home."},
    {id:"ielts-008", term:"minority", pos:"n", ipa:"/maɪˈnɔːrəti/", meaning_vi:"thiểu số", example:"Only a minority voted against it."},
    {id:"ielts-009", term:"significant", pos:"adj", ipa:"/sɪɡˈnɪfɪkənt/", meaning_vi:"đáng kể", example:"A significant increase in sales."},
    {id:"ielts-010", term:"gradual", pos:"adj", ipa:"/ˈɡrædʒuəl/", meaning_vi:"dần dần", example:"A gradual improvement."},
    {id:"ielts-011", term:"steep", pos:"adj", ipa:"/stiːp/", meaning_vi:"dốc, mạnh", example:"A steep decline in profits."},
    {id:"ielts-012", term:"overall", pos:"adj", ipa:"/ˌoʊvərˈɔːl/", meaning_vi:"tổng thể", example:"The overall result is positive."},
    {id:"ielts-013", term:"respectively", pos:"adv", ipa:"/rɪˈspektɪvli/", meaning_vi:"tương ứng", example:"8 and 9, respectively."},
    {id:"ielts-014", term:"account for", pos:"v", ipa:"", meaning_vi:"chiếm (tỷ lệ)", example:"Computers account for 50% of sales."},
    {id:"ielts-015", term:"comprise", pos:"v", ipa:"/kəmˈpraɪz/", meaning_vi:"bao gồm", example:"Women comprise 60% of the staff."},
    {id:"ielts-016", term:"illustrate", pos:"v", ipa:"/ˈɪləstreɪt/", meaning_vi:"minh họa", example:"The graph illustrates growth."},
    {id:"ielts-017", term:"indicate", pos:"v", ipa:"/ˈɪndɪkeɪt/", meaning_vi:"chỉ ra", example:"Data indicates a positive trend."},
    {id:"ielts-018", term:"peak", pos:"n/v", ipa:"/piːk/", meaning_vi:"đỉnh điểm", example:"Temperature peaked at 40 degrees."},
    {id:"ielts-019", term:"dip", pos:"n", ipa:"/dɪp/", meaning_vi:"giảm nhẹ", example:"A slight dip in revenue."},
    {id:"ielts-020", term:"surpass", pos:"v", ipa:"/sərˈpæs/", meaning_vi:"vượt qua", example:"Sales surpassed last year's."},
    {id:"ielts-021", term:"acquire", pos:"v", ipa:"/əˈkwaɪər/", meaning_vi:"đạt được", example:"Acquire new skills."},
    {id:"ielts-022", term:"advocate", pos:"v", ipa:"/ˈædvəkeɪt/", meaning_vi:"ủng hộ", example:"Advocate for human rights."},
    {id:"ielts-023", term:"ambiguous", pos:"adj", ipa:"/æmˈbɪɡjuəs/", meaning_vi:"mơ hồ", example:"The instructions are ambiguous."},
    {id:"ielts-024", term:"analyze", pos:"v", ipa:"/ˈænəlaɪz/", meaning_vi:"phân tích", example:"Analyze the results."},
    {id:"ielts-025", term:"benefit", pos:"n/v", ipa:"/ˈbenɪfɪt/", meaning_vi:"lợi ích", example:"The benefits of exercise."},
    {id:"ielts-026", term:"coherent", pos:"adj", ipa:"/koʊˈhɪrənt/", meaning_vi:"mạch lạc", example:"A coherent argument."},
    {id:"ielts-027", term:"contradict", pos:"v", ipa:"/ˌkɑːntrəˈdɪkt/", meaning_vi:"mâu thuẫn", example:"His actions contradict his words."},
    {id:"ielts-028", term:"crucial", pos:"adj", ipa:"/ˈkruːʃl/", meaning_vi:"quan trọng", example:"A crucial decision."},
    {id:"ielts-029", term:"demonstrate", pos:"v", ipa:"/ˈdemənstreɪt/", meaning_vi:"chứng minh", example:"Demonstrate how it works."},
    {id:"ielts-030", term:"diverse", pos:"adj", ipa:"/daɪˈvɜːrs/", meaning_vi:"đa dạng", example:"A diverse range of topics."},
    {id:"ielts-031", term:"enhance", pos:"v", ipa:"/ɪnˈhæns/", meaning_vi:"nâng cao", example:"Enhance your performance."},
    {id:"ielts-032", term:"equivalent", pos:"adj", ipa:"/ɪˈkwɪvələnt/", meaning_vi:"tương đương", example:"The equivalent amount of money."},
    {id:"ielts-033", term:"exacerbate", pos:"v", ipa:"/ɪɡˈzæsərbeɪt/", meaning_vi:"làm trầm trọng thêm", example:"Pollution exacerbates health problems."},
    {id:"ielts-034", term:"feasible", pos:"adj", ipa:"/ˈfiːzəbl/", meaning_vi:"khả thi", example:"A feasible solution."},
    {id:"ielts-035", term:"hierarchy", pos:"n", ipa:"/ˈhaɪərɑːrki/", meaning_vi:"hệ thống cấp bậc", example:"The company hierarchy."},
    {id:"ielts-036", term:"implement", pos:"v", ipa:"/ˈɪmplɪment/", meaning_vi:"thực hiện", example:"Implement the new policy."},
    {id:"ielts-037", term:"inevitable", pos:"adj", ipa:"/ɪnˈevɪtəbl/", meaning_vi:"không thể tránh khỏi", example:"Changes are inevitable."},
    {id:"ielts-038", term:"justify", pos:"v", ipa:"/ˈdʒʌstɪfaɪ/", meaning_vi:"biện minh", example:"Justify your answer."},
    {id:"ielts-039", term:"notable", pos:"adj", ipa:"/ˈnoʊtəbl/", meaning_vi:"đáng chú ý", example:"A notable difference."},
    {id:"ielts-040", term:"perspective", pos:"n", ipa:"/pərˈspektɪv/", meaning_vi:"quan điểm", example:"A different perspective."}
  ]},
  { id: "tourism_hospitality_pro", ten: "Nhà hàng & Khách sạn", items: [
    {id:"tou-001", term:"reservation", pos:"n", ipa:"/ˌrezərˈveɪʃn/", meaning_vi:"sự đặt trước", example:"I have a reservation."},
    {id:"tou-002", term:"receptionist", pos:"n", ipa:"/rɪˈsepʃənɪst/", meaning_vi:"lễ tân", example:"Ask the receptionist."},
    {id:"tou-003", term:"accommodation", pos:"n", ipa:"/əˌkɑːməˈdeɪʃn/", meaning_vi:"chỗ ở", example:"Find cheap accommodation."},
    {id:"tou-004", term:"itinerary", pos:"n", ipa:"/aɪˈtɪnəreri/", meaning_vi:"lịch trình", example:"Our travel itinerary."},
    {id:"tou-005", term:"amenity", pos:"n", ipa:"/əˈmenəti/", meaning_vi:"tiện nghi", example:"Hotel amenities like a pool."},
    {id:"tou-006", term:"vacancy", pos:"n", ipa:"/ˈveɪkənsi/", meaning_vi:"phòng trống", example:"No vacancies tonight."},
    {id:"tou-007", term:"concierge", pos:"n", ipa:"/kɑːnsiˈerʒ/", meaning_vi:"hỗ trợ khách hàng", example:"Book a taxi via the concierge."},
    {id:"tou-008", term:"housekeeping", pos:"n", ipa:"/ˈhaʊskiːpɪŋ/", meaning_vi:"dọn phòng", example:"Housekeeping at 10 AM."},
    {id:"tou-009", term:"bellboy", pos:"n", ipa:"/ˈbelbɔɪ/", meaning_vi:"nhân viên hành lý", example:"The bellboy took the bags."},
    {id:"tou-010", term:"suite", pos:"n", ipa:"/swiːt/", meaning_vi:"phòng thượng hạng", example:"A luxury suite."},
    {id:"tou-011", term:"complimentary", pos:"adj", ipa:"/ˌkɑːmplɪˈmentri/", meaning_vi:"miễn phí", example:"Breakfast is complimentary."},
    {id:"tou-012", term:"deposit", pos:"n", ipa:"/dɪˈpɑːzɪt/", meaning_vi:"tiền đặt cọc", example:"Pay a deposit."},
    {id:"tou-013", term:"shuttle", pos:"n", ipa:"/ˈʃʌtl/", meaning_vi:"xe đưa đón", example:"Free airport shuttle."},
    {id:"tou-014", term:"sightseeing", pos:"n", ipa:"/ˈsaɪtsiːɪŋ/", meaning_vi:"ngắm cảnh", example:"Go sightseeing all day."},
    {id:"tou-015", term:"souvenir", pos:"n", ipa:"/ˌsuːvəˈnɪr/", meaning_vi:"quà lưu niệm", example:"I bought a souvenir."},
    {id:"tou-016", term:"excursion", pos:"n", ipa:"/ɪkˈskɜːrʒn/", meaning_vi:"chuyến tham quan", example:"An excursion to the mountains."},
    {id:"tou-017", term:"cuisine", pos:"n", ipa:"/kwɪˈziːn/", meaning_vi:"ẩm thực", example:"Italian cuisine."},
    {id:"tou-018", term:"buffet", pos:"n", ipa:"/bəˈfeɪ/", meaning_vi:"tiệc tự chọn", example:"Breakfast buffet at 6 AM."},
    {id:"tou-019", term:"check-in", pos:"v", ipa:"", meaning_vi:"nhận phòng", example:"What time is check-in?"},
    {id:"tou-020", term:"check-out", pos:"v", ipa:"", meaning_vi:"trả phòng", example:"Check-out at 12 PM."},
    {id:"tou-021", term:"all-inclusive", pos:"adj", ipa:"", meaning_vi:"trọn gói", example:"An all-inclusive resort."},
    {id:"tou-022", term:"boarding pass", pos:"n", ipa:"", meaning_vi:"thẻ lên máy bay", example:"Show your boarding pass."},
    {id:"tou-023", term:"carry-on", pos:"n", ipa:"", meaning_vi:"hành lý xách tay", example:"Is this your carry-on?"},
    {id:"tou-024", term:"customs", pos:"n", ipa:"/ˈkʌstəmz/", meaning_vi:"hải quan", example:"Go through customs."},
    {id:"tou-025", term:"delayed", pos:"adj", ipa:"/dɪˈleɪd/", meaning_vi:"bị trễ", example:"The flight is delayed."},
    {id:"tou-026", term:"departure", pos:"n", ipa:"/dɪˈpɑːrtʃər/", meaning_vi:"khởi hành", example:"Check the departure board."},
    {id:"tou-027", term:"destination", pos:"n", ipa:"/ˌdestɪˈneɪʃn/", meaning_vi:"điểm đến", example:"What is your destination?"},
    {id:"tou-028", term:"duty-free", pos:"adj", ipa:"", meaning_vi:"miễn thuế", example:"Buy duty-free perfume."},
    {id:"tou-029", term:"ecotourism", pos:"n", ipa:"/ˈiːkoʊtʊrɪzəm/", meaning_vi:"du lịch sinh thái", example:"Ecotourism is growing."},
    {id:"tou-030", term:"high season", pos:"n", ipa:"", meaning_vi:"mùa cao điểm", example:"Prices rise in high season."},
    {id:"tou-031", term:"low season", pos:"n", ipa:"", meaning_vi:"mùa thấp điểm", example:"Travel in low season to save money."},
    {id:"tou-032", term:"landmark", pos:"n", ipa:"/ˈlændmɑːrk/", meaning_vi:"địa danh nổi tiếng", example:"The Eiffel Tower is a landmark."},
    {id:"tou-033", term:"layover", pos:"n", ipa:"/ˈleɪoʊvər/", meaning_vi:"quá cảnh", example:"A 5-hour layover in Tokyo."},
    {id:"tou-034", term:"overbook", pos:"v", ipa:"/ˌoʊvərˈbʊk/", meaning_vi:"đặt quá chỗ", example:"The hotel is overbooked."},
    {id:"tou-035", term:"package tour", pos:"n", ipa:"", meaning_vi:"tour trọn gói", example:"We booked a package tour."},
    {id:"tou-036", term:"passport", pos:"n", ipa:"/ˈpæspɔːrt/", meaning_vi:"hộ chiếu", example:"Don't lose your passport."},
    {id:"tou-037", term:"resort", pos:"n", ipa:"/rɪˈzɔːrt/", meaning_vi:"khu nghỉ dưỡng", example:"A beach resort."},
    {id:"tou-038", term:"sightseeing", pos:"n", ipa:"", meaning_vi:"ngắm cảnh", example:"Let's go sightseeing."},
    {id:"tou-039", term:"valet", pos:"n", ipa:"/væˈleɪ/", meaning_vi:"nhân viên đỗ xe", example:"Give the keys to the valet."},
    {id:"tou-040", term:"voucher", pos:"n", ipa:"/ˈvaʊtʃər/", meaning_vi:"phiếu giảm giá/quà tặng", example:"I
