const group_3_decks = [
    {
        id: "topic_foods",
        ten: "Foods (Đồ ăn)",
        items: [
            { id: "f1", term: "Pizza", pos: "n.", ipa: "/ˈpiːtsə/", meaning_vi: "Bánh pizza", example: "I love eating pizza on weekends." },
            { id: "f2", term: "Hamburger", pos: "n.", ipa: "/ˈhæmbɜːrɡər/", meaning_vi: "Bánh kẹp thịt", example: "He ordered a hamburger and french fries." },
            { id: "f3", term: "Salad", pos: "n.", ipa: "/ˈsæləd/", meaning_vi: "Rau trộn", example: "She had a healthy green salad for lunch." },
            { id: "f4", term: "Bread", pos: "n.", ipa: "/bred/", meaning_vi: "Bánh mì", example: "I bought a loaf of fresh bread." },
            { id: "f5", term: "Cheese", pos: "n.", ipa: "/tʃiːz/", meaning_vi: "Phô mai", example: "This cheese is made from goat's milk." },
            { id: "f6", term: "Butter", pos: "n.", ipa: "/ˈbʌtər/", meaning_vi: "Bơ", example: "Spread some butter on the toast." },
            { id: "f7", term: "Chicken", pos: "n.", ipa: "/ˈtʃɪkɪn/", meaning_vi: "Thịt gà", example: "We are having roast chicken for dinner." },
            { id: "f8", term: "Beef", pos: "n.", ipa: "/biːf/", meaning_vi: "Thịt bò", example: "He likes his beef cooked medium-rare." },
            { id: "f9", term: "Pork", pos: "n.", ipa: "/pɔːrk/", meaning_vi: "Thịt heo", example: "Pork chops are on sale today." },
            { id: "f10", term: "Fish", pos: "n.", ipa: "/fɪʃ/", meaning_vi: "Cá", example: "Eating fish is good for your brain." },
            { id: "f11", term: "Rice", pos: "n.", ipa: "/raɪs/", meaning_vi: "Gạo, cơm", example: "Rice is a staple food in Asia." },
            { id: "f12", term: "Noodle", pos: "n.", ipa: "/ˈnuːdl/", meaning_vi: "Sợi mì", example: "I like spicy chicken noodles." },
            { id: "f13", term: "Soup", pos: "n.", ipa: "/suːp/", meaning_vi: "Món súp, canh", example: "Hot soup is perfect for a cold day." },
            { id: "f14", term: "Sandwich", pos: "n.", ipa: "/ˈsændwɪtʃ/", meaning_vi: "Bánh mì kẹp", example: "I made a ham and cheese sandwich." },
            { id: "f15", term: "Sausage", pos: "n.", ipa: "/ˈsɔːsɪdʒ/", meaning_vi: "Xúc xích", example: "They grilled some sausages for the picnic." },
            { id: "f16", term: "Bacon", pos: "n.", ipa: "/ˈbeɪkən/", meaning_vi: "Thịt xông khói", example: "I smell bacon frying in the kitchen." },
            { id: "f17", term: "Egg", pos: "n.", ipa: "/eɡ/", meaning_vi: "Quả trứng", example: "She boiled an egg for breakfast." },
            { id: "f18", term: "Tofu", pos: "n.", ipa: "/ˈtəʊfuː/", meaning_vi: "Đậu hũ", example: "Tofu is a great source of protein for vegetarians." },
            { id: "f19", term: "Potato", pos: "n.", ipa: "/pəˈteɪtəʊ/", meaning_vi: "Khoai tây", example: "Mashed potatoes are my favorite side dish." },
            { id: "f20", term: "Tomato", pos: "n.", ipa: "/təˈmɑːtəʊ/", meaning_vi: "Cà chua", example: "Add some fresh tomatoes to the salad." },
            { id: "f21", term: "Onion", pos: "n.", ipa: "/ˈʌnjən/", meaning_vi: "Hành tây", example: "Chopping onions makes me cry." },
            { id: "f22", term: "Garlic", pos: "n.", ipa: "/ˈɡɑːrlɪk/", meaning_vi: "Tỏi", example: "Garlic adds a lot of flavor to the sauce." },
            { id: "f23", term: "Mushroom", pos: "n.", ipa: "/ˈmʌʃrʊm/", meaning_vi: "Nấm", example: "I ordered a mushroom pizza." },
            { id: "f24", term: "Cake", pos: "n.", ipa: "/keɪk/", meaning_vi: "Bánh ngọt", example: "She baked a chocolate cake for his birthday." },
            { id: "f25", term: "Cookie", pos: "n.", ipa: "/ˈkʊki/", meaning_vi: "Bánh quy", example: "Would you like a chocolate chip cookie?" },
            { id: "f26", term: "Chocolate", pos: "n.", ipa: "/ˈtʃɒklət/", meaning_vi: "Sô-cô-la", example: "Dark chocolate is my favorite." },
            { id: "f27", term: "Ice cream", pos: "n.", ipa: "/ˌaɪs ˈkriːm/", meaning_vi: "Kem", example: "We ate vanilla ice cream for dessert." },
            { id: "f28", term: "Candy", pos: "n.", ipa: "/ˈkændi/", meaning_vi: "Kẹo", example: "Eating too much candy is bad for your teeth." },
            { id: "f29", term: "Honey", pos: "n.", ipa: "/ˈhʌni/", meaning_vi: "Mật ong", example: "I put honey in my tea instead of sugar." },
            { id: "f30", term: "Jam", pos: "n.", ipa: "/dʒæm/", meaning_vi: "Mứt", example: "She spread strawberry jam on her toast." },
            { id: "f31", term: "Yogurt", pos: "n.", ipa: "/ˈjɒɡərt/", meaning_vi: "Sữa chua", example: "Greek yogurt is very healthy." },
            { id: "f32", term: "Milk", pos: "n.", ipa: "/mɪlk/", meaning_vi: "Sữa", example: "Drink a glass of milk before bed." },
            { id: "f33", term: "Coffee", pos: "n.", ipa: "/ˈkɒfi/", meaning_vi: "Cà phê", example: "I need a cup of coffee to wake up." },
            { id: "f34", term: "Tea", pos: "n.", ipa: "/tiː/", meaning_vi: "Trà", example: "Would you like a cup of green tea?" },
            { id: "f35", term: "Juice", pos: "n.", ipa: "/dʒuːs/", meaning_vi: "Nước ép", example: "Fresh apple juice is delicious." },
            { id: "f36", term: "Water", pos: "n.", ipa: "/ˈwɔːtər/", meaning_vi: "Nước", example: "Remember to drink plenty of water." },
            { id: "f37", term: "Wine", pos: "n.", ipa: "/waɪn/", meaning_vi: "Rượu vang", example: "They shared a bottle of red wine." },
            { id: "f38", term: "Beer", pos: "n.", ipa: "/bɪr/", meaning_vi: "Bia", example: "He ordered a cold beer at the bar." },
            { id: "f39", term: "Steak", pos: "n.", ipa: "/steɪk/", meaning_vi: "Bít tết", example: "We went to a restaurant for steak." },
            { id: "f40", term: "Seafood", pos: "n.", ipa: "/ˈsiːfuːd/", meaning_vi: "Hải sản", example: "This restaurant serves the best seafood in town." }
        ]
    },
    {
        id: "topic_fruits",
        ten: "Fruits (Trái cây)",
        items: [
            { id: "fr1", term: "Apple", pos: "n.", ipa: "/ˈæpl/", meaning_vi: "Quả táo", example: "An apple a day keeps the doctor away." },
            { id: "fr2", term: "Banana", pos: "n.", ipa: "/bəˈnænə/", meaning_vi: "Quả chuối", example: "Monkeys love to eat bananas." },
            { id: "fr3", term: "Orange", pos: "n.", ipa: "/ˈɒrɪndʒ/", meaning_vi: "Quả cam", example: "I drink freshly squeezed orange juice." },
            { id: "fr4", term: "Grape", pos: "n.", ipa: "/ɡreɪp/", meaning_vi: "Quả nho", example: "These green grapes are very sweet." },
            { id: "fr5", term: "Strawberry", pos: "n.", ipa: "/ˈstrɔːbəri/", meaning_vi: "Dâu tây", example: "She put strawberries on her cake." },
            { id: "fr6", term: "Watermelon", pos: "n.", ipa: "/ˈwɔːtərmelən/", meaning_vi: "Dưa hấu", example: "Watermelon is refreshing in the summer." },
            { id: "fr7", term: "Lemon", pos: "n.", ipa: "/ˈlemən/", meaning_vi: "Quả chanh vàng", example: "Add a slice of lemon to the tea." },
            { id: "fr8", term: "Lime", pos: "n.", ipa: "/laɪm/", meaning_vi: "Quả chanh xanh", example: "Lime juice is great for cocktails." },
            { id: "fr9", term: "Mango", pos: "n.", ipa: "/ˈmæŋɡəʊ/", meaning_vi: "Quả xoài", example: "This ripe mango is delicious." },
            { id: "fr10", term: "Pineapple", pos: "n.", ipa: "/ˈpaɪnæpl/", meaning_vi: "Quả dứa (thơm)", example: "I like pineapple on my pizza." },
            { id: "fr11", term: "Papaya", pos: "n.", ipa: "/pəˈpaɪə/", meaning_vi: "Quả đu đủ", example: "Papaya is rich in vitamins." },
            { id: "fr12", term: "Peach", pos: "n.", ipa: "/piːtʃ/", meaning_vi: "Quả đào", example: "The peach is very soft and juicy." },
            { id: "fr13", term: "Pear", pos: "n.", ipa: "/per/", meaning_vi: "Quả lê", example: "She bought a bag of pears at the market." },
            { id: "fr14", term: "Plum", pos: "n.", ipa: "/plʌm/", meaning_vi: "Quả mận", example: "He ate a sweet purple plum." },
            { id: "fr15", term: "Cherry", pos: "n.", ipa: "/ˈtʃeri/", meaning_vi: "Quả anh đào", example: "There is a cherry on top of the ice cream." },
            { id: "fr16", term: "Blueberry", pos: "n.", ipa: "/ˈbluːbəri/", meaning_vi: "Việt quất", example: "I love blueberry muffins." },
            { id: "fr17", term: "Coconut", pos: "n.", ipa: "/ˈkəʊkənʌt/", meaning_vi: "Quả dừa", example: "Coconut water is very hydrating." },
            { id: "fr18", term: "Kiwi", pos: "n.", ipa: "/ˈkiːwi/", meaning_vi: "Quả kiwi", example: "Kiwi has a lot of vitamin C." },
            { id: "fr19", term: "Avocado", pos: "n.", ipa: "/ˌævəˈkɑːdəʊ/", meaning_vi: "Quả bơ", example: "Avocado toast is a popular breakfast." },
            { id: "fr20", term: "Pomegranate", pos: "n.", ipa: "/ˈpɒmɪɡrænɪt/", meaning_vi: "Quả lựu", example: "Opening a pomegranate can be messy." },
            { id: "fr21", term: "Fig", pos: "n.", ipa: "/fɪɡ/", meaning_vi: "Quả sung", example: "Dried figs are a healthy snack." },
            { id: "fr22", term: "Date", pos: "n.", ipa: "/deɪt/", meaning_vi: "Quả chà là", example: "Dates are naturally very sweet." },
            { id: "fr23", term: "Apricot", pos: "n.", ipa: "/ˈeɪprɪkɒt/", meaning_vi: "Quả mơ", example: "She made apricot jam yesterday." },
            { id: "fr24", term: "Guava", pos: "n.", ipa: "/ˈɡwɑːvə/", meaning_vi: "Quả ổi", example: "Guava is a tropical fruit." },
            { id: "fr25", term: "Dragon fruit", pos: "n.", ipa: "/ˈdræɡən fruːt/", meaning_vi: "Thanh long", example: "Dragon fruit looks very exotic." },
            { id: "fr26", term: "Passion fruit", pos: "n.", ipa: "/ˈpæʃn fruːt/", meaning_vi: "Chanh dây", example: "I love the smell of passion fruit." },
            { id: "fr27", term: "Lychee", pos: "n.", ipa: "/ˈliːtʃiː/", meaning_vi: "Quả vải", example: "Lychees are very popular in Asia." },
            { id: "fr28", term: "Jackfruit", pos: "n.", ipa: "/ˈdʒækfruːt/", meaning_vi: "Quả mít", example: "Jackfruit is the largest tree-borne fruit." },
            { id: "fr29", term: "Durian", pos: "n.", ipa: "/ˈdʊəriən/", meaning_vi: "Sầu riêng", example: "Durian has a very strong smell." },
            { id: "fr30", term: "Mangosteen", pos: "n.", ipa: "/ˈmæŋɡəstiːn/", meaning_vi: "Măng cụt", example: "Mangosteen is often called the queen of fruits." },
            { id: "fr31", term: "Rambutan", pos: "n.", ipa: "/ræmˈbuːtn/", meaning_vi: "Chôm chôm", example: "Rambutan looks like a hairy lychee." },
            { id: "fr32", term: "Longan", pos: "n.", ipa: "/ˈlɒŋɡən/", meaning_vi: "Nhãn", example: "Longan is very sweet and juicy." },
            { id: "fr33", term: "Grapefruit", pos: "n.", ipa: "/ˈɡreɪpfruːt/", meaning_vi: "Quả bưởi", example: "I have half a grapefruit for breakfast." },
            { id: "fr34", term: "Tangerine", pos: "n.", ipa: "/ˌtændʒəˈriːn/", meaning_vi: "Quả quýt", example: "Tangerines are easy to peel." },
            { id: "fr35", term: "Persimmon", pos: "n.", ipa: "/pərˈsɪmən/", meaning_vi: "Quả hồng", example: "Dried persimmons are a delicious treat." },
            { id: "fr36", term: "Starfruit", pos: "n.", ipa: "/ˈstɑːrfruːt/", meaning_vi: "Quả khế", example: "Slices of starfruit look like stars." },
            { id: "fr37", term: "Cranberry", pos: "n.", ipa: "/ˈkrænbəri/", meaning_vi: "Nam việt quất", example: "We usually have cranberry sauce with turkey." },
            { id: "fr38", term: "Raspberry", pos: "n.", ipa: "/ˈræzbəri/", meaning_vi: "Quả mâm xôi", example: "I picked fresh raspberries from the garden." },
            { id: "fr39", term: "Blackberry", pos: "n.", ipa: "/ˈblækbəri/", meaning_vi: "Mâm xôi đen", example: "Watch out for thorns when picking blackberries." },
            { id: "fr40", term: "Melon", pos: "n.", ipa: "/ˈmelən/", meaning_vi: "Dưa lưới", example: "We had slices of sweet melon for dessert." }
        ]
    }
];
